"""The ARGUMENT-SPINE view — a typed model of the book's linear argument: an ordered run of numbered
claims, plus a labeling of every chapter by the spine claim(s) it advances. The sixth sibling model beside
outline / outcomes / concepts / big-ideas / claims (directive book/_design/book-editorial-discipline-directive-260802.md
Part A Task 1 / Part B Phase 1).

WHY A NEW MODEL, NOT AN EXTENSION.  The claims model holds unordered stances, each with the contradiction
predicate an audit checks prose against. The Big-Ideas model holds six fixed landing slots. A spine claim
is neither: it is an ordered STEP in the argument the book makes from front to back, and its distinctive
fields — `order`, seed provenance, reconciliation links, chapter advancement — belong to no sibling. The
same rule that earned the claims model its own file (a new field none of the siblings carry) applies here.

RECONCILE, DON'T RESTATE.  The spine is not a second source for the siblings' content. Each spine claim
carries `reconciles` links: the claim ids (claims_declared.json), big-idea slugs (landing-big-ideas.json),
and What-This-Book-Argues claim slugs (argues_claims_declared.json) it subsumes into one argument step, plus
the author's seed-statement numbers it descends from. The structural check holds every link RESOLVING (AS3,
across all three namespaces) and the claim + big-idea reconciliation COMPLETE in reverse (AS4) — so a stance
added to a sibling model without a place in the argument is a finding, not a silent orphan. AS4 does not
extend to argues_claims: a WTBA claim with no premise pointing at it is legitimate, so that namespace gets
the forward integrity gate only.

CHAPTER LABELS LIVE HERE, NOT IN THE OUTLINE.  The outline model is derived from the book on every run —
it has no hand-authored source a judgment field could live in — and the outcomes model is pedagogical. The
per-chapter advancement judgment is argument-structural, so it homes here: `chapter_advances` maps every
outline chapter slug to the spine ids it advances, and the generated artifact projects the reverse
(`advanced_by`, per spine claim). Exhaustiveness over the outline's chapters is invariant AS5.

FLAGS ARE DERIVED, INFORMATIONAL, AND NEVER GATE.  Two families of editorial smell are computed by the
generator into the artifact's `flags` block, never authored. CHAPTER side (the directive's Phase-1c
worklist): a non-exempt chapter advancing 0 spine claims (suspect: why does it exist?) or more than
FOCUS_CAP (probably unfocused). CLAIM side (the depth/overmapping sensors): a non-exempt claim advanced by
0 chapters (a real gap) or only within Part 0/1 (front-loaded/shallow); and a claim advanced by more than
OVERMAP_CAP chapters (an overmapping-audit surface — its breadth is worth re-examining chapter by chapter).
Chapters whose breadth or silence is their job carry a `chapter_exemptions` reason from the closed
EXEMPT_REASONS enum; genuine premises carry a `claim_exemptions` reason from CLAIM_EXEMPT_REASONS so they do
not surface as thin. All flags are surfaced, never a gate finding.

FRESHNESS (AS8) — the CS5 analogue for the spine.  Each declared claim carries a `reviewed_hash`: the hash
of the statement wording its chapter labels were reviewed against. AS8 re-hashes the current statement and
reddens a claim whose wording has changed since review — the labels on its advancing chapters may no longer
hold. A re-review updates the hash (editing the declared file); regenerating the artifact never refreshes it.

Run `python3 book-models/argument_spine_model.py regenerate` to write the artifact; `... verify` to
drift-check; `... spine` to print the argument; `... flags` to print the focus + health worklist; `...
hashes` to print each claim's current statement hash (for re-seeding a reviewed_hash after a re-review).
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import outline_model as om  # noqa: E402 — the outline view is the chapter tree the labels map onto

_HERE = os.path.dirname(os.path.abspath(__file__))
_ARTIFACT = os.path.join(_HERE, "argument-spine.json")
_DECLARED = os.path.join(_HERE, "argument_spine_declared.json")

_PROVENANCE = ("GENERATED by book-models/argument_spine_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/argument_spine_model.py regenerate`. Derived from the hand-authored "
               "spine + chapter labels in book-models/argument_spine_declared.json, resolved against the "
               "outline + the claims + big-ideas sibling models.")

_MODEL_NOTE = (
    "The argument-spine model holds the book's linear argument as an ordered run of claims, each "
    "reconciling the author's seed statements, the claims model, and the Big-Ideas model into one step — "
    "plus the per-chapter labeling of which steps each chapter advances. The `flags` block is DERIVED "
    "editorial signal and never gates: CHAPTER-side (a non-exempt chapter advancing 0 steps is suspect; one "
    "advancing more than the focus cap is probably unfocused — the directive's Phase-1c worklist) AND "
    "CLAIM-side health (a non-exempt claim advanced by 0 chapters is a gap; one advanced only within "
    "Part 0/1 is front-loaded/shallow; one advanced by more than the overmap cap is an overmapping-audit "
    "surface). Per-claim `reviewed_hash` seeds the AS8 freshness sensor: a statement edited without a "
    "re-review reddens its advancing chapters. Exempt chapters (preface / conclusion / discussion / "
    "end-of-part synthesis / apparatus) and exempt claims (genuine front-loaded-by-design premises) are the "
    "ones whose breadth, silence, or shallow reach is their job.")

#: The `statement` word cap — a spine claim is one argument step, not a paragraph. Counted with
#: `statement.split()`, mirroring the claims model's C6. Higher than the claims model's 18 because a spine
#: step often joins a cause to its consequence in one sentence — and, for the alignment-thesis step, the
#: thesis plus its two hierarchical moves (constrain first; sense where prevention is incomplete), which is
#: the step's whole correction and does not survive compression. That author-ratified statement sets the cap.
WORD_CAP = 32

#: The spine's size bounds — the directive asks for the argument in ~10–20 numbered statements (AS2).
SPINE_MIN, SPINE_MAX = 10, 20

#: A non-exempt chapter advancing more than this many spine claims is flagged probably-unfocused (the
#: directive's editorial smell). Breadth beyond the cap is only appropriate for the exempt kinds.
FOCUS_CAP = 3

#: A spine claim advanced by MORE than this many chapters is flagged for an OVERMAPPING audit — the
#: claim-side symmetry of the chapter over-cap flag. The two central theses (modeling ~18, alignment ~13)
#: and the governance thesis (~11) sit above it; the next-broadest claim advances 7, a clean gap. The flag
#: never gates — it names the claims whose breadth is worth re-examining chapter by chapter.
OVERMAP_CAP = 10

#: The Part prefixes that count as "front-loaded". A claim advanced only within Part 0 (front matter) and
#: Part 1 (the motivating overview) is shallow: stated up front and never re-advanced in the body — the
#: known case is `churn-is-the-limit`, advanced only by the preface and 1.1.
FRONT_PARTS = ("0", "1")

#: The CLOSED reasons a spine claim may be exempt from the claim-depth flags (AS9) — the claim-side analogue
#: of EXEMPT_REASONS. `front-loaded-by-design` marks a genuine premise stated once, up front, and assumed
#: thereafter (it needs no dedicated body chapter); `bridge` marks a structural step that divides or joins
#: other claims rather than earning chapters of its own. A reason the orchestrator ratifies before use.
CLAIM_EXEMPT_REASONS = ("front-loaded-by-design", "bridge")

#: The CLOSED reasons a chapter may be exempt from the focus flags (AS7). `apparatus` covers
#: non-argumentative front/back matter (acknowledgments); `overview` covers a deliberate whole-book
#: survey chapter — a reason the orchestrator ratifies before it is used.
EXEMPT_REASONS = ("preface", "conclusion", "discussion", "end-of-part-synthesis", "apparatus", "overview")

#: The author's 10 seed statements (directive Part A Task 1) — the valid `seeds` numbers (AS2).
SEED_MIN, SEED_MAX = 1, 10


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class SpineClaim:
    """One ordered step of the book's argument. `id` is the kebab join key; `order` its 1-based position;
    `seeds` the author seed-statement numbers it descends from; `reconciles_claims` / `reconciles_big_ideas`
    / `reconciles_argues_claims` the sibling-model entries it subsumes (discussion claims, landing Big Ideas,
    and What-This-Book-Argues claims). `feeds` the later spine ids this step creates the surface for (the
    typed causal edge; AS10 holds it forward-pointing). `advanced_by` is DERIVED — the chapters labeled with
    this step."""
    id: str
    order: int
    statement: str
    seeds: list[int]
    reconciles_claims: list[str]
    reconciles_big_ideas: list[str]
    reconciles_argues_claims: list[str]
    feeds: list[str] = field(default_factory=list)   # AS10: spine ids this step CREATES THE SURFACE FOR (must point forward)
    exempt: "str | None" = None                      # claim-depth exemption reason (front-loaded-by-design / bridge) or None
    reviewed_hash: str = ""                          # AS8 seed: the statement hash the chapter labels were reviewed against
    quantifiable: bool = False                       # W-LEDGER: is this the kind of claim a metric could bear weight for?
    reality_claim: bool = False                      # W-LEDGER: an empirical/positioned claim about reality (vs definitional/normative)
    measurand: str = ""                              # W-LEDGER: the real-world quantity a metric would measure (optional)
    word_count: int = 0                              # derived: statement.split() length
    statement_hash: str = ""                         # derived: current hash of `statement`
    advanced_by: list[str] = field(default_factory=list)  # derived: chapter slugs that advance this step
    body_depth: int = 0                              # derived: advancing chapters OUTSIDE Part 0/1
    front_loaded: bool = False                       # derived: advanced only within Part 0/1 (thin)
    overmapped: bool = False                         # derived: advanced by > OVERMAP_CAP chapters
    fresh: bool = True                               # derived: reviewed_hash == statement_hash (AS8)


@dataclass
class ChapterLabel:
    """One chapter's argument label: the spine ids it advances, and its exemption (or None)."""
    slug: str
    advances: list[str]
    exempt: "str | None"


@dataclass
class SpineModel:
    spine: list[SpineClaim]
    chapters: list[ChapterLabel]

    def flags(self) -> "dict[str, list[dict]]":
        """The DERIVED editorial flags — CHAPTER-side focus smells and CLAIM-side health smells; never gated.

        Chapter side (the directive's Phase-1c worklist):
        - zero_claim_suspects: a non-exempt chapter advancing 0 spine claims.
        - over_cap_unfocused: a non-exempt chapter advancing more than FOCUS_CAP claims.

        Claim side (the depth + overmapping sensors; claim-exempt premises are skipped):
        - thin_claim_gaps: a claim advanced by 0 chapters — a real gap.
        - thin_claims_front_loaded: a claim advanced only within Part 0/1 (body_depth 0) — front-loaded.
        - overmapped_claims: a claim advanced by more than OVERMAP_CAP chapters — an overmapping-audit
          surface (its breadth is worth re-examining chapter by chapter). NOT skipped for exemptions —
          overmapping is orthogonal to depth-exemption."""
        zero = [{"chapter": c.slug, "advances": 0}
                for c in self.chapters if not c.exempt and not c.advances]
        over = [{"chapter": c.slug, "advances": len(c.advances), "spine_ids": list(c.advances)}
                for c in self.chapters if not c.exempt and len(c.advances) > FOCUS_CAP]
        thin_gaps = [{"claim": s.id, "advanced_by": 0}
                     for s in self.spine if not s.exempt and not s.advanced_by]
        thin_front = [{"claim": s.id, "advanced_by": len(s.advanced_by), "body_depth": s.body_depth,
                       "chapters": list(s.advanced_by)}
                      for s in self.spine if not s.exempt and s.front_loaded]
        overmapped = [{"claim": s.id, "advanced_by": len(s.advanced_by), "chapters": list(s.advanced_by)}
                      for s in self.spine if s.overmapped]
        return {"zero_claim_suspects": zero, "over_cap_unfocused": over,
                "thin_claim_gaps": thin_gaps, "thin_claims_front_loaded": thin_front,
                "overmapped_claims": overmapped}


# ---- load + build -----------------------------------------------------------------------------------

def _statement_hash(statement: str) -> str:
    """The AS8 freshness key: a short, stable digest of a claim's statement wording. A changed statement
    changes this hash, so any chapter reviewed against the old wording reddens until re-reviewed."""
    return hashlib.sha256(statement.encode("utf-8")).hexdigest()[:12]


def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def derive_model() -> SpineModel:
    """Build the spine model from the hand-authored declarations — the single derivation the regen and the
    drift check share. Spine order is the argument's own order; chapters follow the outline's order, so the
    artifact is deterministic."""
    decl = _load_declared()
    claim_exempt: "dict[str, str]" = decl.get("claim_exemptions", {})
    spine = [SpineClaim(
        id=d["id"], order=d["order"], statement=d["statement"],
        seeds=list(d.get("seeds", [])),
        reconciles_claims=list(d.get("reconciles", {}).get("claims", [])),
        reconciles_big_ideas=list(d.get("reconciles", {}).get("big_ideas", [])),
        reconciles_argues_claims=list(d.get("reconciles", {}).get("argues_claims", [])),
        feeds=list(d.get("feeds", [])),
        exempt=claim_exempt.get(d["id"]),
        reviewed_hash=d.get("reviewed_hash", ""),
        quantifiable=bool(d.get("quantifiable", False)),
        reality_claim=bool(d.get("reality_claim", False)),
        measurand=d.get("measurand", ""),
        word_count=len(d["statement"].split()),
        statement_hash=_statement_hash(d["statement"]),
    ) for d in decl["spine"]]
    spine.sort(key=lambda s: s.order)

    import chapter_identity_model as chapter_identity  # noqa: E402 — sibling book-model
    advances: "dict[str, list[str]]" = decl.get("chapter_advances", {})
    exemptions: "dict[str, str]" = decl.get("chapter_exemptions", {})
    outline = om.derive_outline()

    def _lab(slug: str) -> str:
        # chapter_advances / chapter_exemptions are keyed by the number-free identity LABEL now; map each
        # outline slug to its label to look the labels up. Falls back to the slug for a chapter with no
        # identity row (should not happen — CI3 asserts full outline coverage).
        return chapter_identity.label_for_slug(slug) or slug

    chapters = [ChapterLabel(slug=c.slug, advances=list(advances.get(_lab(c.slug), [])),
                             exempt=exemptions.get(_lab(c.slug)))
                for c in outline.chapters]
    # Any label keyed to a chapter the outline no longer defines still surfaces (AS5 reddens it), appended
    # after the outline's chapters so the artifact never silently drops a hand-authored label.
    known = {_lab(c.slug) for c in outline.chapters}
    for label in advances:
        if label not in known:
            chapters.append(ChapterLabel(slug=label, advances=list(advances[label]),
                                         exempt=exemptions.get(label)))

    # Derive the reverse projection: spine claim -> chapters that advance it.
    by_id = {s.id: s for s in spine}
    for ch in chapters:
        for sid in ch.advances:
            if sid in by_id:
                by_id[sid].advanced_by.append(ch.slug)
    # Derive per-claim health from the reverse projection: depth (front-loaded / body-depth), overmapping,
    # and freshness. `part_of` reads the leading number of a chapter slug (0.1-preface -> "0").
    def _part_of(slug: str) -> str:
        return slug.split(".", 1)[0]
    for s in spine:
        parts = {_part_of(slug) for slug in s.advanced_by}
        s.body_depth = sum(1 for slug in s.advanced_by if _part_of(slug) not in FRONT_PARTS)
        s.front_loaded = bool(s.advanced_by) and parts <= set(FRONT_PARTS)
        s.overmapped = len(s.advanced_by) > OVERMAP_CAP
        s.fresh = s.reviewed_hash == s.statement_hash
    return SpineModel(spine=spine, chapters=chapters)


# ---- sibling-model key sets -------------------------------------------------------------------------

def _load_json(path: str) -> "dict | None":
    return json.load(open(path, encoding="utf-8")) if os.path.isfile(path) else None


def _sibling_sets() -> "tuple[set[str], set[str], set[str]]":
    """(claim_ids, big_idea_slugs, argues_claim_slugs) — the resolve targets for `reconciles`, read at check
    time from the sibling declared sources; a single source of truth, no snapshot. AS3 resolves all three;
    AS4 (reverse completeness) covers only claims + big_ideas — a WTBA claim with no premise pointing at it
    is legitimate, so `argues_claims` gets the forward integrity gate, not the reverse completeness gate."""
    claims = _load_json(os.path.join(_HERE, "claims_declared.json")) or {}
    claim_ids = {c["id"] for c in claims.get("claims", [])}
    big = _load_json(os.path.join(_HERE, "landing-big-ideas.json")) or {}
    # The argument ideas are the `_order` six; the file also carries non-argument slots (the catalogue
    # gateway), which are not reconciliation targets.
    idea_slugs = set(big.get("_order", [])) or {k for k in big if not k.startswith("_")}
    # The What-This-Book-Argues claim slugs are the `_order` six on the WTBA registry (the same set the
    # part-opener-traceability lint resolves against).
    argues = _load_json(os.path.join(_HERE, "argues_claims_declared.json")) or {}
    argues_slugs = set(argues.get("_order", [])) or {k for k in argues if not k.startswith("_")}
    return claim_ids, idea_slugs, argues_slugs


# ---- invariants (AS1–AS7; walked by the drift check in tests/book_models.py) -------------------------

def structural_findings(model: "SpineModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA invariants. Deterministic; the focus flags are NOT findings (they are the
    artifact's `flags` block — editorial signal, not schema violation).

    AS2 — spine ids unique + kebab; `order` is exactly 1..N contiguous; N within [SPINE_MIN, SPINE_MAX];
          every `seeds` number within the author's 1..10 seed set; statement within WORD_CAP.
    AS3 — every `reconciles` link resolves: claim ids against claims_declared.json, big-idea slugs against
          landing-big-ideas.json, and What-This-Book-Argues claim slugs against argues_claims_declared.json.
    AS4 — the reconciliation is COMPLETE: every sibling claim id and every big-idea slug is reconciled by
          ≥1 spine claim (a sibling stance with no place in the argument is a finding). Deliberately NOT
          applied to argues_claims — a WTBA claim with no premise pointing at it is legitimate, so that
          namespace gets AS3's forward integrity gate but not AS4's reverse completeness gate.
    AS5 — `chapter_advances` keys are exactly the outline's chapter slugs (exhaustive labeling; a label
          keyed to a chapter the book no longer defines reddens too).
    AS6 — every advanced id names a spine claim; no duplicate ids within one chapter's label.
    AS7 — every chapter exemption reason ∈ EXEMPT_REASONS; every exemption key is a labeled chapter.
    AS8 — freshness (the CS5 analogue): every claim carries a `reviewed_hash` equal to its current statement
          hash — a statement edited without a re-review reddens (its chapter labels may no longer hold).
    AS9 — claim exemptions: every reason ∈ CLAIM_EXEMPT_REASONS; every exemption key names a spine claim.
    AS10 — every `feeds` target resolves to a later-ordered spine id (a forward causal edge; a backward
          or self feed reddens).

    (AS1, drift — the artifact equals a fresh derivation — is walked by the tests/book_models.py check and
    the `verify` CLI, mirroring the siblings. The DEPTH and OVERMAPPING sensors are DERIVED report flags in
    the artifact's `flags` block — editorial signal, deliberately NOT structural findings here.)"""
    if model is None:
        model = derive_model()
    claim_ids, idea_slugs, argues_slugs = _sibling_sets()
    findings: "list[str]" = []

    # AS2 — id + order + seed + word-cap shape.
    seen: "set[str]" = set()
    for s in model.spine:
        if s.id in seen:
            findings.append(f"AS2 duplicate spine id {s.id!r}")
        seen.add(s.id)
        if not all(part.isalnum() for part in s.id.split("-")) or s.id != s.id.lower():
            findings.append(f"AS2 spine id {s.id!r} is not kebab-case")
        for n in s.seeds:
            if not (SEED_MIN <= n <= SEED_MAX):
                findings.append(f"AS2 spine claim {s.id!r} cites seed {n} outside the author's 1..10 set")
        if s.word_count > WORD_CAP:
            findings.append(f"AS2 spine claim {s.id!r} statement is {s.word_count} words (> {WORD_CAP}-word cap)")
    n = len(model.spine)
    if not (SPINE_MIN <= n <= SPINE_MAX):
        findings.append(f"AS2 spine has {n} claims — outside the directive's {SPINE_MIN}–{SPINE_MAX} band")
    if [s.order for s in model.spine] != list(range(1, n + 1)):
        findings.append("AS2 spine `order` values are not exactly 1..N contiguous")

    # AS3 — reconciliation links resolve.
    for s in model.spine:
        for cid in s.reconciles_claims:
            if cid not in claim_ids:
                findings.append(f"AS3 spine claim {s.id!r} reconciles unknown claim id {cid!r}")
        for slug in s.reconciles_big_ideas:
            if slug not in idea_slugs:
                findings.append(f"AS3 spine claim {s.id!r} reconciles unknown big-idea slug {slug!r}")
        for slug in s.reconciles_argues_claims:
            if slug not in argues_slugs:
                findings.append(f"AS3 spine claim {s.id!r} reconciles unknown argues-claim slug {slug!r}")

    # AS4 — reconciliation complete in the reverse direction.
    covered_claims = {cid for s in model.spine for cid in s.reconciles_claims}
    covered_ideas = {slug for s in model.spine for slug in s.reconciles_big_ideas}
    for cid in sorted(claim_ids - covered_claims):
        findings.append(f"AS4 claims-model id {cid!r} is reconciled by no spine claim")
    for slug in sorted(idea_slugs - covered_ideas):
        findings.append(f"AS4 big-idea {slug!r} is reconciled by no spine claim")

    # AS5 — exhaustive chapter labeling, keys == outline chapter LABELS (number-free identity model).
    import chapter_identity_model as chapter_identity  # noqa: E402 — sibling book-model
    decl = _load_declared()
    labeled = set(decl.get("chapter_advances", {}))
    outline_labels = {chapter_identity.label_for_slug(c.slug) or c.slug
                      for c in om.derive_outline().chapters}
    for label in sorted(outline_labels - labeled):
        findings.append(f"AS5 chapter {label!r} carries no argument label (chapter_advances is exhaustive)")
    for label in sorted(labeled - outline_labels):
        findings.append(f"AS5 chapter_advances keys {label!r} — the outline defines no such chapter")

    # AS6 — advanced ids resolve; no duplicates per chapter.
    spine_ids = {s.id for s in model.spine}
    for ch in model.chapters:
        if len(ch.advances) != len(set(ch.advances)):
            findings.append(f"AS6 chapter {ch.slug!r} lists a duplicate spine id")
        for sid in ch.advances:
            if sid not in spine_ids:
                findings.append(f"AS6 chapter {ch.slug!r} advances unknown spine id {sid!r}")

    # AS7 — chapter exemption enum + keys.
    for slug, reason in decl.get("chapter_exemptions", {}).items():
        if reason not in EXEMPT_REASONS:
            findings.append(f"AS7 chapter {slug!r} exemption {reason!r} not in the closed enum "
                            f"({', '.join(EXEMPT_REASONS)})")
        if slug not in labeled:
            findings.append(f"AS7 exemption for {slug!r} — chapter carries no label row")

    # AS8 — freshness: each claim's chapter labels were reviewed against the current statement wording.
    for s in model.spine:
        if not s.reviewed_hash:
            findings.append(f"AS8 spine claim {s.id!r} has no reviewed_hash — seed it to the current "
                            f"statement hash ({s.statement_hash}) once its labels are reviewed")
        elif s.reviewed_hash != s.statement_hash:
            findings.append(f"AS8 spine claim {s.id!r} statement changed since review — re-review its "
                            f"{len(s.advanced_by)} advancing chapter(s), then update reviewed_hash "
                            f"(declared {s.reviewed_hash!r} vs current {s.statement_hash!r})")

    # AS9 — claim exemption enum + keys (the claim-side analogue of AS7).
    for cid, reason in decl.get("claim_exemptions", {}).items():
        if reason not in CLAIM_EXEMPT_REASONS:
            findings.append(f"AS9 claim {cid!r} exemption {reason!r} not in the closed enum "
                            f"({', '.join(CLAIM_EXEMPT_REASONS)})")
        if cid not in spine_ids:
            findings.append(f"AS9 claim exemption for {cid!r} — no such spine claim")

    # AS10 — every `feeds` target resolves to a later-ordered spine id (a causal edge points FORWARD;
    # a backward or self feed inverts the modeling->alignment progression and reddens).
    order_of = {s.id: s.order for s in model.spine}
    for s in model.spine:
        for tgt in s.feeds:
            if tgt not in order_of:
                findings.append(f"AS10 spine claim {s.id!r} feeds unknown spine id {tgt!r}")
            elif order_of[tgt] <= s.order:
                findings.append(f"AS10 spine claim {s.id!r} feeds {tgt!r} which is not later-ordered "
                                f"(feed must point forward: {s.order} -> {order_of[tgt]})")
    return findings


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "SpineModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    flags = model.flags()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "spine_claims": len(model.spine),
            "chapters_labeled": sum(1 for c in model.chapters if c.advances),
            "chapters_exempt": sum(1 for c in model.chapters if c.exempt),
            "advancement_edges": sum(len(c.advances) for c in model.chapters),
            "feeds_edges": sum(len(s.feeds) for s in model.spine),
            "reconciled_claims": len({cid for s in model.spine for cid in s.reconciles_claims}),
            "reconciled_big_ideas": len({b for s in model.spine for b in s.reconciles_big_ideas}),
            "zero_claim_suspects": len(flags["zero_claim_suspects"]),
            "over_cap_unfocused": len(flags["over_cap_unfocused"]),
            "thin_claim_gaps": len(flags["thin_claim_gaps"]),
            "thin_claims_front_loaded": len(flags["thin_claims_front_loaded"]),
            "overmapped_claims": len(flags["overmapped_claims"]),
            "claims_exempt": sum(1 for s in model.spine if s.exempt),
            "claims_stale": sum(1 for s in model.spine if not s.fresh),
            "quantifiable_claims": sum(1 for s in model.spine if s.quantifiable),
            "reality_claims": sum(1 for s in model.spine if s.reality_claim),
            "max_statement_words": max((s.word_count for s in model.spine), default=0),
        },
        "taxonomy": {"word_cap": WORD_CAP, "focus_cap": FOCUS_CAP, "overmap_cap": OVERMAP_CAP,
                     "spine_bounds": [SPINE_MIN, SPINE_MAX], "front_parts": list(FRONT_PARTS),
                     "exempt_reasons": list(EXEMPT_REASONS),
                     "claim_exempt_reasons": list(CLAIM_EXEMPT_REASONS)},
        "spine": [asdict(s) for s in model.spine],
        "chapters": [asdict(c) for c in model.chapters],
        "flags": flags,
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['spine_claims']} spine claims; "
          f"{c['chapters_labeled']} chapters labeled ({c['advancement_edges']} edges, "
          f"{c['chapters_exempt']} exempt); chapter flags: {c['zero_claim_suspects']} zero-claim, "
          f"{c['over_cap_unfocused']} over-cap; claim flags: {c['thin_claim_gaps']} gap, "
          f"{c['thin_claims_front_loaded']} front-loaded, {c['overmapped_claims']} overmapped "
          f"({c['claims_exempt']} exempt, {c['claims_stale']} stale)")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} structural finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """AS1-drift as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    keys = ("spine", "chapters", "flags", "_counts")
    if any(stored.get(k) != fresh[k] for k in keys):
        print("DRIFT: argument-spine.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"argument-spine.json is in sync ({fresh['_counts']['spine_claims']} spine claims, "
          f"{fresh['_counts']['advancement_edges']} advancement edges)")
    return 0


# ---- CLI --------------------------------------------------------------------------------------------

def _health_tag(s: "SpineClaim") -> str:
    """A one-glyph health suffix for the spine listing: depth + freshness signal at a glance."""
    tags = []
    if s.exempt:
        tags.append(f"exempt:{s.exempt}")
    elif not s.advanced_by:
        tags.append("GAP")
    elif s.front_loaded:
        tags.append("front-loaded")
    if s.overmapped:
        tags.append(f"OVERMAPPED:{len(s.advanced_by)}")
    if not s.fresh:
        tags.append("STALE")
    return f"  [{'; '.join(tags)}]" if tags else ""


def _print_spine() -> int:
    model = derive_model()
    print("== the argument spine ==")
    for s in model.spine:
        seeds = f" [seeds {','.join(map(str, s.seeds))}]" if s.seeds else ""
        print(f"{s.order:>3}. {s.id}{seeds}{_health_tag(s)}\n     {s.statement}")
        if s.advanced_by:
            print(f"     advanced by ({len(s.advanced_by)}, body-depth {s.body_depth}): "
                  f"{', '.join(s.advanced_by)}")
    return 0


def _print_flags() -> int:
    flags = derive_model().flags()
    print("== focus flags (derived; the Phase-1c refactor worklist) ==")
    for f in flags["zero_claim_suspects"]:
        print(f"  ZERO-CLAIM suspect: {f['chapter']}")
    for f in flags["over_cap_unfocused"]:
        print(f"  OVER-CAP ({f['advances']} > {FOCUS_CAP}): {f['chapter']} — {', '.join(f['spine_ids'])}")
    if not flags["zero_claim_suspects"] and not flags["over_cap_unfocused"]:
        print("  none — every non-exempt chapter advances 1..3 spine claims")
    print("== claim-health flags (derived; the depth + overmapping sensors) ==")
    for f in flags["thin_claim_gaps"]:
        print(f"  GAP (advanced by 0 chapters): {f['claim']}")
    for f in flags["thin_claims_front_loaded"]:
        print(f"  FRONT-LOADED ({f['advanced_by']} chapters, body-depth {f['body_depth']}): "
              f"{f['claim']} — {', '.join(f['chapters'])}")
    for f in flags["overmapped_claims"]:
        print(f"  OVERMAPPED ({f['advanced_by']} > {OVERMAP_CAP}): {f['claim']} — audit chapter by chapter")
    if not (flags["thin_claim_gaps"] or flags["thin_claims_front_loaded"] or flags["overmapped_claims"]):
        print("  none — every non-exempt claim reaches the body and no claim over-maps")
    return 0


def _print_hashes() -> int:
    """Print each claim's CURRENT statement hash — the value a reviewed_hash is seeded/re-seeded to."""
    for s in derive_model().spine:
        marker = "" if s.fresh else "  (STALE — reviewed against " + (s.reviewed_hash or "<none>") + ")"
        print(f"{s.statement_hash}  {s.id}{marker}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "spine":
        return _print_spine()
    if cmd == "flags":
        return _print_flags()
    if cmd == "hashes":
        return _print_hashes()
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
