"""The CAPABILITY-LADDER view — a typed model of the book's ONE canonical 8-rung Representation Capability
Ladder: the teaching abstraction projected into the opening figure, the new Part 2 (Modeling) explanatory
ladder, the Part 4 brownfield adoption path, the Appendix-A stack min-representation, the Appendix-E
skill-graduation, and the Part 6 comparative mapping. A sibling of the other declared -> generated book models
(argument_spine / industry_cases): the hand-authored source of truth is `book-models/capability_ladder_declared.json`;
capability-ladder.json is generated (`python3 book-models/capability_ladder_model.py regenerate`).

WHY A NEW MODEL, NOT AN EXTENSION.  The ladder recurs THREE times with three jobs — explanatory (teach),
adoption (guide), comparative (measure) — and also indexes Appendix-A stacks and the Appendix-E skill rung.
"Do not invent three separate ladders — use one canonical representation-capability ladder throughout." A
ladder duplicated across the opening figure, the Part-4 climb, the Appendix-A table, and the Part-6 mapping
WILL drift; a declared model makes the drift a finding (the single-source-of-truth trigger). The argument
spine already holds the linear argument; the ladder holds the ORTHOGONAL representational-capability axis the
spine's modeling->alignment turn rides along, so it earns its own file.

GENRE CHECK — ADOPT THE SCHEMA, REJECT THE RUNTIME.  The genre is a maturity/capability model. We adopt the
rung-list schema and REJECT the maturity runtime: no levels, scores, badges, or monotonic-ascent claim. The
declared `guard` field carries the closed anti-CMM value `capability-not-maturity`, checked by CL3, so a
projection can never render the ladder as CMM. A CAPABILITY ladder orders representational capabilities, not
organizations; higher rungs make additional engineering questions possible, they do not imply every system
should climb every rung.

THE 12->8 JOIN.  The 8 teaching rungs relate to the 12-rung Part-6 `modeling_ceiling_ladder` (in
industry_cases_declared.json) through `modeling_ceiling_map`, a TOTAL join: every one of the 12 fine empirical
rungs maps to exactly one of the 8 teaching rungs, and every map value resolves to a rung (CL2). This is the
join that keeps the teaching ladder and the empirical matrix from ever diverging — the ladder TEACHES, the
matrix MEASURES, and the map is the bridge cited in both places.

Run `python3 book-models/capability_ladder_model.py regenerate` to write the artifact; `... verify` to
drift-check (CL0/AS1 analogue); `... ladder` to print the rungs + gradient; `... map` to print the 12->8 join;
`... table` to print the projected ladder table markdown.
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass, field

_HERE = os.path.dirname(os.path.abspath(__file__))
_ARTIFACT = os.path.join(_HERE, "capability-ladder.json")
_DECLARED = os.path.join(_HERE, "capability_ladder_declared.json")
#: The 12-rung empirical ladder the `modeling_ceiling_map` must totally cover (CL2) — the Part-6 instrument
#: the teaching ladder abstracts. Read at check time from the industry-cases declared source (single source of
#: truth, no snapshot), so a rung added there reddens an incomplete map here.
_INDUSTRY_DECLARED = os.path.join(_HERE, "industry_cases_declared.json")

_PROVENANCE = ("GENERATED by book-models/capability_ladder_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/capability_ladder_model.py regenerate`. Derived from the hand-authored "
               "8-rung ladder + the 12->8 modeling_ceiling_map in "
               "book-models/capability_ladder_declared.json, resolved against the 12-rung "
               "modeling_ceiling_ladder in industry_cases_declared.json.")

_MODEL_NOTE = (
    "The capability-ladder model holds the book's ONE canonical 8-rung Representation Capability Ladder — the "
    "teaching abstraction projected into the opening figure, the new Part 2 explanatory ladder, the Part 4 "
    "adoption path, the Appendix-A stacks, the Appendix-E skill rung, and the Part 6 comparative. A CAPABILITY "
    "ladder, not a maturity model: it orders representational capabilities, not organizations; the `guard` "
    "field carries the closed anti-CMM value so no projection can render levels/scores/badges. The two-axis "
    "gradient (bottom = better context for the reasoner; top = stronger control over the artifact) is the "
    "standing reading, the `lean` field naming each rung's side and the turn falling between rungs 4 and 5. "
    "The `modeling_ceiling_map` is the TOTAL 12->8 join to the Part-6 empirical matrix: the ladder TEACHES, the "
    "matrix MEASURES, the map is the bridge that keeps them from diverging.")

#: The ladder's fixed size — 8 canonical rungs (CL1). A ninth rung is a rare, deliberate event, not append.
LADDER_SIZE = 8

#: The closed anti-CMM guard value (CL3). Present verbatim or the ladder could be rendered as a maturity model.
GUARD_VALUE = "capability-not-maturity"

#: The closed set of rung leans — which side of the modeling->alignment turn a rung sits on (the two-axis
#: gradient rendered as data). Rungs 1-4 help the reasoner (modeling-leaning); rungs 5-8 govern the artifact
#: (alignment-leaning); the turn falls between 4 and 5.
LEAN_VALUES = ("modeling", "alignment")


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Rung:
    """One rung of the capability ladder. `id` is the kebab join key (the SSOT key the figures, the Part-6
    matrix map, and the industry-case ladder-rung join all resolve against); `order` its 1-based position;
    `label` the canonical human label (authoritative for prose AND figures); `capability` the one-line 'what
    this rung lets you do that the rung below cannot'; `capability_question` the fuller question the rung
    answers; `lean` its side of the two-axis gradient (modeling / alignment)."""
    id: str
    order: int
    label: str
    capability: str
    capability_question: str
    lean: str


@dataclass
class CapabilityLadderModel:
    guard: str
    gradient: dict
    rungs: "list[Rung]"
    modeling_ceiling_map: "dict[str, str]"

    def rung_ids(self) -> "list[str]":
        return [r.id for r in self.rungs]


# ---- load + build -----------------------------------------------------------------------------------

def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def derive_model(raw: "dict | None" = None) -> CapabilityLadderModel:
    """Build the ladder model from the hand-authored declarations — the single derivation the projection and
    the checks share. Rungs are sorted by `order` so the artifact is deterministic."""
    if raw is None:
        raw = _load_declared()
    rungs = [
        Rung(id=r.get("id", ""), order=r.get("order", 0), label=r.get("label", ""),
             capability=r.get("capability", ""), capability_question=r.get("capability_question", ""),
             lean=r.get("lean", ""))
        for r in raw.get("rungs", [])
    ]
    rungs.sort(key=lambda r: r.order)
    return CapabilityLadderModel(
        guard=raw.get("guard", ""), gradient=dict(raw.get("gradient", {}) or {}), rungs=rungs,
        modeling_ceiling_map=dict(raw.get("modeling_ceiling_map", {}) or {}),
    )


def _modeling_ceiling_rung_ids() -> "list[str]":
    """The 12 empirical rung ids the `modeling_ceiling_map` must totally cover — read live from the
    industry-cases declared source (single source of truth). Returns [] if that file is absent (the CL2
    completeness check then has nothing to hold, mirroring the siblings' status-aware joins)."""
    if not os.path.isfile(_INDUSTRY_DECLARED):
        return []
    with open(_INDUSTRY_DECLARED, encoding="utf-8") as fh:
        raw = json.load(fh)
    return [r.get("id", "") for r in raw.get("modeling_ceiling_ladder", {}).get("rungs", [])]


# ---- invariants (CL1-CL3; walked by the drift check in tests/book_models.py) ------------------------

def structural_findings(model: "CapabilityLadderModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA invariants. Deterministic. AUDIT-ONLY-first (rule #55) on first landing, then
    promoted to BLOCKING once a clean session confirms the drain — the path every book model took.

    CL1 — rung ids unique + kebab; `order` is exactly 1..N contiguous with N == LADDER_SIZE; every `label`,
          `capability`, and `capability_question` non-empty; every `lean` in the closed LEAN_VALUES set.
    CL2 — the `modeling_ceiling_map` is a TOTAL join over the 12-rung empirical ladder: it covers EVERY
          modeling_ceiling_ladder rung id (no fine rung left unmapped) AND every map VALUE resolves to one of
          the 8 teaching rung ids (the abstraction is total and closed — the teaching ladder and the empirical
          matrix cannot diverge).
    CL3 — `guard == GUARD_VALUE` (the closed anti-CMM guard is present, so no projection renders the ladder as
          a maturity model).

    (CL0, drift — the artifact equals a fresh derivation — is walked by the tests/book_models.py check and the
    `verify` CLI, mirroring the siblings.)"""
    if model is None:
        model = derive_model()
    findings: "list[str]" = []

    # CL1 — rung id + order + non-empty text + lean enum.
    seen: "set[str]" = set()
    for r in model.rungs:
        if r.id in seen:
            findings.append(f"CL1 duplicate rung id {r.id!r}")
        seen.add(r.id)
        if not all(part.isalnum() for part in r.id.split("-")) or r.id != r.id.lower():
            findings.append(f"CL1 rung id {r.id!r} is not kebab-case")
        for f_name, val in (("label", r.label), ("capability", r.capability),
                            ("capability_question", r.capability_question)):
            if not str(val).strip():
                findings.append(f"CL1 rung {r.id!r} has empty {f_name}")
        if r.lean not in LEAN_VALUES:
            findings.append(f"CL1 rung {r.id!r} lean {r.lean!r} not in {LEAN_VALUES}")
    n = len(model.rungs)
    if n != LADDER_SIZE:
        findings.append(f"CL1 ladder has {n} rungs — expected exactly {LADDER_SIZE}")
    if [r.order for r in model.rungs] != list(range(1, n + 1)):
        findings.append("CL1 rung `order` values are not exactly 1..N contiguous")

    # CL2 — the 12->8 map is total + closed.
    rung_ids = set(model.rung_ids())
    empirical = _modeling_ceiling_rung_ids()
    mapped = set(model.modeling_ceiling_map)
    for missing in sorted(set(empirical) - mapped):
        findings.append(f"CL2 modeling_ceiling_map does not cover empirical rung {missing!r} "
                        f"(the 12->8 join must be total)")
    for extra in sorted(mapped - set(empirical)):
        findings.append(f"CL2 modeling_ceiling_map keys {extra!r} — no such empirical modeling_ceiling_ladder rung")
    for fine, teach in model.modeling_ceiling_map.items():
        if teach not in rung_ids:
            findings.append(f"CL2 modeling_ceiling_map[{fine!r}] -> {teach!r} resolves to no teaching rung id")

    # CL3 — the anti-CMM guard is present + closed.
    if model.guard != GUARD_VALUE:
        findings.append(f"CL3 guard {model.guard!r} is not the closed anti-CMM value {GUARD_VALUE!r}")
    return findings


# ---- projection: the ladder table -------------------------------------------------------------------

def render_ladder_md(model: "CapabilityLadderModel | None" = None) -> str:
    """The projected ladder table — top rung (8) first, so the printed order matches the figure's
    bottom-to-top climb read downward. Columns: #, Rung, Capability, Lean. The prose wave places exactly
    these lines when it authors the ladder into a chapter; a page-parity check can then hold them byte-equal."""
    if model is None:
        model = derive_model()
    header = "| # | Rung | Capability | Lean |"
    rule = "|---|---|---|---|"
    rows = [f"| {r.order} | **{r.label}** | {r.capability} | {r.lean} |"
            for r in sorted(model.rungs, key=lambda r: -r.order)]
    return "\n".join([header, rule, *rows])


def render_map_md(model: "CapabilityLadderModel | None" = None) -> str:
    """The 12->8 join table — each empirical rung id and the teaching rung it abstracts into. The Appendix-A
    'conceptual ladder meets implementation architecture' table projects from this."""
    if model is None:
        model = derive_model()
    header = "| 12-rung empirical rung | → 8-rung teaching rung |"
    rule = "|---|---|"
    rows = [f"| `{fine}` | `{teach}` |" for fine, teach in model.modeling_ceiling_map.items()]
    return "\n".join([header, rule, *rows])


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "CapabilityLadderModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "rungs": len(model.rungs),
            "modeling_leaning": sum(1 for r in model.rungs if r.lean == "modeling"),
            "alignment_leaning": sum(1 for r in model.rungs if r.lean == "alignment"),
            "map_entries": len(model.modeling_ceiling_map),
        },
        "guard": model.guard,
        "gradient": model.gradient,
        "rungs": [asdict(r) for r in model.rungs],
        "modeling_ceiling_map": dict(model.modeling_ceiling_map),
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['rungs']} rungs "
          f"({c['modeling_leaning']} modeling-leaning, {c['alignment_leaning']} alignment-leaning); "
          f"{c['map_entries']} modeling_ceiling_map entries")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} structural finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """CL0-drift as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    keys = ("guard", "gradient", "rungs", "modeling_ceiling_map", "_counts")
    if any(stored.get(k) != fresh[k] for k in keys):
        print("DRIFT: capability-ladder.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"capability-ladder.json is in sync ({fresh['_counts']['rungs']} rungs, "
          f"{fresh['_counts']['map_entries']} map entries)")
    return 0


# ---- CLI --------------------------------------------------------------------------------------------

def _print_ladder() -> int:
    model = derive_model()
    g = model.gradient
    print("== the capability ladder (8 rungs; a CAPABILITY ladder, NOT a maturity model) ==")
    print(f"   gradient: bottom = {g.get('bottom', '?')!r} · top = {g.get('top', '?')!r} · "
          f"turn between rungs {g.get('turn_between', '?')}")
    for r in sorted(model.rungs, key=lambda r: -r.order):
        print(f"{r.order:>2}. {r.label}  [{r.lean}]\n     {r.capability}")
    return 0


def _print_map() -> int:
    print("== the 12->8 join (modeling_ceiling_map — the teaching ladder abstracts the empirical matrix) ==")
    print(render_map_md())
    findings = [f for f in structural_findings() if f.startswith("CL2")]
    print("  CL2: total+closed" if not findings else "\n".join("  " + f for f in findings))
    return 0


def _print_table() -> int:
    print(render_ladder_md())
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "ladder":
        return _print_ladder()
    if cmd == "map":
        return _print_map()
    if cmd == "table":
        return _print_table()
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
