"""The CHAPTER-IDENTITY view — the ONE surrogate-key dimension table the whole book joins against.

Every other book-model used to key its chapter references on a FILENAME slug (`6.1-toward-a-theory-of-mage`)
or a bare NUMBER (`6.1`). Both rot on a reorg: renumber a chapter and every stored `6.1-…` dangles; retitle
one and every stored title drifts. This model kills that failure class. Each chapter earns a frozen,
number-free `label` (`toward-a-theory-of-mage`) assigned once at creation; the label is the join key every
downstream model references. `number` derives from the filename's `N.M-` prefix; `title` derives from the
chapter file's `<!-- chapter-title: -->` metadata comment. Neither is stored — a reorg edits ONE field
(`filename`) here, and every downstream ref stays valid untouched.

TWO FIELDS ONLY (`label` + `filename`). The author's shape: `title` is NOT stored (the reviewer's objection
stands — three chapters carry no H1 and several H1s carry subtitles ≠ the display title, so the H1 is not a
safe title source; the `<!-- chapter-title: -->` comment is). `number` is NOT stored (it lives in the
filename prefix). A template-conformance sensor (`check`) keeps the derivation always-safe: every chapter
file carries exactly one `<!-- chapter-title: -->`, exactly one H1 (counted outside code fences), and a
filename prefix agreeing with its outline position.

ASYMMETRIC BIJECTION. The model holds the DISCOVERED chapter files under `frontmatter/` + `part1..6/` +
`conclusion/` (excluding `00-part-intro.md`), a SUPERSET of the outline chapters: a couple of front-matter
apparatus pages (`0.1-the-mage-method-at-a-glance`, `0.2-what-this-book-argues`) are real chapter files
referenced by label but not in the outline's chapter tree. The SYNTHETIC apparatus — the appendices and the
terminal back matter (Colophon, About-the-Author, assembled by `build_backmatter_chapters`) — carries NO
identity row, exactly like the appendix pages: identity covers discovered chapters only. So `verify` asserts
every OUTLINE chapter has an identity row and every identity `filename` exists on disk — but NOT the converse
(the front-matter extras are legitimate).

Run `python3 book-models/chapter_identity_model.py regenerate` to write the derived artifact; `... verify`
to run the bijection drift-check; `... check` to run the template-conformance sensor + dangling-label
backstop; `... list` to print the identity table.
"""
from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import asdict, dataclass

import outline_model as om  # noqa: E402 — sibling book-model; path is set by the importing test/hook

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)  # the catalogue root — chapter files live under book/<filename>
_BOOK = os.path.join(_ROOT, "book")
_ARTIFACT = os.path.join(_HERE, "chapter_identity.json")
_DECLARED = os.path.join(_HERE, "chapter_identity_declared.json")

_PROVENANCE = ("GENERATED by book-models/chapter_identity_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/chapter_identity_model.py regenerate`. Derived from the hand-authored "
               "chapter_identity_declared.json (label + filename), resolved against the chapter files on disk.")

_MODEL_NOTE = (
    "The chapter-identity model is the book's surrogate-key dimension table — one frozen number-free `label` "
    "per chapter file, plus the mutable `filename`. `number` derives from the filename's N.M- prefix; `title` "
    "derives from the file's <!-- chapter-title: --> comment. Every other book-model joins on `label`, never "
    "a filename or number, so a reorg edits one field here and all downstream refs stay valid. The bijection "
    "check (verify) holds label uniqueness, filename-on-disk, asymmetric outline coverage, and number/title "
    "derivability; the conformance sensor (check) holds each chapter's template shape + a dangling-label "
    "backstop over the migrated downstream models.")

#: The `N.M-` filename-prefix shape every chapter basename must carry (so `number()` never raises).
_PREFIX_RE = re.compile(r"^(\d+\.\d+)-")
#: The chapter-title metadata comment — the single title-derivation source (conformance leg 1 guarantees one).
_CT_RE = re.compile(r"<!--\s*chapter-title:\s*(.*?)\s*-->")
#: An H1 line — a single leading `#` then whitespace then non-space. Counted OUTSIDE fenced code (leg 2).
_H1_RE = re.compile(r"^#\s+\S")


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Row:
    """One chapter's identity: the frozen `label` (join key) + the mutable `filename` (relative to book/)."""
    label: str
    filename: str


@dataclass
class IdentityModel:
    rows: list[Row]


# ---- load + build -----------------------------------------------------------------------------------

def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def derive_model() -> IdentityModel:
    """Build the model from the hand-authored declarations, in authored order (which is outline reading
    order) — the single derivation the regen and the drift check share."""
    decl = _load_declared()
    rows = [Row(label=c["label"], filename=c["filename"]) for c in decl.get("chapters", [])]
    return IdentityModel(rows=rows)


# ---- resolver API (the display seam every renderer + sibling model imports) --------------------------

_BY_LABEL: "dict[str, Row] | None" = None
_BY_FILE_STEM: "dict[str, str] | None" = None  # basename-stem (with N.M- prefix) -> label
_BY_LABEL_STEM: "dict[str, str] | None" = None  # number-free stem (== label) -> label; identity, for symmetry
_TITLE_CACHE: "dict[str, str]" = {}


def _index() -> "dict[str, Row]":
    global _BY_LABEL, _BY_FILE_STEM
    if _BY_LABEL is None:
        model = derive_model()
        _BY_LABEL = {r.label: r for r in model.rows}
        _BY_FILE_STEM = {os.path.basename(r.filename)[:-3]: r.label for r in model.rows}
    return _BY_LABEL


def resolve(label: str) -> Row:
    """The full identity row for a label; raises KeyError on an unknown label."""
    idx = _index()
    if label not in idx:
        raise KeyError(f"unknown chapter label {label!r} — not in chapter_identity_declared.json")
    return idx[label]


def filename(label: str) -> str:
    """The chapter file, relative to book/ (e.g. 'part6/6.1-toward-a-theory-of-mage.md')."""
    return resolve(label).filename


def number(label: str) -> str:
    """DERIVED: the `N.M` number prefix of the filename basename (e.g. '6.1'). Pure-string; no file read."""
    base = os.path.basename(filename(label))
    m = _PREFIX_RE.match(base)
    if not m:
        raise ValueError(f"chapter {label!r} filename {base!r} lacks an N.M- prefix")
    return m.group(1)


def html_href(label: str) -> str:
    """DERIVED: the built-HTML href for the chapter — 'book/<basename-stem>.html'. Pure-string; no file read.
    Matches the flat build layout (every chapter renders to book/<N.M-slug>.html)."""
    base = os.path.basename(filename(label))
    return "book/" + base[:-3] + ".html"


def title(label: str) -> str:
    """DERIVED: the display title from the file's <!-- chapter-title: --> comment. Reads the file; cached
    per process. The conformance sensor guarantees exactly one match, so a missing/duplicate comment raises
    here (fail-loud) — that is the sensor's job to prevent, not this resolver's to paper over."""
    if label in _TITLE_CACHE:
        return _TITLE_CACHE[label]
    path = os.path.join(_BOOK, filename(label))
    text = open(path, encoding="utf-8").read()
    matches = _CT_RE.findall(text)
    if len(matches) != 1:
        raise ValueError(f"chapter {label!r} ({path}) has {len(matches)} <!-- chapter-title: --> comments, "
                         f"expected exactly one (conformance sensor should have caught this)")
    _TITLE_CACHE[label] = matches[0]
    return matches[0]


def label_for_file(fname: str) -> str:
    """Reverse: the label for a filename (relative or basename). For migration + the bijection check."""
    _index()
    stem = os.path.basename(fname)
    if stem.endswith(".md"):
        stem = stem[:-3]
    assert _BY_FILE_STEM is not None
    if stem not in _BY_FILE_STEM:
        raise KeyError(f"no chapter identity row for file {fname!r}")
    return _BY_FILE_STEM[stem]


def label_for_slug(slug: str) -> "str | None":
    """Reverse from a bare page-slug stem ('6.1-toward-a-theory-of-mage' OR the number-free label itself) to
    the label. Returns None when the slug names no chapter (so a caller can distinguish chapter vs non-chapter
    page-slugs, e.g. an appendix slug). Accepts both the numbered stem and the already-migrated bare label."""
    _index()
    assert _BY_FILE_STEM is not None
    if slug in _BY_FILE_STEM:            # numbered stem '6.1-...'
        return _BY_FILE_STEM[slug]
    if slug in _index():                 # already a bare label
        return slug
    return None


def labels() -> "set[str]":
    """The authoritative label set — the dangling-label backstop's resolve target."""
    return set(_index().keys())


# ---- bijection / validator (verify) -----------------------------------------------------------------

def structural_findings(model: "IdentityModel | None" = None) -> "list[str]":
    """The bijection invariants (§1c). Deterministic. All clean at HEAD.

    1. UNIQUE labels — no two rows share a label (primary key).
    2. filename <-> disk — every row's filename resolves to a real file under book/.
    3. OUTLINE coverage (asymmetric) — every outline chapter slug has exactly one row whose filename
       basename stem == slug. Does NOT require the converse (the 3 non-outline rows are permitted).
    4. NUMBER derivable — every filename basename matches ^N.M- (so number() never raises).
    5. TITLE derivable — every file carries exactly one <!-- chapter-title: --> (so title() never raises).
    """
    if model is None:
        model = derive_model()
    findings: "list[str]" = []

    # 1 — unique labels.
    seen: "set[str]" = set()
    for r in model.rows:
        if r.label in seen:
            findings.append(f"CI1 duplicate label {r.label!r}")
        seen.add(r.label)

    # 2 — filename resolves on disk.
    for r in model.rows:
        if not os.path.isfile(os.path.join(_BOOK, r.filename)):
            findings.append(f"CI2 row {r.label!r} filename {r.filename!r} resolves to no file under book/")

    # 3 — asymmetric outline coverage: every outline chapter has exactly one row.
    file_stems = {os.path.basename(r.filename)[:-3]: r.label for r in model.rows}
    outline = om.derive_outline()
    for c in outline.chapters:
        if c.slug not in file_stems:
            findings.append(f"CI3 outline chapter {c.slug!r} has no chapter-identity row")

    # 4 — number derivable.
    for r in model.rows:
        if not _PREFIX_RE.match(os.path.basename(r.filename)):
            findings.append(f"CI4 row {r.label!r} filename {r.filename!r} lacks an N.M- number prefix")

    # 5 — title derivable (exactly one chapter-title comment).
    for r in model.rows:
        path = os.path.join(_BOOK, r.filename)
        if not os.path.isfile(path):
            continue  # already reported by CI2
        n = len(_CT_RE.findall(open(path, encoding="utf-8").read()))
        if n != 1:
            findings.append(f"CI5 row {r.label!r} has {n} <!-- chapter-title: --> comment(s), expected 1")

    return findings


# ---- conformance sensor + dangling-label backstop (check) -------------------------------------------

#: Chapter files EXEMPT from the H1 leg of the conformance sensor. `acknowledgments` (0.6) is a bare
#: front-matter apparatus page — a single paragraph of thanks with no body sections. Its only heading IS
#: its title; promoting that to an H1 gives it zero sections, at which point the outline model stops
#: counting it as a chapter (a real structural regression, 37→36 outline chapters). It is heading-free by
#: design, so the H1-arity leg is waived here; the chapter-title leg (title-derivation safety) still applies
#: to all 40 files, and 0.6 carries its <!-- chapter-title: --> so title() stays safe. (Surfaced to the
#: author as a frontmatter-H1 judgment call — package §3 "SCOPE DECISION".)
_H1_EXEMPT_LABELS = frozenset({"acknowledgments"})


def _conformance_findings(md_rel: str) -> "list[str]":
    """Template-conformance for one chapter file: exactly one chapter-title comment + (unless the chapter is
    an H1-exempt apparatus page) exactly one H1, counted OUTSIDE fenced code blocks — a `# ` inside a ```
    fence is a code comment, not a heading."""
    path = os.path.join(_BOOK, md_rel)
    text = open(path, encoding="utf-8").read()
    out: "list[str]" = []

    n_ct = len(_CT_RE.findall(text))
    if n_ct != 1:
        out.append(f"{md_rel}: expected exactly one <!-- chapter-title: --> comment, found {n_ct}")

    label = os.path.basename(md_rel)[:-3]
    label = re.sub(r"^\d+\.\d+-", "", label)
    if label in _H1_EXEMPT_LABELS:
        return out  # heading-free apparatus page — the H1-arity leg is waived (see _H1_EXEMPT_LABELS)

    in_fence = False
    n_h1 = 0
    for line in text.split("\n"):
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if not in_fence and _H1_RE.match(line):
            n_h1 += 1
    if n_h1 != 1:
        out.append(f"{md_rel}: expected exactly one H1 (outside code fences), found {n_h1}")
    return out


def conformance_findings() -> "list[str]":
    """Leg 1+2 of the sensor over ALL 40 chapter files (Option A scope — the identity model's full set).
    Leg 3 (filename prefix agrees with outline reading order) is folded into `_prefix_order_findings`."""
    model = derive_model()
    out: "list[str]" = []
    for r in model.rows:
        out.extend(_conformance_findings(r.filename))
    return out


def _prefix_order_findings() -> "list[str]":
    """Sensor leg 3: each outline chapter's identity filename prefix agrees with its outline position — the
    outline slug already carries the `N.M-` prefix, so the identity filename basename must equal the slug.
    (The 3 non-outline rows have no outline position; they are checked only for prefix shape by CI4.)"""
    file_stems = {os.path.basename(r.filename)[:-3]: r.label for r in derive_model().rows}
    out: "list[str]" = []
    for c in om.derive_outline().chapters:
        if c.slug not in file_stems:
            out.append(f"prefix-order: outline chapter {c.slug!r} has no identity filename with that stem")
    return out


def _namespace_findings() -> "list[str]":
    """NON-FATAL namespace note (design §2.1/§6). After migration a chapter label and an outline section-id
    share one slug namespace (the number prefix that kept them distinct is gone). A collision is not a
    resolution regression — a value resolving as EITHER a label or a section-id matches today's permissive
    `slug ∪ section` behavior — but it is worth surfacing because the dangling-label backstop resolving
    specifically against `labels()` is the precision net a colliding permissive check cannot give. Reported,
    never gated: chapter 1.1 legitimately holds both a `# The Printer` title and a `## The printer` section,
    so this set is not empty on the current tree and cannot be driven to ∅ without an editorial rename."""
    section_ids = {s.section_id for _c, s in om.derive_outline().sections()}
    clash = sorted(labels() & section_ids)
    if clash:
        return [f"namespace-note: {len(clash)} chapter label(s) also name an outline section-id "
                f"(permissive resolution, no regression; the label-scoped backstop is the precision net): "
                f"{', '.join(clash)}"]
    return []


#: The downstream models whose chapter references were migrated to `label` (design §5). The dangling-label
#: backstop resolves each of these files' chapter-`label` refs against `labels()`. Read lazily so a
#: half-migrated tree (some files still on numbered slugs) does not falsely redden the backstop — a value
#: that is not a bare label is simply skipped (it is still gated by its own model's resolver).
_BACKSTOP_LABEL_FIELDS: "tuple[tuple[str, str], ...]" = (
    ("book-models/claims_declared.json", "home+asserted_at"),
    ("book-models/argument_spine_declared.json", "keys"),
    ("book-models/chapter_shape_declared.json", "slug"),
    ("book-models/outcomes_declared.json", "primary_unit+secondary_units"),
    ("book-models/lit_positioning_declared.json", "target_locations"),
    ("book-models/metaphor-spans.json", "label+stretch"),
    ("book-models/metrics-dashboard.json", "label"),
    ("book-models/field-notes.json", "chapter_slug"),
    ("book-models/discussion-claims.json", "chapter_slug"),
    ("book/data/data-claims.json", "source"),
)


def check() -> "tuple[str, list[str]]":
    """The template-conformance sensor + prefix-order leg + namespace note (AUDIT-ONLY first, then BLOCKING
    per the promotion staircase). Returns (status, findings). The dangling-label backstop over migrated
    models is walked by the test harness (which knows each model's field shapes); this subcommand owns the
    per-file template legs it can compute standalone."""
    findings: "list[str]" = []
    findings.extend(conformance_findings())
    findings.extend(_prefix_order_findings())
    findings.extend(_namespace_findings())
    status = "FAIL" if any(not f.startswith("namespace-note:") for f in findings) else "PASS"
    return status, findings


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "IdentityModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "chapters": len(model.rows),
            "outline_chapters": len(om.derive_outline().chapters),
        },
        "chapters": [asdict(r) for r in model.rows],
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['chapters']} chapters "
          f"({c['outline_chapters']} outline chapters covered)")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} bijection finding(s):")
        for f in findings:
            print(f"    {f}")
    else:
        print("  CI1–CI5 bijection clean")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """Bijection-drift as a CLI: the on-disk artifact equals a fresh derivation AND CI1–CI5 are clean."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    rc = 0
    if any(stored.get(k) != fresh[k] for k in ("chapters", "_counts")):
        print("DRIFT: chapter_identity.json disagrees with a fresh derivation — regenerate")
        rc = 1
    findings = structural_findings()
    if findings:
        print(f"{len(findings)} bijection finding(s):")
        for f in findings:
            print(f"  {f}")
        rc = 1
    if rc == 0:
        print(f"chapter_identity.json is in sync ({fresh['_counts']['chapters']} chapters); CI1–CI5 clean")
    return rc


# ---- CLI --------------------------------------------------------------------------------------------

def _print_list() -> int:
    model = derive_model()
    print(f"== chapter identity ({len(model.rows)} rows) ==")
    for r in model.rows:
        print(f"  {number(r.label):<4} {r.label:<38} {r.filename}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "check":
        status, findings = check()
        for f in findings:
            print(f"  {f}")
        print(f"conformance sensor: {status} ({len(findings)} finding(s))")
        return 1 if status == "FAIL" else 0
    if cmd == "list":
        return _print_list()
    print(__doc__)
    return 2


if __name__ == "__main__":
    # Allow standalone invocation: put book-models on the path so `import outline_model` resolves.
    if _HERE not in sys.path:
        sys.path.insert(0, _HERE)
    raise SystemExit(main(sys.argv))
