"""The CLAIMS view — a typed model of the load-bearing PROPOSITIONS and key distinctions the book asserts,
each carrying the AUDIT PREDICATE (`contradicted_by`) that names what prose would negate it. A fifth sibling
model beside outline / outcomes / concepts / big-ideas (DESIGN book/_design/book-claims-model-260801.md).

WHY A NEW MODEL, NOT AN EXTENSION.  The other models hold a term (concepts), a definition, a reader
capability (outcomes), or a fixed landing slot (big-ideas). A claim is none of these: it is a stance the
book TAKES and could silently betray, so it needs the one field none of them carry — `contradicted_by`, the
predicate an audit checks prose against. See DESIGN §1. The claims model reuses the sibling join keys rather
than re-modeling: `asserted_at` / `home` are outline unit keys; `relates_to` links into concepts /
definitions / big-ideas / outcomes. New object, reused keys.

THE JUDGMENT-AUDIT BOUNDARY (load-bearing, DESIGN §4.2).  The contradiction check itself is a SEMANTIC
JUDGMENT-AUDIT owned by a review gate, NOT a blocking lint — no deterministic check separates "keep the
model derived from the code" (a contradiction) from "a derived model kills drift" (a correct use of the same
words). Only the STRUCTURAL / SCHEMA checks here (C1–C6 + the C7-drift freshness check) are mechanical, so
only they may ever go blocking. The watch-phrase surfacing lint (`lint_claim_watch_phrases.py`, C7) stays
AUDIT-ONLY FOREVER — a hit is a review candidate, never a verdict.

TWO-WAY PROVENANCE (DESIGN §3.2).  `stated` — the book asserts it explicitly (`anchor` cites the sentence);
`implicit` — a load-bearing stance the book only implies (`anchor` says why it is not stated outright, the
author's worklist). Never masquerade implicit as stated.

NO NEW MARKDOWN SYMBOL (DESIGN §3.3).  Claims live in this model's `claims.json`, keyed by outline units —
the renderer stays uncoupled. An inline `<!-- claim: <id> -->` marker is a deferred upgrade, not wired here.

Run `python3 book-models/claims_model.py regenerate` to write the artifact; `... verify` to drift-check;
`... claims <chapter>` for the pre-edit consult (the claims a chapter asserts + their contradiction predicates).
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import outline_model as om  # noqa: E402 — the outline view is the unit tree claims map onto

_HERE = os.path.dirname(os.path.abspath(__file__))
_ARTIFACT = os.path.join(_HERE, "claims.json")
_DECLARED = os.path.join(_HERE, "claims_declared.json")
_ROOT = os.path.dirname(_HERE)  # the governance-catalog repo root (book-models/ is one level down)

_PROVENANCE = ("GENERATED by book-models/claims_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/claims_model.py regenerate`. Derived from the hand-authored stance set "
               "in book-models/claims_declared.json, resolved against the outline + sibling models.")

# The model's `_note`, written into claims.json. States the §4.2 judgment-audit boundary (Phase-4 record)
# and the §4.3 reflexive payoff — the two aides instantiate the book's own Alignment Thesis on its manuscript.
_MODEL_NOTE = (
    "The claims model holds each load-bearing proposition the book asserts, plus the AUDIT PREDICATE "
    "(`contradicted_by`) naming what prose would negate it. JUDGMENT-AUDIT BOUNDARY (DESIGN §4.2): the "
    "contradiction check is a SEMANTIC judgment-audit owned by a review gate, NOT a blocking lint; only the "
    "structural / schema checks (C1–C6 + the C7-drift freshness check) are mechanical and may ever go "
    "blocking, and the watch-phrase surfacing lint (C7) stays AUDIT-ONLY FOREVER (a hit is a review "
    "candidate, never a verdict). REFLEXIVE PAYOFF (DESIGN §4.3): the two aides — the pre-edit consult "
    "(`catalog.py claims <chapter>`, the CONSTRAINT that aims the editing agent away from the drift) and the "
    "watch-phrase lint plus judgment-audit (the SENSOR that catches it after) — instantiate the book's own "
    "Alignment Thesis on its own manuscript. The model does not merely record the constraint/sensor "
    "distinction; it applies it to the book's prose.")

# ---- the kind taxonomy ------------------------------------------------------------------------------
# A CLOSED set of claim kinds (DESIGN §3). `kind` MUST be in this set (invariant C4). A `distinction`
# additionally names its two poles in `distinguishes` (C4). The set is tuned to the book's stance shapes:
# the dominant "X, not Y" distinction, plus thesis / stance / causal / mapping / scope-boundary / metaphor /
# caveat / practice for the non-two-pole propositions.
KINDS = (
    "distinction",     # an "X, not Y" claim holding two named poles apart (the dominant shape)
    "thesis",          # a master proposition the book argues at book scale
    "stance",          # a position the book takes (a premise / posture)
    "causal",          # an X-causes-or-earns-Y claim
    "mapping",         # a claim assigning members of one set to another (theses → not-knowings)
    "scope-boundary",  # a claim delimiting a set / what is in or out of scope
    "metaphor",        # a claim carried by a figure (printer, not coder)
    "caveat",          # a humility / limitation the book states about its own claims
    "practice",        # a claim about the method — what to DO
)

#: The two honesty tags a claim carries — how the book holds the stance (DESIGN §3.2).
PROVENANCE_TAGS = ("stated", "implicit")

#: The `statement` word cap — a claim is a proposition, not a paraphrase (DESIGN §3.1). Counted
#: deterministically with `statement.split()`, mirroring the point-claim word-cap lint. Higher than the
#: point decorator's 10 because a claim states a full proposition.
WORD_CAP = 18

#: The typed-link prefixes `relates_to` may use — each resolves into a sibling model (join, not re-model).
RELATES_PREFIXES = ("concept", "definition", "thesis", "big-idea", "outcome")


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Claim:
    """One load-bearing proposition the book asserts. `id` is the kebab join key (and the reverse-index
    `claim` symbol). `asserted_at` is EVERY outline site that states the claim (multi-site is the point);
    `home` is the one site where it is chiefly argued. `contradicted_by` is the audit predicate — the short
    statement of what prose would negate the claim (the field no sibling model carries). `distinguishes`
    holds the two poles of a `distinction` (required iff kind == 'distinction'). `watch_phrases` are literal
    candidate phrases the surfacing lint (C7) greps for — high-false-positive by design; a hit is a review
    candidate. `relates_to` links into the sibling models. `provenance` is stated | implicit."""
    id: str
    kind: str
    statement: str
    distinguishes: list[str]       # [pole_a, pole_b] — REQUIRED (exactly 2) iff kind == 'distinction'
    home: str                      # the one outline unit where the claim is chiefly argued
    asserted_at: list[str]         # every outline unit that states it (section-id | chapter | part-N | book | point:<slug>)
    contradicted_by: str           # the AUDIT PREDICATE — what prose would negate the claim
    watch_phrases: list[str]       # literal candidate phrases the C7 surfacing lint greps for (may be empty)
    relates_to: list[str]          # typed links into the sibling models (concept: | definition: | thesis: | big-idea: | outcome:)
    provenance: str                # stated | implicit
    anchor: str                    # for stated: the prose it rests on; for implicit: why the book only implies it
    word_count: int = 0            # derived: statement.split() length (materialized for the C6 view)


@dataclass
class ClaimModel:
    claims: list[Claim]

    def by_site(self) -> "dict[str, list[Claim]]":
        """outline unit → claims asserted at it (the pre-edit consult's join)."""
        d: "dict[str, list[Claim]]" = {}
        for c in self.claims:
            for site in c.asserted_at:
                d.setdefault(site, []).append(c)
        return d


# ---- load + build -----------------------------------------------------------------------------------

def _load_declared() -> "list[dict]":
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)["claims"]


def _mk_claim(d: "dict") -> Claim:
    stmt = d["statement"]
    return Claim(
        id=d["id"], kind=d["kind"], statement=stmt,
        distinguishes=list(d.get("distinguishes", [])), home=d["home"],
        asserted_at=list(d.get("asserted_at", [])), contradicted_by=d.get("contradicted_by", ""),
        watch_phrases=list(d.get("watch_phrases", [])), relates_to=list(d.get("relates_to", [])),
        provenance=d.get("provenance", "stated"), anchor=d.get("anchor", ""),
        word_count=len(stmt.split()))


def derive_model() -> ClaimModel:
    """Build the claim model from the hand-authored declarations, sorted deterministically by id — the single
    derivation the regen and the drift check share."""
    claims = [_mk_claim(d) for d in _load_declared()]
    claims.sort(key=lambda c: c.id)
    return ClaimModel(claims=claims)


# ---- outline-unit + relates_to resolution -----------------------------------------------------------

def _outline_sets() -> "tuple[set[str], set[str], set[int], set[str]]":
    """(section_ids, chapter_slugs, parts, point_slugs) the book currently defines — the resolve targets for
    `home` / `asserted_at` (C1). Points come from the outline's decorator-derived paragraph points.

    Chapter references migrated to number-free identity LABELS (chapter_identity model), so the chapter
    resolve set is the union of the outline slugs (legacy / half-migrated tree) and the identity labels.
    Permissive union — a value resolves as EITHER — which matches the pre-existing slug ∪ section behavior;
    the dangling-label backstop resolving specifically against labels() is the precision net."""
    import chapter_identity_model as chapter_identity  # noqa: E402 — sibling book-model
    outline = om.derive_outline()
    section_ids = {s.section_id for _c, s in outline.sections()}
    chapter_slugs = {c.slug for c in outline.chapters} | chapter_identity.labels()
    parts = {c.part for c in outline.chapters}
    points: "set[str]" = set()
    for c in outline.chapters:
        points.update(p.slug for p in c.preamble_points)
        for s in c.sections:
            points.update(p.slug for p in s.points)
    return section_ids, chapter_slugs, parts, points


def _site_resolves(site: str, section_ids: "set[str]", chapter_slugs: "set[str]", parts: "set[int]",
                   points: "set[str]") -> bool:
    """True when an outline site key names a real unit (book | part-N | chapter slug | section id | point:<slug>)."""
    if site == "book":
        return True
    if site.startswith("part-"):
        n = site.removeprefix("part-")
        return n.isdigit() and int(n) in parts
    if site.startswith("point:"):
        return site.removeprefix("point:") in points
    return site in chapter_slugs or site in section_ids


def _load_json(path: str) -> "dict | None":
    return json.load(open(path, encoding="utf-8")) if os.path.isfile(path) else None


def _relates_target_sets() -> "dict[str, set[str]]":
    """The sibling-model key sets each `relates_to` prefix resolves against (C2). Read at check time from the
    sibling models — a single source of truth, no snapshot:
      concept:    → book/data/concepts.json keys (also the resolve set for a thesis: link, whose theses live
                    there as `thesis-<slug>` concepts).
      definition: → book/data/definitions.json terms.
      big-idea:   → book-models/landing-big-ideas.json idea keys.
      outcome:    → book-models/outcomes.json outcome ids.
    A prefix whose sibling model is absent resolves to the empty set, so any link under it reddens (C2)."""
    concepts = _load_json(os.path.join(_ROOT, "book", "data", "concepts.json")) or {}
    concept_keys = {k for k in concepts if not k.startswith("_")}
    definitions = _load_json(os.path.join(_ROOT, "book", "data", "definitions.json")) or {}
    definition_keys = {k for k in definitions if not k.startswith("_")}
    big_ideas = _load_json(os.path.join(_HERE, "landing-big-ideas.json")) or {}
    idea_keys = _big_idea_keys(big_ideas)
    outcomes = _load_json(_ARTIFACT.replace("claims.json", "outcomes.json")) or {}
    outcome_ids = {o.get("outcome_id") for o in outcomes.get("outcomes", []) if o.get("outcome_id")}
    return {
        "concept": concept_keys,
        # a thesis: link names one of the book's two theses, modeled as `thesis-<slug>` concepts.
        "thesis": {k.removeprefix("thesis-") for k in concept_keys if k.startswith("thesis-")},
        "definition": definition_keys,
        "big-idea": idea_keys,
        "outcome": outcome_ids,
    }


def _big_idea_keys(big_ideas: "dict") -> "set[str]":
    """The book's argument-vocabulary slugs — the decoupled `_argument_big_ideas` registry, NOT the
    top-level record keys (website-v3, 260825, repurposed the file's top level for the six LANDING claims).
    A `big-idea:` relates_to link resolves against this nine-slug book-internal set."""
    return set(big_ideas.get("_argument_big_ideas", []))


# ---- invariants (C1–C6; walked by the drift check in tests/book_models.py) ---------------------------

def structural_findings(model: "ClaimModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA invariants (C1–C6, DESIGN §4.1). Each finding is a drain signal — the seed is
    drained to zero before any blocking promotion. These are deterministic (no prose meaning is read); the
    SEMANTIC contradiction check is a review-gate judgment-audit, not walked here (DESIGN §4.2).

    C1 — every `home` and every `asserted_at` site resolves to a real outline unit.
    C2 — every `relates_to` link resolves against its sibling model's key set (concept / definition / thesis /
         big-idea / outcome), and carries a known prefix.
    C3 — every claim carries a non-empty `contradicted_by` predicate (a claim with none is not auditable).
    C4 — `kind` ∈ the closed taxonomy; a `distinction` names exactly two poles in `distinguishes`, and a
         non-distinction names none.
    C5 — every claim is asserted at ≥1 site, OR is `provenance: implicit` with an `anchor` note.
    C6 — `statement` is within the word cap (WORD_CAP), counted by `statement.split()`.
    """
    if model is None:
        model = derive_model()
    section_ids, chapter_slugs, parts, points = _outline_sets()
    targets = _relates_target_sets()

    findings: "list[str]" = []
    seen_ids: "set[str]" = set()
    for c in model.claims:
        if c.id in seen_ids:
            findings.append(f"C0 duplicate claim id {c.id!r}")
        seen_ids.add(c.id)

        # C1 — home + asserted_at resolve.
        if not _site_resolves(c.home, section_ids, chapter_slugs, parts, points):
            findings.append(f"C1 claim {c.id!r} home {c.home!r} resolves to no outline unit")
        for site in c.asserted_at:
            if not _site_resolves(site, section_ids, chapter_slugs, parts, points):
                findings.append(f"C1 claim {c.id!r} asserted_at site {site!r} resolves to no outline unit")

        # C2 — relates_to links resolve.
        for link in c.relates_to:
            if ":" not in link:
                findings.append(f"C2 claim {c.id!r} relates_to {link!r} has no `<prefix>:<slug>` shape")
                continue
            prefix, slug = link.split(":", 1)
            if prefix not in RELATES_PREFIXES:
                findings.append(f"C2 claim {c.id!r} relates_to {link!r} uses unknown prefix {prefix!r} "
                                f"(known: {', '.join(RELATES_PREFIXES)})")
            elif slug not in targets.get(prefix, set()):
                findings.append(f"C2 claim {c.id!r} relates_to {link!r} does not resolve in the {prefix} model")

        # C3 — non-empty contradiction predicate.
        if not c.contradicted_by.strip():
            findings.append(f"C3 claim {c.id!r} carries no contradicted_by predicate — not auditable")

        # C4 — kind enum + distinction pole shape.
        if c.kind not in KINDS:
            findings.append(f"C4 claim {c.id!r} kind {c.kind!r} not in the closed taxonomy")
        if c.kind == "distinction":
            if len(c.distinguishes) != 2:
                findings.append(f"C4 distinction {c.id!r} must name exactly 2 poles in distinguishes "
                                f"(has {len(c.distinguishes)})")
        elif c.distinguishes:
            findings.append(f"C4 non-distinction {c.id!r} (kind {c.kind!r}) names poles in distinguishes "
                            f"(only a distinction may)")

        # C5 — asserted at ≥1 site, or implicit-with-anchor.
        if not c.asserted_at:
            if c.provenance != "implicit":
                findings.append(f"C5 claim {c.id!r} is asserted at no site and is not flagged implicit")
            elif not c.anchor.strip():
                findings.append(f"C5 implicit claim {c.id!r} is asserted at no site and cites no anchor")

        # C6 — word cap.
        if c.word_count > WORD_CAP:
            findings.append(f"C6 claim {c.id!r} statement is {c.word_count} words (> {WORD_CAP}-word cap)")

        # provenance sanity (tag validity + stated cites an anchor).
        if c.provenance not in PROVENANCE_TAGS:
            findings.append(f"claim {c.id!r} has invalid provenance {c.provenance!r}")
        elif c.provenance == "stated" and not c.anchor.strip():
            findings.append(f"claim {c.id!r} is stated but cites no anchor")

    return findings


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "ClaimModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "claims": len(model.claims),
            "by_kind": {k: sum(1 for c in model.claims if c.kind == k) for k in KINDS},
            "by_provenance": {p: sum(1 for c in model.claims if c.provenance == p) for p in PROVENANCE_TAGS},
            "distinctions": sum(1 for c in model.claims if c.kind == "distinction"),
            "with_watch_phrases": sum(1 for c in model.claims if c.watch_phrases),
            "assertion_sites": sum(len(c.asserted_at) for c in model.claims),
            "relates_to_links": sum(len(c.relates_to) for c in model.claims),
            "max_statement_words": max((c.word_count for c in model.claims), default=0),
        },
        "taxonomy": {"kinds": list(KINDS), "provenance": list(PROVENANCE_TAGS), "word_cap": WORD_CAP},
        "claims": [asdict(c) for c in model.claims],
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['claims']} claims "
          f"(by kind {c['by_kind']}); {c['distinctions']} distinctions, "
          f"{c['with_watch_phrases']} with watch-phrases; {c['assertion_sites']} assertion sites; "
          f"max statement {c['max_statement_words']}/{payload['taxonomy']['word_cap']} words")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} structural finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """C7-drift as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    if stored.get("claims") != fresh["claims"] or stored.get("_counts") != fresh["_counts"]:
        print("DRIFT: claims.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"claims.json is in sync ({fresh['_counts']['claims']} claims)")
    return 0


# ---- the pre-edit consult (DESIGN §4.2) -------------------------------------------------------------

def claims_for_chapter(chapter: str) -> "list[Claim]":
    """Every claim asserted in `chapter` — by chapter slug directly, OR by a section id / point that belongs
    to that chapter. The join the pre-edit consult prints so an editing agent can confirm its edit does not
    negate a listed stance."""
    outline = om.derive_outline()
    # Resolve the chapter to its slug (accept either the full slug or a bare number prefix like '3.1').
    slug = None
    for c in outline.chapters:
        if c.slug == chapter or c.slug.split("-", 1)[0] == chapter:
            slug = c.slug
            break
    if slug is None:
        return []
    chap = next(c for c in outline.chapters if c.slug == slug)
    own_sites = {slug} | {s.section_id for s in chap.sections}
    own_sites |= {f"point:{p.slug}" for s in chap.sections for p in s.points}
    own_sites |= {f"point:{p.slug}" for p in chap.preamble_points}
    part_key = f"part-{chap.part}"
    model = derive_model()
    hits: "list[Claim]" = []
    for cl in model.claims:
        sites = set(cl.asserted_at) | {cl.home}
        if sites & own_sites or part_key in sites:
            hits.append(cl)
    return hits


def consult(chapter: str) -> int:
    """Print the claims a chapter asserts and their contradiction predicates — the pre-edit consult. Before
    editing a chapter's prose, run this and confirm the edit does not negate a listed stance."""
    hits = claims_for_chapter(chapter)
    if not hits:
        print(f"no claims asserted in {chapter!r} (unknown chapter, or none seeded here yet)")
        return 0
    print(f"== claims asserted in {chapter} — confirm your edit negates none of these ==")
    for cl in hits:
        poles = f"  [{cl.distinguishes[0]} | vs | {cl.distinguishes[1]}]" if cl.distinguishes else ""
        print(f"\n• {cl.id} ({cl.kind}){poles}")
        print(f"    claim:         {cl.statement}")
        print(f"    contradicted-by: {cl.contradicted_by}")
        if cl.watch_phrases:
            print(f"    watch-phrases:  {', '.join(repr(w) for w in cl.watch_phrases)}")
    print(f"\n— {len(hits)} claim(s)")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "regenerate"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "claims":
        if len(argv) < 3:
            print(f"usage: {argv[0]} claims <chapter>")
            return 2
        return consult(argv[2])
    print(f"usage: {argv[0]} [regenerate|verify|claims <chapter>]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
