"""The FACTORY-VOCABULARY view — a typed model of the internal editing vocabulary behind Chapter 5's
factory language. This model names the distinctions the prose draws so an editing pass can apply them
consistently and a lint can hold the mechanizable part.

AN EDITING MODEL, NOT A PASSAGE.  The structure below is deliberately NOT printed in the book. It governs
how the prose chooses words; the reader meets the words, never the table. A sibling of the other declared ->
generated book models (capability_ladder / argument_spine): the hand-authored source of truth is
`book-models/factory_vocabulary_declared.json`; factory-vocabulary.json is generated
(`python3 book-models/factory_vocabulary_model.py regenerate`).

THE VOCABULARY WAS REDUCED.  An earlier version of this model carried a COLLECTIVE noun (`engineering
apparatus`), five KINDs participating in it (machinery, tooling, representation, control, infrastructure),
and a PROPERTY (`engineering capital`) holding of the collective. The author ruled that one to two terms too
many: apparatus did almost the same work as `factory` with fuzzier boundaries; `machinery` versus `tooling`
had become ontology for ontology's sake; and capital asked the reader to reinterpret the factory
economically just as the chapter was trying to make it concrete. What survives is a FOUR-TERM CORE, each
term answering a DIFFERENT question, inside the whole:

    WHOLE        factory                the engineered system for producing software change
      +- PART    code-fabricator        Who does the work?
      +- PART    model                  What describes what should be built?
      +- PART    tool                   What does the fabricator work with?
      +- ROLE    control                What bounds its freedom?
    ENVIRONMENT  engineering-environment  what the arrangement creates for the work

One formulation teaches it, and the lint checks the sentence is present:

    Fabricators build the product from models, using tools, subject to controls.

CONTROL IS A ROLE, NOT A BIN — the subtle part, and the part a careless reading loses.  A test is ordinarily
a TOOL: an agent can run it and reason about the result. It participates in a CONTROL when the result
carries a consequence the agent cannot simply reason away — a failing test that blocks admission, a
permission boundary on action, a merge gate on admission. So `control` is modelled as a `role` REALIZED BY
the parts (`realized_by`), never as a fourth part beside them, and it carries the `discriminator` verbatim as
data. FV4 holds all of that: the closed `partition` guard `control-is-a-role-not-a-bin`, at least two
`realized_by` edges, and a non-empty discriminator.

GENRE CHECK — adopt the schema, reject the runtime.  The genre is a controlled vocabulary / thesaurus, and
its canonical best-in-class is SKOS. We ADOPT its insistence that a relation is not a concept — the reason
`control` is a role rather than a part. We REJECT the faceted-classification runtime, where facets partition:
hence the anti-bin guard. No RDF, no URIs, no inference engine; the schema earns its keep, the runtime does
not.

RETIRED TERMS INVERT THE LINT'S POLARITY.  `retired_terms` carries the two words that LEFT Chapter 5, each
with the scope it is banned in, the reason, and what to say instead. The old deterministic check steered
prose TOWARD `engineering apparatus`; the new one finds it. `engineering capital` is banned only inside
Chapter 5 — it remains live and defined elsewhere in the book, a known and accepted asymmetry.

Run `python3 book-models/factory_vocabulary_model.py regenerate` to write the artifact; `... verify` to
drift-check; `... tree` to print the WHOLE/PART/ROLE/ENVIRONMENT structure; `... tests` to print the
per-term questions, role tests, and negative rules; `... foreshadow` to print the manufacturing -> software
foreshadowing map; `... retired` to print the retired terms and their replacement guidance.
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass, field

_HERE = os.path.dirname(os.path.abspath(__file__))
_ARTIFACT = os.path.join(_HERE, "factory-vocabulary.json")
_DECLARED = os.path.join(_HERE, "factory_vocabulary_declared.json")
#: The chapter the vocabulary governs. FV8 joins `author_named_sections[].file` against it, and FV9 joins
#: `formulation_scope`, so a renamed chapter file reddens rather than silently emptying the report.
_PART5 = os.path.join(os.path.dirname(_HERE), "book", "part5")

_PROVENANCE = ("GENERATED by book-models/factory_vocabulary_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/factory_vocabulary_model.py regenerate`. Derived from the "
               "hand-authored vocabulary in book-models/factory_vocabulary_declared.json.")

_MODEL_NOTE = (
    "The factory-vocabulary model holds the INTERNAL EDITING vocabulary behind Chapter 5's factory "
    "language — never printed in the book. A FOUR-TERM CORE, each term answering a different question, "
    "inside a WHOLE: the factory holds three PARTs (the fabricator — who does the work; the model — what "
    "describes what should be built; the tool — what the fabricator works with) plus a ROLE (control — what "
    "bounds its freedom), and an ENVIRONMENT names what their arrangement creates. One formulation teaches "
    "it: `Fabricators build the product from models, using tools, subject to controls.` CONTROL IS A ROLE, "
    "NOT A BIN: a test is a tool an agent runs and reasons about, and it participates in a control when the "
    "result carries a consequence the agent cannot simply reason away — declared as `discriminator` and "
    "guarded by the closed `partition` value. `retired_terms` carries the two words that LEFT the chapter "
    "(`engineering apparatus`, `engineering capital`), scoped bans included; that plus the narrow-licence "
    "words is the deterministic part a lint can hold (lint_factory_vocabulary.py). The role tests are the "
    "part a human applies.")

#: The closed set of node kinds. FOUR values, and the absence of `collective` / `kind` / `property` is
#: itself the guard: the retired "apparatus is a fourth category, capital is a fifth" error cannot be
#: re-declared, because there is no node kind to declare it as. A fifth value is a model change.
NODE_KINDS = ("whole", "part", "role", "environment")

#: Node kinds the REDUCTION removed. Declared so the regression is named rather than merely absent — FV2
#: refuses any node carrying one, with the reason attached.
RETIRED_NODE_KINDS = ("collective", "kind", "property")

#: The closed anti-bin guard (FV4). Present verbatim, or a consumer could render the four terms as
#: mutually exclusive bins — which mis-states `control`. The analogue of the capability ladder's
#: `capability-not-maturity` guard, re-aimed at the reduced vocabulary.
PARTITION_GUARD = "control-is-a-role-not-a-bin"

#: The closed set of misuse-collocation confidence tiers.
#:   `named`           — the author named this phrase as a misuse; a lint finding.
#:   `author-defended` — the author explicitly DEFENDS this phrase; reported for context, NEVER a finding.
CONFIDENCE_TIERS = ("named", "author-defended")

#: The closed set of usage-licence dispositions for retained-but-constrained words.
DISPOSITIONS = ("retain", "retain-narrow")


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Node:
    """One node of the vocabulary. `id` is the kebab join key (the slug the term registry and the lint both
    resolve against); `node_kind` its place in the WHOLE / PART / ROLE / ENVIRONMENT structure; `question`
    the question the term answers (the core's organizing device — four terms, four DIFFERENT questions, so
    two nodes sharing a question means one of them is redundant); `role_test` the question that decides
    whether the word applies at a site; `negative_rule` the load-bearing half — what the word must NOT be
    stretched to cover.

    The structural edges are deliberately DIFFERENT fields per node kind, so the distinction cannot blur:
    `parent` (a part or the role hangs from the whole) and `realized_by` (the parts a ROLE is realized
    through — the anti-bin edges). `discriminator` is the role's own field: the test that says when a part
    stops being merely itself and participates in the role."""
    id: str
    node_kind: str
    label: str
    question: str
    role_test: str
    negative_rule: str
    exemplars: "list[str]" = field(default_factory=list)
    parent: str = ""
    realized_by: "list[str]" = field(default_factory=list)
    discriminator: str = ""
    aliases: "list[str]" = field(default_factory=list)


@dataclass
class RetiredTerm:
    """A term that LEFT the governed scope. `phrase` is the compound the ban is named for; `banned_words`
    adds bare words the compound hides behind (`apparatus` for `engineering apparatus`) and is EMPTY where
    the bare word stays legitimate (`capital` remains ordinary economic prose); `exempt_collocations` are
    the surviving licensed uses a hit may fall inside. `banned_in` scopes the ban to globs under `book/` —
    the field that keeps this a Chapter-5 decision rather than a book-wide sweep."""
    id: str
    phrase: str
    retired_because: str
    say_instead: str
    banned_in: "list[str]" = field(default_factory=list)
    banned_words: "list[str]" = field(default_factory=list)
    exempt_collocations: "list[str]" = field(default_factory=list)


@dataclass
class UsageLicence:
    """A word RETAINED under a stated constraint rather than assigned a node — `support apparatus` (the
    support/production measurement) and `stock` (an economic noun, only where accumulation is the measured
    phenomenon). `accumulation_words` gives the lint the licence's deterministic window test."""
    id: str
    phrase: str
    disposition: str
    licence: str
    negative_rule: str
    accumulation_words: "list[str]" = field(default_factory=list)


@dataclass
class Foreshadow:
    """One manufacturing -> software foreshadowing pair. The mechanism by which the software-factory
    section sets up the case sections: choose the manufacturing example that PREFIGURES the software one,
    so the conceptual transfer is already prepared when the software term arrives. `kind` joins the pair
    onto the node table; the `_probes` lists are the deterministic presence test."""
    manufacturing: str
    software: str
    kind: str
    manufacturing_probes: "list[str]" = field(default_factory=list)
    software_probes: "list[str]" = field(default_factory=list)


@dataclass
class Misuse:
    """One named misuse collocation — a literal phrase, the node the model says applies instead, and the
    confidence tier. `author-defended` rows are context, never findings."""
    phrase: str
    reassign_to: str
    confidence: str
    note: str


@dataclass
class AuthorNamedSection:
    """One section the author's site-by-site vocabulary pass covers. Named STRUCTURALLY so a reflow cannot
    shift it: `heading` is a `##`/`###` heading's text, or `*opening*` for everything before the file's
    first `##`, or empty for the whole file. The lint derives the span at check time and reports the gap
    between the named sections and the findings it can actually produce."""
    id: str
    file: str
    heading: str = ""


@dataclass
class FactoryVocabularyModel:
    partition: str
    formulation: str
    formulation_scope: "list[str]"
    nodes: "list[Node]"
    retired_terms: "list[RetiredTerm]"
    usage_licences: "list[UsageLicence]"
    foreshadowing: "list[Foreshadow]"
    foreshadowing_scope: "dict[str, list[str]]"
    misuse_collocations: "list[Misuse]"
    author_named_sections: "list[AuthorNamedSection]" = field(default_factory=list)

    def node(self, node_id: str) -> "Node | None":
        return next((n for n in self.nodes if n.id == node_id), None)

    def node_ids(self) -> "list[str]":
        return [n.id for n in self.nodes]

    def of_kind(self, node_kind: str) -> "list[Node]":
        return [n for n in self.nodes if n.node_kind == node_kind]

    def part_ids(self) -> "list[str]":
        return [n.id for n in self.of_kind("part")]

    def the_role(self) -> "Node | None":
        roles = self.of_kind("role")
        return roles[0] if len(roles) == 1 else None

    def core_ids(self) -> "list[str]":
        """The FOUR-TERM CORE — the three parts plus the role. The set the foreshadowing map joins onto."""
        return self.part_ids() + [n.id for n in self.of_kind("role")]

    def findings_collocations(self) -> "list[Misuse]":
        """The misuse rows a lint may raise as FINDINGS — `author-defended` rows excluded by construction,
        so a pre-rejected finding cannot reach the report. Empty today: the named rows steered prose toward
        a term that no longer exists. The mechanism survives so a future named row is still validated."""
        return [m for m in self.misuse_collocations if m.confidence == "named"]

    def defended_collocations(self) -> "list[Misuse]":
        return [m for m in self.misuse_collocations if m.confidence == "author-defended"]


# ---- load + build -----------------------------------------------------------------------------------

def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def derive_model(raw: "dict | None" = None) -> FactoryVocabularyModel:
    """Build the vocabulary model from the hand-authored declarations — the one derivation the projections,
    the invariant walk, and the lint all share."""
    if raw is None:
        raw = _load_declared()
    nodes = [
        Node(id=n.get("id", ""), node_kind=n.get("node_kind", ""), label=n.get("label", ""),
             question=n.get("question", ""), role_test=n.get("role_test", ""),
             negative_rule=n.get("negative_rule", ""), exemplars=list(n.get("exemplars", []) or []),
             parent=n.get("parent", ""), realized_by=list(n.get("realized_by", []) or []),
             discriminator=n.get("discriminator", ""), aliases=list(n.get("aliases", []) or []))
        for n in raw.get("nodes", [])
    ]
    retired = [
        RetiredTerm(id=r.get("id", ""), phrase=r.get("phrase", ""),
                    retired_because=r.get("retired_because", ""), say_instead=r.get("say_instead", ""),
                    banned_in=list(r.get("banned_in", []) or []),
                    banned_words=list(r.get("banned_words", []) or []),
                    exempt_collocations=list(r.get("exempt_collocations", []) or []))
        for r in raw.get("retired_terms", [])
    ]
    licences = [
        UsageLicence(id=u.get("id", ""), phrase=u.get("phrase", ""), disposition=u.get("disposition", ""),
                     licence=u.get("licence", ""), negative_rule=u.get("negative_rule", ""),
                     accumulation_words=list(u.get("accumulation_words", []) or []))
        for u in raw.get("usage_licences", [])
    ]
    fore = [
        Foreshadow(manufacturing=f.get("manufacturing", ""), software=f.get("software", ""),
                   kind=f.get("kind", ""),
                   manufacturing_probes=list(f.get("manufacturing_probes", []) or []),
                   software_probes=list(f.get("software_probes", []) or []))
        for f in raw.get("foreshadowing", [])
    ]
    misuses = [
        Misuse(phrase=m.get("phrase", ""), reassign_to=m.get("reassign_to", ""),
               confidence=m.get("confidence", ""), note=m.get("note", ""))
        for m in raw.get("misuse_collocations", [])
    ]
    scope = {k: list(v or []) for k, v in (raw.get("foreshadowing_scope", {}) or {}).items()}
    named = [
        AuthorNamedSection(id=s.get("id", ""), file=s.get("file", ""), heading=s.get("heading") or "")
        for s in raw.get("author_named_sections", [])
    ]
    return FactoryVocabularyModel(
        partition=raw.get("partition", ""), formulation=raw.get("formulation", ""),
        formulation_scope=list(raw.get("formulation_scope", []) or []),
        nodes=nodes, retired_terms=retired, usage_licences=licences, foreshadowing=fore,
        foreshadowing_scope=scope, misuse_collocations=misuses, author_named_sections=named,
    )


# ---- invariants (FV1-FV9) ---------------------------------------------------------------------------

def structural_findings(model: "FactoryVocabularyModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA invariants over the vocabulary. Deterministic — every one is a set or
    enum check over declared data, never a judgment about prose.

    FV1 — node ids unique + kebab; `node_kind` in the closed NODE_KINDS; `label`, `question`, `role_test`,
          and `negative_rule` non-empty on every node (a node without a negative rule is the failure this
          model exists to prevent — the role test alone lets a word creep).
    FV2 — CARDINALITY encodes the REDUCTION: exactly one `whole`, one `role`, one `environment`, and three
          `part`s (fabricator, model, tool). A node declaring a RETIRED_NODE_KIND re-opens the "apparatus is
          a fourth category / capital is a fifth" error and is refused by name.
    FV3 — the four-term core answers four DIFFERENT questions: every node's `question` is distinct. Two
          terms sharing a question means one of them is redundant, which is exactly the defect the
          reduction removed.
    FV4 — ANTI-BIN: `partition` == PARTITION_GUARD; the `role` carries a non-empty `discriminator` and at
          least two `realized_by` edges, each resolving to a `part` (control is realized THROUGH the parts,
          not placed beside them); every `parent` / `realized_by` id resolves to a node.
    FV5 — every `part` and the `role` `parent` the `whole`; only the `role` declares `realized_by` or a
          `discriminator` (a part that carries them is being smuggled into the role's job).
    FV6 — the foreshadowing map: `manufacturing`, `software`, and both probe lists non-empty, and every
          `kind` value resolves to a core id (a part or the role), so a renamed term cannot orphan the
          transfer. The map need not be surjective — the fabricator has no manufacturing vehicle the
          chapter uses, and that is an honest gap, not a finding.
    FV7 — misuse rows: `confidence` in CONFIDENCE_TIERS; a `named` row's `reassign_to` resolves to a node
          id; an `author-defended` row carries an EMPTY `reassign_to` and a non-empty note. Usage licences:
          `disposition` in DISPOSITIONS, licence and negative rule non-empty.
    FV8 — the author's named sections resolve against real files, and each row carries a unique id.
    FV9 — the REDUCTION's own invariants. The `formulation` is non-empty and every `formulation_scope` file
          exists (the sentence the chapter teaches must have a file to be taught in). Every retired term
          declares a non-empty `phrase`, `retired_because`, `say_instead`, and at least one `banned_in`
          glob — a ban without a stated replacement is a lint finding no one can act on. Every
          `exempt_collocation` must CONTAIN one of its term's banned words, or the exemption is dead config
          that suppresses nothing. And no retired phrase may collide with a live node label, which would
          mean banning the vocabulary the model is telling prose to use.

    (Drift — the artifact equals a fresh derivation — is the `verify` CLI, mirroring the siblings.)"""
    if model is None:
        model = derive_model()
    out: "list[str]" = []
    ids = set()

    # FV1
    for n in model.nodes:
        if n.id in ids:
            out.append(f"FV1 duplicate node id {n.id!r}")
        ids.add(n.id)
        if not n.id or n.id != n.id.lower() or not all(p.isalnum() for p in n.id.split("-")):
            out.append(f"FV1 node id {n.id!r} is not kebab-case")
        if n.node_kind not in NODE_KINDS:
            out.append(f"FV1 node {n.id!r} node_kind {n.node_kind!r} not in {NODE_KINDS}")
        for fname in ("label", "question", "role_test", "negative_rule"):
            if not str(getattr(n, fname)).strip():
                out.append(f"FV1 node {n.id!r} has empty {fname}")

    # FV2 — the cardinality that encodes the reduction.
    for solo in ("whole", "role", "environment"):
        got = model.of_kind(solo)
        if len(got) != 1:
            out.append(f"FV2 expected exactly one {solo!r} node, found {len(got)} "
                       f"({[n.id for n in got]})")
    if len(model.of_kind("part")) != 3:
        out.append(f"FV2 expected three `part` nodes (the fabricator, the model, the tool), found "
                   f"{len(model.of_kind('part'))} ({model.part_ids()}) — the four-term core is three "
                   f"parts plus the control role")
    for n in model.nodes:
        if n.node_kind in RETIRED_NODE_KINDS:
            out.append(f"FV2 node {n.id!r} declares the RETIRED node_kind {n.node_kind!r} — the "
                       f"vocabulary was reduced precisely to remove the collective noun and the property; "
                       f"re-adding one is a model change, not an append")

    # FV3 — four terms, four different questions.
    seen_q: "dict[str, str]" = {}
    for n in model.nodes:
        key = " ".join(n.question.lower().split())
        if key and key in seen_q:
            out.append(f"FV3 nodes {seen_q[key]!r} and {n.id!r} answer the SAME question "
                       f"{n.question!r} — two terms answering one question means one is redundant")
        seen_q[key] = n.id

    # FV4 — the anti-bin guard + edge resolution.
    if model.partition != PARTITION_GUARD:
        out.append(f"FV4 partition {model.partition!r} is not the closed anti-bin value "
                   f"{PARTITION_GUARD!r} — without it a consumer may render the four terms as disjoint "
                   f"bins, which mis-states `control`")
    role = model.the_role()
    parts = set(model.part_ids())
    if role is None:
        out.append("FV4 no single `role` node — `control` is the role the anti-bin rule is about")
    else:
        if not role.discriminator.strip():
            out.append(f"FV4 role {role.id!r} has an empty `discriminator` — the relational test (the "
                       f"result carries a consequence the agent cannot simply reason away) is the whole "
                       f"content of the role, and losing it collapses the role back into a bin")
        if len(role.realized_by) < 2:
            out.append(f"FV4 role {role.id!r} declares fewer than two `realized_by` edges — the model must "
                       f"state which parts realize it, or it reads as a fourth part")
        for r in role.realized_by:
            if r not in parts:
                out.append(f"FV4 role {role.id!r} realized_by {r!r}, which is not a `part` node")
    for n in model.nodes:
        if n.parent and n.parent not in ids:
            out.append(f"FV4 node {n.id!r} parent {n.parent!r} resolves to no node")

    # FV5 — the parts and the role hang off the whole; only the role carries the role's fields.
    whole = model.of_kind("whole")
    if whole:
        for n in model.of_kind("part") + model.of_kind("role"):
            if n.parent != whole[0].id:
                out.append(f"FV5 node {n.id!r} parent {n.parent!r} — expected the whole {whole[0].id!r}")
    for n in model.nodes:
        if n.node_kind != "role" and (n.realized_by or n.discriminator.strip()):
            out.append(f"FV5 node {n.id!r} is a {n.node_kind!r} but carries `realized_by` / "
                       f"`discriminator` — those are the ROLE's fields")

    # FV6 — the foreshadowing map joins onto the core.
    core = set(model.core_ids())
    for f in model.foreshadowing:
        for fname in ("manufacturing", "software"):
            if not str(getattr(f, fname)).strip():
                out.append(f"FV6 foreshadowing row {f.manufacturing!r}->{f.software!r} has empty {fname}")
        if not f.manufacturing_probes or not f.software_probes:
            out.append(f"FV6 foreshadowing row {f.manufacturing!r}->{f.software!r} is missing a probe list "
                       f"(the deterministic presence test has nothing to run)")
        if f.kind not in core:
            out.append(f"FV6 foreshadowing row {f.manufacturing!r}->{f.software!r} kind {f.kind!r} "
                       f"resolves to no core term (expected one of {sorted(core)})")
    for side in ("manufacturing", "software"):
        if not model.foreshadowing_scope.get(side):
            out.append(f"FV6 foreshadowing_scope is missing the {side!r} file list")

    # FV7 — misuse rows + usage licences.
    for m in model.misuse_collocations:
        if m.confidence not in CONFIDENCE_TIERS:
            out.append(f"FV7 misuse {m.phrase!r} confidence {m.confidence!r} not in {CONFIDENCE_TIERS}")
        if not m.phrase.strip() or not m.note.strip():
            out.append(f"FV7 misuse {m.phrase!r} has an empty phrase or note")
        if m.confidence == "named" and m.reassign_to not in ids:
            out.append(f"FV7 misuse {m.phrase!r} reassign_to {m.reassign_to!r} resolves to no node")
        if m.confidence == "author-defended" and m.reassign_to:
            out.append(f"FV7 misuse {m.phrase!r} is author-defended but carries reassign_to "
                       f"{m.reassign_to!r} — a defended phrase has no replacement")
    for u in model.usage_licences:
        if u.disposition not in DISPOSITIONS:
            out.append(f"FV7 usage licence {u.id!r} disposition {u.disposition!r} not in {DISPOSITIONS}")
        for fname in ("phrase", "licence", "negative_rule"):
            if not str(getattr(u, fname)).strip():
                out.append(f"FV7 usage licence {u.id!r} has empty {fname}")

    # FV8 — the author's named sections resolve against real files.
    seen_ids: "set[str]" = set()
    for s in model.author_named_sections:
        if not s.id.strip():
            out.append("FV8 author_named_sections row has an empty id")
        if s.id in seen_ids:
            out.append(f"FV8 duplicate author_named_sections id {s.id!r}")
        seen_ids.add(s.id)
        if not os.path.isfile(os.path.join(_PART5, s.file)):
            out.append(f"FV8 author_named_sections {s.id!r} names file {s.file!r}, which does not exist "
                       f"in book/part5/")

    # FV9 — the reduction's own invariants: the formulation, and the retired terms.
    if not model.formulation.strip():
        out.append("FV9 `formulation` is empty — the one sentence the chapter teaches is the whole point "
                   "of reducing the vocabulary, and the lint's positive check has nothing to look for")
    if not model.formulation_scope:
        out.append("FV9 `formulation_scope` is empty — the formulation must name the file that teaches it")
    for fname in model.formulation_scope:
        if not os.path.isfile(os.path.join(_PART5, fname)):
            out.append(f"FV9 formulation_scope names file {fname!r}, which does not exist in book/part5/")
    labels = {" ".join(n.label.lower().split()) for n in model.nodes}
    retired_ids: "set[str]" = set()
    for r in model.retired_terms:
        if r.id in retired_ids:
            out.append(f"FV9 duplicate retired_terms id {r.id!r}")
        retired_ids.add(r.id)
        for fname in ("phrase", "retired_because", "say_instead"):
            if not str(getattr(r, fname)).strip():
                out.append(f"FV9 retired term {r.id!r} has empty {fname} — a ban without a stated "
                           f"replacement is a finding nobody can act on")
        if not r.banned_in:
            out.append(f"FV9 retired term {r.id!r} declares no `banned_in` scope — an unscoped ban would "
                       f"sweep chapters the decision does not cover")
        words = [r.phrase.lower()] + [w.lower() for w in r.banned_words]
        for ex in r.exempt_collocations:
            if not any(w in ex.lower() for w in words):
                out.append(f"FV9 retired term {r.id!r} exempts {ex!r}, which contains none of its banned "
                           f"words {words} — the exemption suppresses nothing")
        if " ".join(r.phrase.lower().split()) in labels:
            out.append(f"FV9 retired term {r.id!r} phrase {r.phrase!r} is also a live node label — the "
                       f"model would be banning the vocabulary it tells prose to use")
    return out


# ---- projections ------------------------------------------------------------------------------------

def render_tree(model: "FactoryVocabularyModel | None" = None) -> str:
    """The WHOLE / PART / ROLE / ENVIRONMENT structure as an indented tree, each term with the question it
    answers — the shape an editor should hold in mind. Printed by the CLI, never by the book."""
    if model is None:
        model = derive_model()
    lines: "list[str]" = []
    for w in model.of_kind("whole"):
        lines.append(f"WHOLE        {w.id}  — {w.label}")
    for p in model.of_kind("part"):
        lines.append(f"  PART       {p.id}  — {p.question}")
    role = model.the_role()
    if role is not None:
        lines.append(f"  ROLE       {role.id}  — {role.question}   "
                     f"(realized by: {', '.join(role.realized_by)}; a ROLE, not a fourth part)")
        lines.append(f"               discriminator: {role.discriminator}")
    for e in model.of_kind("environment"):
        lines.append(f"ENVIRONMENT  {e.id}  — {e.label}")
    lines.append(f"guard        partition = {model.partition}")
    lines.append(f"formulation  {model.formulation}")
    if model.retired_terms:
        lines.append(f"retired      {', '.join(r.phrase for r in model.retired_terms)}  "
                     f"(banned in {', '.join(sorted({g for r in model.retired_terms for g in r.banned_in}))})")
    return "\n".join(lines)


def render_foreshadow_md(model: "FactoryVocabularyModel | None" = None) -> str:
    """The foreshadowing map as a table — the manufacturing example chosen to PREFIGURE each software
    term, and the core term the pair instantiates."""
    if model is None:
        model = derive_model()
    rows = [f"| {f.manufacturing} | {f.software} | `{f.kind}` |" for f in model.foreshadowing]
    return "\n".join(["| manufacturing example | → software counterpart | term |", "|---|---|---|", *rows])


def render_retired_md(model: "FactoryVocabularyModel | None" = None) -> str:
    """The retired terms as a table — the word, why it left, and what to say instead. The inverted half of
    the vocabulary decision: the lint now FINDS these rather than steering prose toward them."""
    if model is None:
        model = derive_model()
    rows = [f"| `{r.phrase}` | {', '.join(r.banned_in)} | {r.retired_because} | {r.say_instead} |"
            for r in model.retired_terms]
    return "\n".join(["| retired term | banned in | why it left | say instead |", "|---|---|---|---|", *rows])


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "FactoryVocabularyModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "nodes": len(model.nodes),
            "by_node_kind": {nk: len(model.of_kind(nk)) for nk in NODE_KINDS},
            "core_terms": len(model.core_ids()),
            "retired_terms": len(model.retired_terms),
            "usage_licences": len(model.usage_licences),
            "foreshadowing_pairs": len(model.foreshadowing),
            "misuse_named": len(model.findings_collocations()),
            "misuse_author_defended": len(model.defended_collocations()),
            "author_named_sections": len(model.author_named_sections),
        },
        "partition": model.partition,
        "formulation": model.formulation,
        "formulation_scope": list(model.formulation_scope),
        "nodes": [asdict(n) for n in model.nodes],
        "retired_terms": [asdict(r) for r in model.retired_terms],
        "usage_licences": [asdict(u) for u in model.usage_licences],
        "foreshadowing": [asdict(f) for f in model.foreshadowing],
        "foreshadowing_scope": {k: list(v) for k, v in model.foreshadowing_scope.items()},
        "misuse_collocations": [asdict(m) for m in model.misuse_collocations],
        "author_named_sections": [asdict(s) for s in model.author_named_sections],
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['nodes']} nodes "
          f"({c['core_terms']}-term core: {c['by_node_kind']['part']} parts + "
          f"{c['by_node_kind']['role']} role); {c['retired_terms']} retired term(s); "
          f"{c['usage_licences']} usage licence(s); {c['foreshadowing_pairs']} foreshadowing pair(s); "
          f"{c['misuse_named']} named misuse(s) + {c['misuse_author_defended']} author-defended")
    fs = structural_findings()
    if fs:
        print(f"  {len(fs)} structural finding(s):")
        for f in fs:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    with open(_ARTIFACT, encoding="utf-8") as fh:
        return json.load(fh)


def verify() -> int:
    """Drift as a CLI: the on-disk artifact must equal a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    keys = ("partition", "formulation", "formulation_scope", "nodes", "retired_terms", "usage_licences",
            "foreshadowing", "foreshadowing_scope", "misuse_collocations", "author_named_sections",
            "_counts")
    if any(stored.get(k) != fresh[k] for k in keys):
        print("DRIFT: factory-vocabulary.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"factory-vocabulary.json is in sync ({fresh['_counts']['nodes']} nodes, "
          f"{fresh['_counts']['retired_terms']} retired, "
          f"{fresh['_counts']['foreshadowing_pairs']} foreshadowing pairs)")
    return 0


# ---- CLI --------------------------------------------------------------------------------------------

def _print_tests() -> int:
    model = derive_model()
    print("== factory vocabulary — questions, role tests, negative rules (the editing model; never "
          "printed) ==")
    print(f"\nFORMULATION  {model.formulation}")
    for n in model.nodes:
        print(f"\n{n.id}  [{n.node_kind}]  {n.label}")
        print(f"  QUESTION   {n.question}")
        print(f"  ROLE TEST  {n.role_test}")
        print(f"  NEGATIVE   {n.negative_rule}")
        if n.discriminator:
            print(f"  DISCRIM.   {n.discriminator}")
        if n.exemplars:
            print(f"  EXEMPLARS  {'; '.join(n.exemplars)}")
    for r in model.retired_terms:
        print(f"\n{r.id}  [RETIRED in {', '.join(r.banned_in)}]  \"{r.phrase}\"")
        print(f"  WHY        {r.retired_because}")
        print(f"  INSTEAD    {r.say_instead}")
    for u in model.usage_licences:
        print(f"\n{u.id}  [usage-licence: {u.disposition}]  \"{u.phrase}\"")
        print(f"  LICENCE    {u.licence}")
        print(f"  NEGATIVE   {u.negative_rule}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "tree":
        print(render_tree())
        return 0
    if cmd == "tests":
        return _print_tests()
    if cmd == "foreshadow":
        print(render_foreshadow_md())
        return 0
    if cmd == "retired":
        print(render_retired_md())
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
