"""The FACTORY-VOCABULARY view — a typed model of the internal editing vocabulary behind Chapter 5's
factory language. `machinery` had been doing duty for agents, orchestration, tests, models, policies,
permissions, validators, infrastructure and controls at once, and the chapter now draws finer distinctions
than one word supports. This model names the distinctions so an editing pass can apply them consistently
and a lint can hold the mechanizable part.

AN EDITING MODEL, NOT A PASSAGE.  The taxonomy is deliberately NOT printed in the book. It governs how the
prose chooses words; the reader meets the words, never the table. A sibling of the other declared ->
generated book models (capability_ladder / argument_spine): the hand-authored source of truth is
`book-models/factory_vocabulary_declared.json`; factory-vocabulary.json is generated
(`python3 book-models/factory_vocabulary_model.py regenerate`).

THREE KINDS OF NODE — the structural correction is the whole point.  An earlier draft of the vocabulary
listed `engineering apparatus` as though it were a fourth category alongside machinery / tooling /
representation, and `engineering capital` as a fifth. It is neither:

    WHOLE        factory                     the production system
      +- PART        code-fabricator          the thing that realizes the artifact
      +- COLLECTIVE  engineering-apparatus    a COLLECTIVE NOUN, not a sibling of the kinds
           +- KIND   machinery                performs / routes / coordinates / executes
           +- KIND   tooling                  configures / inspects / measures / verifies
           +- KIND   representation           represents knowledge or intent in structured form
           +- KIND   control                  makes a decision consequential for later work
           +- KIND   infrastructure           the computational / operational substrate
    PROPERTY     engineering-capital          holds OF accumulated apparatus (an interpretation)
    ENVIRONMENT  engineering-environment      what the arrangement of apparatus creates

The `node_kind` field carries that distinction as data, and FV2/FV3/FV5 hold it: exactly one collective
(so no sixth "kind" can be smuggled in beside the apparatus), the collective's `collects` list is exactly
the set of kinds (total and closed — every kind participates, and nothing that is not a kind is collected),
and the property `holds_of` the collective rather than sitting beside it.

THE KINDS OVERLAP BY DESIGN — the anti-partition guard.  `control` is not a physical category parallel to
tooling: the same validator is tooling by what it IS and a control by what its verdict DECIDES. Those are
different axes. A consumer that sorts the kinds into mutually exclusive bins has the model wrong, so the
declared `partition` field carries the closed value `kinds-overlap-not-partition` (checked by FV4, the
anti-CMM-guard analogue in capability_ladder_model.py), and `control` declares explicit `overlaps` edges
that FV4 requires to be non-trivial.

GENRE CHECK — adopt the schema, reject the runtime.  The genre is a controlled vocabulary / thesaurus, and
its canonical best-in-class is SKOS. We ADOPT the one distinction SKOS draws that this model turns on: a
collection is not a broader concept (`skos:Collection` exists precisely so "a bag of these" is not modeled
as "a kind above these") — that is the apparatus. We REJECT the faceted-classification runtime, where
facets partition: hence the anti-partition guard above. No RDF, no URIs, no inference engine; the schema
earns its keep, the runtime does not.

Run `python3 book-models/factory_vocabulary_model.py regenerate` to write the artifact; `... verify` to
drift-check; `... tree` to print the WHOLE/PART/COLLECTIVE/KIND/PROPERTY/ENVIRONMENT structure; `... tests`
to print the per-term role tests and negative rules; `... foreshadow` to print the manufacturing -> software
foreshadowing map.
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass, field

_HERE = os.path.dirname(os.path.abspath(__file__))
_ARTIFACT = os.path.join(_HERE, "factory-vocabulary.json")
_DECLARED = os.path.join(_HERE, "factory_vocabulary_declared.json")
#: The chapter the vocabulary governs. FV8 joins `author_named_sections[].file` against it, so a renamed
#: chapter file reddens rather than silently emptying the gap report.
_PART5 = os.path.join(os.path.dirname(_HERE), "book", "part5")

_PROVENANCE = ("GENERATED by book-models/factory_vocabulary_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/factory_vocabulary_model.py regenerate`. Derived from the "
               "hand-authored vocabulary in book-models/factory_vocabulary_declared.json.")

_MODEL_NOTE = (
    "The factory-vocabulary model holds the INTERNAL EDITING vocabulary behind Chapter 5's factory "
    "language — never printed in the book. Three kinds of node, not one flat list: a WHOLE (the factory) "
    "holding a PART (the fabricator) and a COLLECTIVE (engineering apparatus) whose members are the five "
    "KINDs (machinery, tooling, representation, control, infrastructure), plus a PROPERTY (engineering "
    "capital) that holds OF accumulated apparatus and an ENVIRONMENT the arrangement creates. Apparatus is "
    "the collective noun, NOT a fourth category; capital is a property, NOT a fifth. The kinds OVERLAP by "
    "design — `control` names what a decision DOES, not a physical category parallel to tooling — and the "
    "`partition` guard carries the closed anti-partition value so no consumer renders them as disjoint "
    "bins. `misuse_collocations` and `heterogeneous_list` are the deterministic part a lint can hold "
    "(lint_factory_vocabulary.py); the role tests are the part a human applies.")

#: The closed set of node kinds. Three DISTINCT kinds of node, plus the whole and the part they hang from.
#: A sixth value is a model change, not an append — the author's correction is exactly that `collective`
#: and `property` are NOT more `kind`s.
NODE_KINDS = ("whole", "part", "collective", "kind", "property", "environment")

#: The closed anti-partition guard (FV4). Present verbatim, or a consumer could render the kinds as
#: mutually exclusive facets — which the author explicitly ruled out. The analogue of the capability
#: ladder's `capability-not-maturity` guard.
PARTITION_GUARD = "kinds-overlap-not-partition"

#: The closed set of misuse-collocation confidence tiers.
#:   `named`           — the author named this phrase as a misuse; a lint finding.
#:   `author-defended` — the author explicitly DEFENDS this phrase; reported for context, NEVER a finding.
CONFIDENCE_TIERS = ("named", "author-defended")

#: The closed set of usage-licence dispositions for retained-but-constrained words.
DISPOSITIONS = ("retain", "retain-narrow")


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Node:
    """One node of the vocabulary. `id` is the kebab join key (the slug the term registry and the lint's
    `reassign_to` both resolve against); `node_kind` its place in the three-kinds-of-node structure;
    `role_test` the question that decides whether the word applies at a site; `negative_rule` the
    load-bearing half — what the word must NOT be stretched to cover.

    The structural edges are deliberately DIFFERENT fields per node kind, so the distinction cannot blur:
    `parent` (a part/collective hangs from the whole), `member_of` (a kind participates in the collective),
    `collects` (the collective's members), `holds_of` (a property holds of a collective), `overlaps` (kinds
    that deliberately intersect this one — the anti-partition edges)."""
    id: str
    node_kind: str
    label: str
    role_test: str
    negative_rule: str
    exemplars: "list[str]" = field(default_factory=list)
    parent: str = ""
    member_of: str = ""
    collects: "list[str]" = field(default_factory=list)
    holds_of: str = ""
    overlaps: "list[str]" = field(default_factory=list)
    aliases: "list[str]" = field(default_factory=list)


@dataclass
class UsageLicence:
    """A word RETAINED under a stated constraint rather than assigned a node — `support apparatus` (the
    support/production measurement) and `stock` (an economic noun, only where accumulation is the measured
    phenomenon). `accumulation_words` gives the lint the licence's deterministic window test."""
    id: str
    phrase: str
    disposition: str
    licence: str
    negative_rule: str
    accumulation_words: "list[str]" = field(default_factory=list)


@dataclass
class Foreshadow:
    """One manufacturing -> software foreshadowing pair. The mechanism by which the software-factory
    section sets up the case sections: choose the manufacturing example that PREFIGURES the software one,
    so the conceptual transfer is already prepared when the software term arrives. `kind` joins the pair
    onto the node table; the `_probes` lists are the deterministic presence test."""
    manufacturing: str
    software: str
    kind: str
    manufacturing_probes: "list[str]" = field(default_factory=list)
    software_probes: "list[str]" = field(default_factory=list)


@dataclass
class Misuse:
    """One named misuse collocation — a literal phrase, the node the model says applies instead, and the
    confidence tier. `author-defended` rows are context, never findings."""
    phrase: str
    reassign_to: str
    confidence: str
    note: str


@dataclass
class AuthorNamedSection:
    """One section the author's site-by-site vocabulary pass covers. Named STRUCTURALLY so a reflow cannot
    shift it: `heading` is a `##`/`###` heading's text, or `*opening*` for everything before the file's
    first `##`, or empty for the whole file. The lint derives the span at check time and reports the gap
    between the named sections and the findings it can actually produce."""
    id: str
    file: str
    heading: str = ""


@dataclass
class FactoryVocabularyModel:
    partition: str
    nodes: "list[Node]"
    usage_licences: "list[UsageLicence]"
    foreshadowing: "list[Foreshadow]"
    foreshadowing_scope: "dict[str, list[str]]"
    misuse_collocations: "list[Misuse]"
    heterogeneous_list: dict
    author_named_sections: "list[AuthorNamedSection]" = field(default_factory=list)

    def node(self, node_id: str) -> "Node | None":
        return next((n for n in self.nodes if n.id == node_id), None)

    def node_ids(self) -> "list[str]":
        return [n.id for n in self.nodes]

    def of_kind(self, node_kind: str) -> "list[Node]":
        return [n for n in self.nodes if n.node_kind == node_kind]

    def kind_ids(self) -> "list[str]":
        return [n.id for n in self.of_kind("kind")]

    def the_collective(self) -> "Node | None":
        collectives = self.of_kind("collective")
        return collectives[0] if len(collectives) == 1 else None

    def findings_collocations(self) -> "list[Misuse]":
        """The misuse rows a lint may raise as FINDINGS — `author-defended` rows excluded by construction,
        so a pre-rejected finding cannot reach the report."""
        return [m for m in self.misuse_collocations if m.confidence == "named"]

    def defended_collocations(self) -> "list[Misuse]":
        return [m for m in self.misuse_collocations if m.confidence == "author-defended"]


# ---- load + build -----------------------------------------------------------------------------------

def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def derive_model(raw: "dict | None" = None) -> FactoryVocabularyModel:
    """Build the vocabulary model from the hand-authored declarations — the one derivation the projections,
    the invariant walk, and the lint all share."""
    if raw is None:
        raw = _load_declared()
    nodes = [
        Node(id=n.get("id", ""), node_kind=n.get("node_kind", ""), label=n.get("label", ""),
             role_test=n.get("role_test", ""), negative_rule=n.get("negative_rule", ""),
             exemplars=list(n.get("exemplars", []) or []), parent=n.get("parent", ""),
             member_of=n.get("member_of", ""), collects=list(n.get("collects", []) or []),
             holds_of=n.get("holds_of", ""), overlaps=list(n.get("overlaps", []) or []),
             aliases=list(n.get("aliases", []) or []))
        for n in raw.get("nodes", [])
    ]
    licences = [
        UsageLicence(id=u.get("id", ""), phrase=u.get("phrase", ""), disposition=u.get("disposition", ""),
                     licence=u.get("licence", ""), negative_rule=u.get("negative_rule", ""),
                     accumulation_words=list(u.get("accumulation_words", []) or []))
        for u in raw.get("usage_licences", [])
    ]
    fore = [
        Foreshadow(manufacturing=f.get("manufacturing", ""), software=f.get("software", ""),
                   kind=f.get("kind", ""),
                   manufacturing_probes=list(f.get("manufacturing_probes", []) or []),
                   software_probes=list(f.get("software_probes", []) or []))
        for f in raw.get("foreshadowing", [])
    ]
    misuses = [
        Misuse(phrase=m.get("phrase", ""), reassign_to=m.get("reassign_to", ""),
               confidence=m.get("confidence", ""), note=m.get("note", ""))
        for m in raw.get("misuse_collocations", [])
    ]
    scope = {k: list(v or []) for k, v in (raw.get("foreshadowing_scope", {}) or {}).items()}
    named = [
        AuthorNamedSection(id=s.get("id", ""), file=s.get("file", ""), heading=s.get("heading") or "")
        for s in raw.get("author_named_sections", [])
    ]
    return FactoryVocabularyModel(
        partition=raw.get("partition", ""), nodes=nodes, usage_licences=licences, foreshadowing=fore,
        foreshadowing_scope=scope, misuse_collocations=misuses,
        heterogeneous_list=dict(raw.get("heterogeneous_list", {}) or {}),
        author_named_sections=named,
    )


# ---- invariants (FV1-FV7) ---------------------------------------------------------------------------

def structural_findings(model: "FactoryVocabularyModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA invariants over the vocabulary. Deterministic — every one is a set or
    enum check over declared data, never a judgment about prose.

    FV1 — node ids unique + kebab; `node_kind` in the closed NODE_KINDS; `label`, `role_test`, and
          `negative_rule` non-empty on every node (a node without a negative rule is the failure this
          model exists to prevent — the role test alone lets a word creep).
    FV2 — CARDINALITY encodes the author's correction: exactly one `whole`, one `collective`, one
          `property`, one `environment`. A second collective or property would re-open precisely the
          "fourth category / fifth category" error the correction closed.
    FV3 — the collective's `collects` list is EXACTLY the set of `kind` node ids (total and closed): every
          kind participates in the apparatus, and the apparatus collects nothing that is not a kind. Every
          kind also declares `member_of` == the collective, so the edge is stated from both ends.
    FV4 — ANTI-PARTITION: `partition` == PARTITION_GUARD, `control` declares at least two `overlaps`, and
          every `overlaps` / `parent` / `member_of` / `holds_of` id resolves to a node.
    FV5 — the `property` holds_of the `collective` (capital is an interpretation OF accumulated apparatus,
          not a sibling of the kinds); the `part` and the `collective` both `parent` the `whole`.
    FV6 — the foreshadowing map: `manufacturing`, `software`, and both probe lists non-empty, and every
          `kind` value resolves to a `kind` node id (the map joins onto the node table, so a renamed kind
          cannot orphan the transfer). The map need not be surjective over the kinds — `infrastructure`
          has no manufacturing counterpart the chapter uses, and that is an honest gap, not a finding.
    FV7 — misuse rows: `confidence` in CONFIDENCE_TIERS; a `named` row's `reassign_to` resolves to a node
          id; an `author-defended` row carries an EMPTY `reassign_to` (it is not a finding, so it has no
          replacement) and a non-empty note. Usage licences: `disposition` in DISPOSITIONS, licence and
          negative rule non-empty. The heterogeneous-list spec: non-empty terminals + members, and its
          `reassign_to` resolves.

    (Drift — the artifact equals a fresh derivation — is the `verify` CLI, mirroring the siblings.)"""
    if model is None:
        model = derive_model()
    out: "list[str]" = []
    ids = set()

    # FV1
    for n in model.nodes:
        if n.id in ids:
            out.append(f"FV1 duplicate node id {n.id!r}")
        ids.add(n.id)
        if not n.id or n.id != n.id.lower() or not all(p.isalnum() for p in n.id.split("-")):
            out.append(f"FV1 node id {n.id!r} is not kebab-case")
        if n.node_kind not in NODE_KINDS:
            out.append(f"FV1 node {n.id!r} node_kind {n.node_kind!r} not in {NODE_KINDS}")
        for fname in ("label", "role_test", "negative_rule"):
            if not str(getattr(n, fname)).strip():
                out.append(f"FV1 node {n.id!r} has empty {fname}")

    # FV2 — the cardinality that encodes the correction.
    for solo in ("whole", "collective", "property", "environment"):
        got = model.of_kind(solo)
        if len(got) != 1:
            out.append(f"FV2 expected exactly one {solo!r} node, found {len(got)} "
                       f"({[n.id for n in got]}) — a second {solo} re-opens the "
                       f"'apparatus is a fourth category / capital is a fifth' error")

    # FV3 — collects == the kind set, stated from both ends.
    collective = model.the_collective()
    kinds = set(model.kind_ids())
    if collective is not None:
        collected = set(collective.collects)
        for missing in sorted(kinds - collected):
            out.append(f"FV3 collective {collective.id!r} does not collect kind {missing!r} "
                       f"(every kind participates in the apparatus)")
        for extra in sorted(collected - kinds):
            out.append(f"FV3 collective {collective.id!r} collects {extra!r}, which is not a `kind` node")
        for k in model.of_kind("kind"):
            if k.member_of != collective.id:
                out.append(f"FV3 kind {k.id!r} member_of {k.member_of!r} — expected {collective.id!r}")

    # FV4 — the anti-partition guard + edge resolution.
    if model.partition != PARTITION_GUARD:
        out.append(f"FV4 partition {model.partition!r} is not the closed anti-partition value "
                   f"{PARTITION_GUARD!r} — without it a consumer may render the kinds as disjoint bins")
    control = model.node("control")
    if control is None:
        out.append("FV4 no `control` node — the overlapping kind the anti-partition rule is about")
    elif len([o for o in control.overlaps if o != "control"]) < 2:
        out.append("FV4 `control` declares fewer than two `overlaps` — the model must state the overlap "
                   "explicitly so it cannot be read as a partition")
    for n in model.nodes:
        for fname in ("parent", "member_of", "holds_of"):
            val = getattr(n, fname)
            if val and val not in ids:
                out.append(f"FV4 node {n.id!r} {fname} {val!r} resolves to no node")
        for o in n.overlaps:
            if o not in kinds:
                out.append(f"FV4 node {n.id!r} overlaps {o!r}, which is not a `kind` node")

    # FV5 — the property hangs off the collective; part + collective hang off the whole.
    whole = model.of_kind("whole")
    prop = model.of_kind("property")
    if collective is not None and prop:
        if prop[0].holds_of != collective.id:
            out.append(f"FV5 property {prop[0].id!r} holds_of {prop[0].holds_of!r} — expected the "
                       f"collective {collective.id!r} (capital is a property OF accumulated apparatus)")
    if whole:
        for n in model.of_kind("part") + model.of_kind("collective"):
            if n.parent != whole[0].id:
                out.append(f"FV5 node {n.id!r} parent {n.parent!r} — expected the whole {whole[0].id!r}")

    # FV6 — the foreshadowing map joins onto the kinds.
    for f in model.foreshadowing:
        for fname in ("manufacturing", "software"):
            if not str(getattr(f, fname)).strip():
                out.append(f"FV6 foreshadowing row {f.manufacturing!r}->{f.software!r} has empty {fname}")
        if not f.manufacturing_probes or not f.software_probes:
            out.append(f"FV6 foreshadowing row {f.manufacturing!r}->{f.software!r} is missing a probe list "
                       f"(the deterministic presence test has nothing to run)")
        if f.kind not in kinds:
            out.append(f"FV6 foreshadowing row {f.manufacturing!r}->{f.software!r} kind {f.kind!r} "
                       f"resolves to no `kind` node")
    for side in ("manufacturing", "software"):
        if not model.foreshadowing_scope.get(side):
            out.append(f"FV6 foreshadowing_scope is missing the {side!r} file list")

    # FV7 — misuse rows + usage licences + the list spec.
    for m in model.misuse_collocations:
        if m.confidence not in CONFIDENCE_TIERS:
            out.append(f"FV7 misuse {m.phrase!r} confidence {m.confidence!r} not in {CONFIDENCE_TIERS}")
        if not m.phrase.strip() or not m.note.strip():
            out.append(f"FV7 misuse {m.phrase!r} has an empty phrase or note")
        if m.confidence == "named" and m.reassign_to not in ids:
            out.append(f"FV7 misuse {m.phrase!r} reassign_to {m.reassign_to!r} resolves to no node")
        if m.confidence == "author-defended" and m.reassign_to:
            out.append(f"FV7 misuse {m.phrase!r} is author-defended but carries reassign_to "
                       f"{m.reassign_to!r} — a defended phrase has no replacement")
    for u in model.usage_licences:
        if u.disposition not in DISPOSITIONS:
            out.append(f"FV7 usage licence {u.id!r} disposition {u.disposition!r} not in {DISPOSITIONS}")
        for fname in ("phrase", "licence", "negative_rule"):
            if not str(getattr(u, fname)).strip():
                out.append(f"FV7 usage licence {u.id!r} has empty {fname}")
    hl = model.heterogeneous_list
    if not hl.get("terminal_patterns") or not hl.get("member_words"):
        out.append("FV7 heterogeneous_list is missing terminal_patterns or member_words")
    if hl.get("reassign_to") not in ids:
        out.append(f"FV7 heterogeneous_list reassign_to {hl.get('reassign_to')!r} resolves to no node")

    # FV8 — the author's named sections resolve against real files, and each row carries an id. The HEADING
    # itself is resolved by the lint (which owns file reading); here we hold the shape and the file join, so
    # a renamed chapter file reddens rather than silently emptying the gap report.
    seen_ids: "set[str]" = set()
    for s in model.author_named_sections:
        if not s.id.strip():
            out.append("FV8 author_named_sections row has an empty id")
        if s.id in seen_ids:
            out.append(f"FV8 duplicate author_named_sections id {s.id!r}")
        seen_ids.add(s.id)
        if not os.path.isfile(os.path.join(_PART5, s.file)):
            out.append(f"FV8 author_named_sections {s.id!r} names file {s.file!r}, which does not exist "
                       f"in book/part5/")
    return out


# ---- projections ------------------------------------------------------------------------------------

def render_tree(model: "FactoryVocabularyModel | None" = None) -> str:
    """The WHOLE / PART / COLLECTIVE / KIND / PROPERTY / ENVIRONMENT structure as an indented tree — the
    shape an editor should hold in mind. Printed by the CLI, never by the book."""
    if model is None:
        model = derive_model()
    lines: "list[str]" = []
    for w in model.of_kind("whole"):
        lines.append(f"WHOLE        {w.id}  — {w.label}")
    for p in model.of_kind("part"):
        lines.append(f"  PART       {p.id}  — {p.label}")
    coll = model.the_collective()
    if coll is not None:
        lines.append(f"  COLLECTIVE {coll.id}  — {coll.label}   (a collective noun, NOT a sibling kind)")
        for k in model.of_kind("kind"):
            over = f"   [overlaps: {', '.join(k.overlaps)}]" if k.overlaps else ""
            lines.append(f"    KIND     {k.id}  — {k.label}{over}")
    for pr in model.of_kind("property"):
        lines.append(f"PROPERTY     {pr.id}  — holds of `{pr.holds_of}` (an interpretation, not a kind)")
    for e in model.of_kind("environment"):
        lines.append(f"ENVIRONMENT  {e.id}  — {e.label}")
    lines.append(f"guard        partition = {model.partition}  (the kinds OVERLAP; they do not partition)")
    return "\n".join(lines)


def render_foreshadow_md(model: "FactoryVocabularyModel | None" = None) -> str:
    """The foreshadowing map as a table — the manufacturing example chosen to PREFIGURE each software
    term, and the kind the pair instantiates."""
    if model is None:
        model = derive_model()
    rows = [f"| {f.manufacturing} | {f.software} | `{f.kind}` |" for f in model.foreshadowing]
    return "\n".join(["| manufacturing example | → software counterpart | kind |", "|---|---|---|", *rows])


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "FactoryVocabularyModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "nodes": len(model.nodes),
            "by_node_kind": {nk: len(model.of_kind(nk)) for nk in NODE_KINDS},
            "usage_licences": len(model.usage_licences),
            "foreshadowing_pairs": len(model.foreshadowing),
            "misuse_named": len(model.findings_collocations()),
            "misuse_author_defended": len(model.defended_collocations()),
            "author_named_sections": len(model.author_named_sections),
        },
        "partition": model.partition,
        "nodes": [asdict(n) for n in model.nodes],
        "usage_licences": [asdict(u) for u in model.usage_licences],
        "foreshadowing": [asdict(f) for f in model.foreshadowing],
        "foreshadowing_scope": {k: list(v) for k, v in model.foreshadowing_scope.items()},
        "misuse_collocations": [asdict(m) for m in model.misuse_collocations],
        "heterogeneous_list": dict(model.heterogeneous_list),
        "author_named_sections": [asdict(s) for s in model.author_named_sections],
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['nodes']} nodes "
          f"({c['by_node_kind']['kind']} kinds under 1 collective); {c['usage_licences']} usage licence(s); "
          f"{c['foreshadowing_pairs']} foreshadowing pair(s); {c['misuse_named']} named misuse(s) + "
          f"{c['misuse_author_defended']} author-defended")
    fs = structural_findings()
    if fs:
        print(f"  {len(fs)} structural finding(s):")
        for f in fs:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    with open(_ARTIFACT, encoding="utf-8") as fh:
        return json.load(fh)


def verify() -> int:
    """Drift as a CLI: the on-disk artifact must equal a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    keys = ("partition", "nodes", "usage_licences", "foreshadowing", "foreshadowing_scope",
            "misuse_collocations", "heterogeneous_list", "author_named_sections", "_counts")
    if any(stored.get(k) != fresh[k] for k in keys):
        print("DRIFT: factory-vocabulary.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"factory-vocabulary.json is in sync ({fresh['_counts']['nodes']} nodes, "
          f"{fresh['_counts']['foreshadowing_pairs']} foreshadowing pairs)")
    return 0


# ---- CLI --------------------------------------------------------------------------------------------

def _print_tests() -> int:
    model = derive_model()
    print("== factory vocabulary — role tests and negative rules (the editing model; never printed) ==")
    for n in model.nodes:
        print(f"\n{n.id}  [{n.node_kind}]  {n.label}")
        print(f"  ROLE TEST  {n.role_test}")
        print(f"  NEGATIVE   {n.negative_rule}")
        if n.exemplars:
            print(f"  EXEMPLARS  {'; '.join(n.exemplars)}")
    for u in model.usage_licences:
        print(f"\n{u.id}  [usage-licence: {u.disposition}]  \"{u.phrase}\"")
        print(f"  LICENCE    {u.licence}")
        print(f"  NEGATIVE   {u.negative_rule}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "tree":
        print(render_tree())
        return 0
    if cmd == "tests":
        return _print_tests()
    if cmd == "foreshadow":
        print(render_foreshadow_md())
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
