"""The LITERATURE-POSITIONING view — a typed model of the book's Literature-Positioning Pass (LPP): every
place the book situates itself against prior and adjacent work, each carrying the pass's X->Y->Z frame and
its citations as MODELED objects nested under the argument spine. Sibling to argument-spine and
flagship-stack in book-models/.

WHY A NEW MODEL, NOT AN EXTENSION.  The argument-spine holds the book's OWN ordered claims; the claims
model holds unordered stances with a contradiction predicate. A literature-positioning intervention is
neither — it is a place where the book positions itself against OUTSIDE work, carrying fields no sibling
holds: the three-line X (established lineage) -> Y (current frontier) -> Z (narrow MAGE move) frame, the
target chapter locations, and the load-bearing addition — citations as first-class objects. A new object
with fields none of the siblings carry earns its own file, the same rule the claims and spine models cleared.

CITATIONS ARE NESTED UNDER THE SPINE.  A citation is not a bare bib key. Each is `{key, backs_claims[],
relation}`: `key` = the references.bib key; `backs_claims[]` = the argument-spine claim id(s) the citation
substantiates or situates — the join that nests the literature UNDER the spine, so a spine claim is
reachable from its backing literature; `relation` in RELATIONS. This layer is the LITERATURE half of the
substantiation aggregator (the data-claim ledger is the DATA half): joined under each spine claim, the two
flag reality-claims with neither data nor literature behind them. LP6 holds the join integrity — every
`backs_claims` id resolves to a real spine claim.

THE CONFORMANCE CHECK (LP1-LP6) IS AUDIT-ONLY FIRST.  Following the repo's blocking-lint landing discipline,
the check reports but does not gate. A record that drops its X/Y/Z, names an unknown spine claim, or (once
landed) cites a key absent from the .bib reddens the audit; a follow-up promotes it to blocking once the
LPP prose waves land and a clean session confirms the drain.

- LP1 - TRACEABILITY + SCHEMA: every intervention has non-empty X, Y, Z; ids unique + kebab; section is a
  `§N` tag; status in STATUSES; every citation relation in RELATIONS; a landed record carries a fold target
  of \"\" (folded interventions are planned until their wave lands).
- LP2 - THESIS JOIN: every `advances_theses` id resolves to a real argument-spine claim.
- LP3 - LANDING INTEGRITY: for status:landed records, every citation key resolves in references.bib AND at
  least one target_location chapter actually contains the key (the intervention really landed). For
  status:planned records the citations are reported as PENDING, never a failure.
- LP4 - LOCATION JOIN: every target_location resolves to a real book chapter slug (warn on unknown).
- LP5 - COVERAGE / BURNDOWN: the planned-vs-landed split — the LPP burndown surface (informational note).
- LP6 - CITATION JOIN: every citation's `backs_claims` resolves to a real spine claim (the nest-under-the-
  spine integrity the substantiation aggregator depends on).

Run `python3 book-models/lit_positioning_model.py regenerate` to write the artifact; `... verify` to
drift-check; `... list` to print the burndown; `... litpos <id>` to print one intervention's X/Y/Z + cites.
"""
from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import asdict, dataclass, field

from _book_pages import book_page_slugs  # shared chapter-page-slug resolver (extract-on-2nd-site)

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)  # the catalogue root — book/ lives beneath it
_ARTIFACT = os.path.join(_HERE, "lit-positioning.json")
_DECLARED = os.path.join(_HERE, "lit_positioning_declared.json")
_SPINE_DECLARED = os.path.join(_HERE, "argument_spine_declared.json")
_REFERENCES_BIB = os.path.join(_ROOT, "book", "references.bib")

_PROVENANCE = ("GENERATED by book-models/lit_positioning_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/lit_positioning_model.py regenerate`. Derived from the hand-authored "
               "lit_positioning_declared.json, resolved against the argument spine, references.bib, and the "
               "book chapters on disk.")

_MODEL_NOTE = (
    "The literature-positioning model holds the book's Literature-Positioning Pass — each place the book "
    "situates itself against outside work, carrying the X (established lineage) -> Y (current frontier) -> "
    "Z (narrow MAGE move) frame and its citations as MODELED objects {key, backs_claims, relation} nested "
    "under the argument spine. It is the LITERATURE half of the substantiation aggregator (the data-claim "
    "ledger is the DATA half). The LP1-LP6 conformance check holds the frame mechanically: traceability + "
    "schema, thesis join, landing integrity, location join, coverage/burndown, citation join. It lands "
    "audit-only-first — a record that drops its X/Y/Z or (once landed) cites a key absent from the .bib "
    "reddens the audit but does not gate while the LPP prose waves are still landing. `status` planned|"
    "landed is the burndown signal; all 11 interventions (§1-§6, §8-§12) are landed today. "
    "The section run is §1-§6, §8-§12 — §7 (architecture conformance) is deliberately absent, handled by "
    "the author separately rather than as a modeled LPP intervention (see lit_positioning_declared.json's "
    "`_note`).")

#: The three-part frame every intervention must carry (LP1 holds each non-empty). The traceability
#: requirement from the LPP instructions: each intervention's lineage->frontier->move must be legible.
FRAME_FIELDS = ("x", "y", "z")

#: The CLOSED citation-relation vocabulary. The LPP verb discipline: `substantiates` = direct empirical
#: support ("shows"); `situates` = positions MAGE against the lineage/frontier; `corroborates` = an
#: independent result that converges; `convergent-evidence` = a practitioner build-report that converges but
#: does NOT establish. A relation outside this set is an LP1 finding.
RELATIONS = ("substantiates", "situates", "corroborates", "convergent-evidence")

#: The CLOSED status vocabulary — the LPP burndown states. `planned` = modeled, not yet written (its cites
#: may be planned keys absent from the .bib); `landed` = the X->Y->Z passage + its cites are in the book.
STATUSES = ("planned", "landed")

#: A `§N` section tag — the intervention's number in the LPP instructions (§7 is deliberately absent).
_SECTION_RE = re.compile(r"^§\d+$")

#: References.bib key extractor — `@type{key,` at line start. The join target for LP3 landing integrity.
_BIB_KEY_RE = re.compile(r"^@\w+\{([^,]+),", re.MULTILINE)


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Citation:
    """A modeled citation nested under the spine. `key` joins to references.bib (LP3 for landed records);
    `backs_claims` are the spine claim id(s) it substantiates or situates (LP6 join integrity — the nest);
    `relation` is its verb-disciplined role in RELATIONS."""
    key: str
    backs_claims: list[str]
    relation: str
    illustrates_pattern: str = ""        # OPTIONAL: the catalogue pattern slug this cite is a prior-art
                                         # known-use of (the GoF double-duty — spine substantiation via
                                         # backs_claims + catalogue prior-art via this). "" when the cite
                                         # instantiates no catalogue pattern.
    resolves_bib: bool = False           # derived (LP3): the key is present in references.bib
    backs_resolve: bool = False          # derived (LP6): every backs_claims id names a spine claim


@dataclass
class Intervention:
    """One LPP intervention: a place the book positions itself against outside work. The X/Y/Z frame is the
    stack-LOCAL editorial judgment; `citations` nest the literature under the spine; `advances_theses` are
    the spine claims this whole intervention advances; `status`/`fold_target` drive the burndown."""
    id: str
    section: str
    title: str
    x: str
    y: str
    z: str
    target_locations: list[str]
    citations: list[Citation]
    advances_theses: list[str]
    status: str
    fold_target: str = ""
    notes: str = ""
    locations_resolve: list[bool] = field(default_factory=list)  # derived (LP4): per target_location
    theses_resolve: list[bool] = field(default_factory=list)     # derived (LP2): per advances_theses id
    landed_appears: bool = False        # derived (LP3): a landed record's cites appear in a target chapter


@dataclass
class LitPositioningModel:
    interventions: list[Intervention]


# ---- join sources (read at check time — single source of truth, no snapshot) ------------------------

def _spine_ids() -> "set[str]":
    """Every argument-spine claim id, read from the hand-authored spine declared source at check time."""
    if not os.path.isfile(_SPINE_DECLARED):
        return set()
    data = json.load(open(_SPINE_DECLARED, encoding="utf-8"))
    return {c["id"] for c in data.get("spine", [])}


def _claim_ids() -> "set[str]":
    """The join target for LP2 + LP6 — the full claim universe a citation may nest under: the argument-spine
    claims PLUS the theory nodes PLUS the discussion claims. A lit-positioning citation legitimately backs a
    DISCUSSION claim (a reality-claim in the book's Discussion prose) or a THEORY node, not only a spine
    claim, so the resolvable set is the same universe the substantiation aggregator joins over — one source of
    truth, no drift. Robust to substantiation's absence (falls back to the spine alone)."""
    ids = _spine_ids()
    try:
        import substantiation  # sibling book-model; the claim-universe SSoT
        ids = ids | substantiation._theory_ids() | substantiation._discussion_ids()
    except Exception:  # noqa: BLE001 — degrade to spine-only if the aggregator is unavailable; LP is audit-only
        pass
    return ids


def _bib_keys() -> "set[str]":
    """The join target for LP3 — every references.bib entry key, read at check time."""
    if not os.path.isfile(_REFERENCES_BIB):
        return set()
    text = open(_REFERENCES_BIB, encoding="utf-8").read()
    return {m.strip() for m in _BIB_KEY_RE.findall(text)}


def _chapter_slugs() -> "set[str]":
    """The join target for LP4 — every book chapter slug. The UNION of two sources: (1) the argument-spine's
    chapter labels (exhaustive over the outline by AS5, so it covers chapters carried only in the outline),
    and (2) the on-disk chapter files (the shared `_book_pages` resolver the sibling models use), so any real
    chapter page — e.g. a backmatter chapter the spine's chapter_advances map does not enumerate — resolves.
    The union only widens the valid set, so it can never introduce an LP4 finding. Read at check time."""
    import chapter_identity_model as chapter_identity  # noqa: E402 — sibling book-model
    slugs: "set[str]" = set(book_page_slugs())
    if os.path.isfile(_SPINE_DECLARED):
        data = json.load(open(_SPINE_DECLARED, encoding="utf-8"))
        slugs |= set(data.get("chapter_advances", {}))
    slugs |= chapter_identity.labels()  # target_locations are number-free identity labels now
    return slugs


def _chapter_text(slug: str) -> str:
    """The source markdown of a chapter, or '' when the key names no file. target_locations are number-free
    identity LABELS now, so resolve the label to its filename via the identity table and read it; fall back
    to a glob for a still-numbered slug (half-migration). Used by LP3 to confirm a landed cite actually
    appears in a target chapter."""
    import glob
    import chapter_identity_model as chapter_identity  # noqa: E402 — sibling book-model
    if slug in chapter_identity.labels():
        path = os.path.join(_ROOT, "book", chapter_identity.filename(slug))
        return open(path, encoding="utf-8").read() if os.path.isfile(path) else ""
    for sub in ("frontmatter", "part1", "part2", "part3", "part4", "part5", "part6", "conclusion", "backmatter"):
        hits = glob.glob(os.path.join(_ROOT, "book", sub, slug + ".md"))
        if hits:
            return open(hits[0], encoding="utf-8").read()
    return ""


# ---- load + build -----------------------------------------------------------------------------------

def _load_declared() -> dict:
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)


def derive_model() -> LitPositioningModel:
    """Build the model from the hand-authored declarations — the single derivation regen and the drift check
    share. Order is the authored order (the §-number order), so the artifact is deterministic."""
    decl = _load_declared()
    claims = _claim_ids()
    bib = _bib_keys()
    chapters = _chapter_slugs()
    interventions: list[Intervention] = []
    for r in decl.get("interventions", []):
        cites = [Citation(
            key=c["key"], backs_claims=list(c.get("backs_claims", [])), relation=c.get("relation", ""),
            illustrates_pattern=c.get("illustrates_pattern", ""),
            resolves_bib=c["key"] in bib,
            backs_resolve=all(cid in claims for cid in c.get("backs_claims", [])) and bool(c.get("backs_claims")),
        ) for c in r.get("citations", [])]
        locs = list(r.get("target_locations", []))
        theses = list(r.get("advances_theses", []))
        iv = Intervention(
            id=r["id"], section=r.get("section", ""), title=r.get("title", ""),
            x=r.get("x", ""), y=r.get("y", ""), z=r.get("z", ""),
            target_locations=locs,
            citations=cites, advances_theses=theses,
            status=r.get("status", "planned"), fold_target=r.get("fold_target", ""),
            notes=r.get("notes", ""),
            locations_resolve=[slug in chapters for slug in locs],
            theses_resolve=[tid in claims for tid in theses],
        )
        # LP3 derived: a landed record's cites appear in at least one target chapter's source.
        if iv.status == "landed":
            texts = [_chapter_text(slug) for slug in locs]
            iv.landed_appears = all(
                any(c.key in t for t in texts) for c in cites
            ) if cites else False
        interventions.append(iv)
    return LitPositioningModel(interventions=interventions)


# ---- invariants (LP1-LP6) ---------------------------------------------------------------------------

def structural_findings(model: "LitPositioningModel | None" = None) -> "list[str]":
    """The STRUCTURAL / SCHEMA + JOIN invariants LP1-LP6. Deterministic. LP5 (coverage/burndown) is a
    DERIVED note surfaced by the CLI, not a finding here. LP3 for planned records is reported as PENDING by
    the CLI, never a finding — only a LANDED record whose cite is absent from the .bib or from its target
    chapters reddens."""
    if model is None:
        model = derive_model()
    claims = _claim_ids()
    chapters = _chapter_slugs()
    findings: "list[str]" = []

    # LP1 - traceability + schema.
    seen: "set[str]" = set()
    for iv in model.interventions:
        if iv.id in seen:
            findings.append(f"LP1 duplicate intervention id {iv.id!r}")
        seen.add(iv.id)
        if not all(part.isalnum() for part in iv.id.split("-")) or iv.id != iv.id.lower():
            findings.append(f"LP1 intervention id {iv.id!r} is not kebab-case")
        if not _SECTION_RE.match(iv.section):
            findings.append(f"LP1 intervention {iv.id!r} section {iv.section!r} is not a §N tag")
        for f_name in FRAME_FIELDS:
            if not str(getattr(iv, f_name)).strip():
                findings.append(f"LP1 intervention {iv.id!r} has an empty {f_name.upper()} frame line")
        if iv.status not in STATUSES:
            findings.append(f"LP1 intervention {iv.id!r} status {iv.status!r} not in {STATUSES}")
        for c in iv.citations:
            if c.relation not in RELATIONS:
                findings.append(f"LP1 intervention {iv.id!r} citation {c.key!r} relation {c.relation!r} "
                                f"not in {RELATIONS}")
            if not c.backs_claims:
                findings.append(f"LP1 intervention {iv.id!r} citation {c.key!r} backs no claim")

    # LP2 - thesis join: every advances_theses id resolves to a real claim (spine, theory, or discussion).
    for iv in model.interventions:
        for tid in iv.advances_theses:
            if tid not in claims:
                findings.append(f"LP2 intervention {iv.id!r} advances unknown claim {tid!r}")

    # LP3 - landing integrity (LANDED records only; planned are PENDING, reported by the CLI).
    bib = _bib_keys()
    for iv in model.interventions:
        if iv.status != "landed":
            continue
        for c in iv.citations:
            if c.key not in bib:
                findings.append(f"LP3 landed intervention {iv.id!r} citation {c.key!r} resolves to no "
                                f"references.bib entry")
        texts = [_chapter_text(slug) for slug in iv.target_locations]
        for c in iv.citations:
            if not any(c.key in t for t in texts):
                findings.append(f"LP3 landed intervention {iv.id!r} citation {c.key!r} appears in none of "
                                f"its target chapters {iv.target_locations} (did it really land?)")

    # LP4 - location join: every target_location resolves to a real chapter slug (warn on unknown).
    for iv in model.interventions:
        for slug in iv.target_locations:
            if slug not in chapters:
                findings.append(f"LP4 intervention {iv.id!r} target_location {slug!r} is not a book chapter")

    # LP6 - citation join: every backs_claims id resolves to a real claim (spine, theory, or discussion — the
    # substantiation aggregator's full universe; a citation may nest under a discussion claim, not only a spine one).
    for iv in model.interventions:
        for c in iv.citations:
            for cid in c.backs_claims:
                if cid not in claims:
                    findings.append(f"LP6 intervention {iv.id!r} citation {c.key!r} backs unknown "
                                    f"claim {cid!r}")
    return findings


def burndown() -> "dict[str, list[str]]":
    """LP5 — the planned-vs-landed split, keyed by section. The LPP burndown surface."""
    model = derive_model()
    landed = [iv.section for iv in model.interventions if iv.status == "landed"]
    planned = [iv.section for iv in model.interventions if iv.status == "planned"]
    return {"landed": landed, "planned": planned}


def coverage_note() -> str:
    """LP5 as a human-readable line — the burndown, plus the count of planned citations still pending in the
    .bib (the prose waves' bibliography debt). Informational; never a gate finding."""
    model = derive_model()
    b = burndown()
    n = len(model.interventions)
    pending = sum(1 for iv in model.interventions if iv.status == "planned" for c in iv.citations
                  if not c.resolves_bib)
    resolved_planned = sum(1 for iv in model.interventions if iv.status == "planned" for c in iv.citations
                           if c.resolves_bib)
    return (f"LP5 LPP burndown — {len(b['landed'])}/{n} landed ({', '.join(b['landed']) or '—'}), "
            f"{len(b['planned'])}/{n} planned ({', '.join(b['planned']) or '—'}); "
            f"planned citations: {pending} PENDING in references.bib, {resolved_planned} already present.")


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: "LitPositioningModel | None" = None) -> dict:
    if model is None:
        model = derive_model()
    return {
        "_provenance": _PROVENANCE,
        "_note": _MODEL_NOTE,
        "_counts": {
            "interventions": len(model.interventions),
            "landed": sum(1 for iv in model.interventions if iv.status == "landed"),
            "planned": sum(1 for iv in model.interventions if iv.status == "planned"),
            "citations_total": sum(len(iv.citations) for iv in model.interventions),
            "citations_pending_bib": sum(1 for iv in model.interventions for c in iv.citations
                                         if not c.resolves_bib),
            "distinct_theses": len({t for iv in model.interventions for t in iv.advances_theses}),
        },
        "taxonomy": {"frame_fields": list(FRAME_FIELDS), "relations": list(RELATIONS),
                     "statuses": list(STATUSES)},
        "interventions": [asdict(iv) for iv in model.interventions],
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['interventions']} interventions "
          f"({c['landed']} landed, {c['planned']} planned); {c['citations_total']} citations "
          f"({c['citations_pending_bib']} pending in references.bib)")
    print(f"  {coverage_note()}")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} structural finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    else:
        print("  LP1-LP6 clean")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """LP-drift as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    if any(stored.get(k) != fresh[k] for k in ("interventions", "_counts")):
        print("DRIFT: lit-positioning.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"lit-positioning.json is in sync ({fresh['_counts']['interventions']} interventions, "
          f"{fresh['_counts']['landed']} landed)")
    return 0


# ---- CLI --------------------------------------------------------------------------------------------

def _status_tag(iv: "Intervention") -> str:
    tags = [iv.status.upper()]
    if iv.fold_target:
        tags.append(f"fold:{iv.fold_target}")
    return f"  [{'; '.join(tags)}]"


def _print_list() -> int:
    model = derive_model()
    print(f"== literature-positioning interventions ({len(model.interventions)}) ==")
    for iv in model.interventions:
        pend = sum(1 for c in iv.citations if not c.resolves_bib)
        print(f"  {iv.section:4} {iv.id}{_status_tag(iv)}")
        print(f"       {iv.title}  ·  {len(iv.citations)} cite(s) ({pend} pending bib)  "
              f"·  advances {', '.join(iv.advances_theses)}")
    print(f"  {coverage_note()}")
    return 0


def _print_litpos(target: str) -> int:
    model = derive_model()
    match = next((iv for iv in model.interventions
                  if iv.id == target or iv.section == target), None)
    if match is None:
        print(f"'{target}' is no literature-positioning intervention. "
              f"Run `python3 book-models/lit_positioning_model.py list`.")
        return 1
    print(f"== {match.title} ({match.id}, {match.section}) =={_status_tag(match)}")
    print(f"X (lineage):  {match.x}")
    print(f"Y (frontier): {match.y}")
    print(f"Z (MAGE move):{match.z}")
    print(f"advances theses: {', '.join(match.advances_theses)}")
    print(f"target locations: {', '.join(match.target_locations)}")
    print("citations (nested under the spine):")
    for c in match.citations:
        bibtag = "" if c.resolves_bib else "  [PENDING in references.bib]"
        print(f"  · {c.key}  [{c.relation}]{bibtag}")
        print(f"      backs: {', '.join(c.backs_claims)}")
    if match.notes:
        print(f"notes: {match.notes}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "verify"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "list":
        return _print_list()
    if cmd == "litpos":
        return _print_litpos(argv[2]) if len(argv) > 2 else _print_list()
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
