"""The METAPHOR-SLOGAN OCCURRENCE index — for every registered slogan (and every LOCAL, rationed metaphor),
each SITE it appears in the built book HTML, scanned fresh each run so it cannot drift. This is what makes
slogan DENSITY mechanical: the sibling `lint_slogan_density.py` reads this index for the competitor-at-full-
strength / over-use / used-once worklist, and `metaphor_spans_model.py` holds the registry it is derived from.

WHAT IS REUSED (A.10 — reuse, don't copy).  This module imports the derived-index scaffolding from
`projections_model` rather than re-implementing it:
  - `served_html_surfaces()` — the SINGLE source of truth for "which built .html is a served surface",
    filtered to the `book-web` projection glob so the surface universe cannot drift from the site walk;
  - `_resolve_projection` / `load_registry` — the glob→file resolution;
  - `_CSS_VAR` — the custom-property strip (a per-page palette token is never miscounted as prose);
  - the `to_jsonable` / `load_artifact` / freshness shape, structurally mirrored (the repo's canonical
    derived-model pattern).
It differs on TWO axes (the reason it is a distinct index, not the projection index): it matches the
CANONICAL slogan phrase + each declared COMPETITOR phrase (not the slug-as-words), and it records the
NEAREST PRECEDING anchor per hit, so the density lint can measure clustering ("two full occurrences within
X anchors").

WHAT IS INDEXED.  Every slogan (canonical + each competitor phrase) and every LOCAL metaphor (its
distinctive image NAME as a whole phrase — "evidence staircase", "compiler analogy" — the rationed images
the density lint checks). CORE metaphors are always-live vocabulary, exempt from the ration rule, and their
image words (loop, churn, printer) recur book-wide by design, so they are NOT indexed. A metaphor is matched
on its distinctive multi-word name rather than its per-token image words, so a book-ubiquitous token in a
name ("mage" in "the MAGE staircase") does not swamp the worklist with sanctioned recurrence.

HONEST SCOPE LIMIT (mirrors define-before-use).  The index matches REGISTERED phrases (canonical + declared
competitors) exactly — normalized for whitespace/case/terminal punctuation. It does NOT fuzzy-detect a novel
paraphrase nobody registered. The `<!-- slogan: id -->` author tag (harvested by the density lint) is how a
real occurrence enters scope for the tag-consistency class.

Run `python3 book-models/metaphor_slogan_index_model.py regenerate` to write the index; `... verify` to
freshness-check; `... where <slug>` to list a slogan/metaphor's occurrence sites.
"""
from __future__ import annotations

import html
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import projections_model as pm  # noqa: E402 — reuse served_html_surfaces / glob resolver / CSS-var strip
import metaphor_spans_model as msm  # noqa: E402 — the registry this index is derived from

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
_ARTIFACT = os.path.join(_HERE, "metaphor-slogan-index.json")

_PROVENANCE = ("GENERATED by book-models/metaphor_slogan_index_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/metaphor_slogan_index_model.py regenerate`. A DERIVED inversion: for "
               "each registered slogan (canonical + competitors) and each LOCAL metaphor (image tokens), the "
               "sites it appears in the built book HTML with the nearest preceding anchor. Re-derived each "
               "run from the built book-web pages, so it cannot itself drift.")

_TAG_RE = re.compile(r"<[^>]+>")
_SCRIPT_STYLE_RE = re.compile(r"<(script|style)\b.*?</\1>", re.S | re.I)
_ID_RE = re.compile(r'id="([A-Za-z0-9_-]+)"')


# ---- the book-web surface universe (reused from projections_model) ----------------------------------

def _book_web_files() -> "list[str]":
    """The built book-web HTML pages (book/*.html), via the shared served-surface walk + glob resolver — the
    same surfaces the projection index sees, so the two cannot drift apart."""
    surfaces = pm.served_html_surfaces()
    book_web = next(p for p in pm.load_registry() if p["id"] == "book-web")
    return sorted(pm._resolve_projection(book_web, surfaces))


# ---- segmentation + normalization -------------------------------------------------------------------

def _segments(raw: str) -> "list[tuple[str, str]]":
    """Split a page's HTML into (nearest-preceding-anchor, segment-html) pairs at each `id="…"` — the HTML
    twin of the chapter anchor walk. A hit inside a segment is credited to that segment's leading anchor;
    text before the first id carries the empty anchor. Script/style blocks are removed first so their
    contents never match as prose."""
    raw = _SCRIPT_STYLE_RE.sub(" ", raw)
    segs: "list[tuple[str, str]]" = []
    prev_pos, prev_anchor = 0, ""
    for m in _ID_RE.finditer(raw):
        segs.append((prev_anchor, raw[prev_pos:m.start()]))
        prev_pos, prev_anchor = m.start(), m.group(1)
    segs.append((prev_anchor, raw[prev_pos:]))
    return segs


def _norm_text(raw: str) -> str:
    """A segment's visible prose, normalized for phrase matching: CSS vars stripped, tags removed, entities
    unescaped, whitespace collapsed, lowercased."""
    txt = pm._CSS_VAR.sub(" ", raw)
    txt = _TAG_RE.sub(" ", txt)
    txt = html.unescape(txt)
    return re.sub(r"\s+", " ", txt).strip().lower()


def _norm_phrase(phrase: str) -> str:
    """A registered phrase normalized to the same shape as `_norm_text`, with terminal punctuation stripped
    (so a canonical ending in '.' matches prose that does not)."""
    p = re.sub(r"\s+", " ", html.unescape(phrase)).strip().lower()
    return p.rstrip(".,;:!?")


def _count(norm_text: str, norm_phrase: str) -> int:
    """Whole-phrase occurrences of `norm_phrase` in `norm_text`, with word-ish boundaries at the ends (a
    hyphen-joined or word-joined neighbour does not count). Exact registered-phrase match — the honest scope
    limit the design accepts."""
    if not norm_phrase:
        return 0
    return len(re.findall(r"(?<![\w-])" + re.escape(norm_phrase) + r"(?![\w-])", norm_text))


# ---- the indexed variants ---------------------------------------------------------------------------

def _metaphor_image_phrase(name: str) -> str:
    """A local metaphor's distinctive image as a whole phrase — its name, lowercased, with a leading article
    dropped and only the first slash-alternative kept ('Poka-yoke / the fixture' -> 'poka-yoke'). Matching a
    multi-word name keeps a book-ubiquitous token from swamping the worklist."""
    phrase = name.split("/")[0].strip().lower()
    return re.sub(r"^(the|a|an)\s+", "", phrase)


def _indexed_entries(model: "msm.MetaphorModel") -> "list[tuple[str, str, dict, list[tuple[str, str]]]]":
    """Every entry to index → (slug, kind, elaborates, [(variant, phrase), …]). Slogans contribute their
    canonical (variant 'canonical') + each competitor (variant 'competitor:<phrase>'); LOCAL metaphors
    contribute their distinctive image name (variant 'image'). Core metaphors are exempt (see docstring)."""
    out: "list[tuple[str, str, dict, list[tuple[str, str]]]]" = []
    for s in model.slogans:
        variants = [("canonical", s.canonical)] + [(f"competitor:{c}", c) for c in s.competitors]
        out.append((s.slug, "slogan", s.elaborates, variants))
    for m in model.local():
        out.append((m.slug, "metaphor", m.elaborates, [("image", _metaphor_image_phrase(m.name))]))
    return out


def build_index() -> "dict[str, dict]":
    """Scan the built book-web HTML for every indexed variant → `{slug: {slug, kind, elaborates, sites}}`,
    each site `{file, anchor, occ, variant}` in file → segment → variant order (deterministic)."""
    model = msm.derive_model()
    files = _book_web_files()
    segmented: "dict[str, list[tuple[str, str]]]" = {}
    for rel in files:
        raw = open(os.path.join(_ROOT, rel), encoding="utf-8").read()
        segmented[rel] = [(anchor, _norm_text(seg)) for anchor, seg in _segments(raw)]

    index: "dict[str, dict]" = {}
    for slug, kind, elaborates, variants in _indexed_entries(model):
        norm_variants = [(variant, _norm_phrase(phrase)) for variant, phrase in variants]
        sites: "list[dict]" = []
        for rel in files:
            for anchor, ntext in segmented[rel]:
                for variant, nphrase in norm_variants:
                    n = _count(ntext, nphrase)
                    if n:
                        sites.append({"file": rel, "anchor": anchor, "occ": n, "variant": variant})
        if sites:
            index[slug] = {
                "slug": slug,
                "kind": kind,
                "elaborates": {"model": (elaborates or {}).get("model", ""),
                               "id": (elaborates or {}).get("id", "")},
                "sites": sites,
            }
    return index


def _idea_key(elaborates: dict) -> str:
    return f"{elaborates.get('model', '')}/{elaborates.get('id', '')}"


def to_jsonable(index: "dict[str, dict] | None" = None) -> dict:
    if index is None:
        index = build_index()
    total_sites = sum(len(e["sites"]) for e in index.values())
    total_occ = sum(site["occ"] for e in index.values() for site in e["sites"])
    by_idea: "dict[str, int]" = {}
    for e in index.values():
        key = _idea_key(e["elaborates"])
        by_idea[key] = by_idea.get(key, 0) + sum(site["occ"] for site in e["sites"])
    return {
        "_provenance": _PROVENANCE,
        "_counts": {
            "indexed_slugs": len(index),
            "total_sites": total_sites,
            "total_occurrences": total_occ,
            # per elaborates idea — the competing-canonical grouping precomputed.
            "by_idea": dict(sorted(by_idea.items())),
        },
        "index": {k: index[k] for k in sorted(index)},
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['indexed_slugs']} slug(s) render across "
          f"{c['total_sites']} site(s), {c['total_occurrences']} occurrence(s)")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


# ---- the freshness gate (BLOCKING) ------------------------------------------------------------------

def freshness_findings() -> "list[str]":
    """FRESHNESS — the on-disk index equals a fresh re-derivation from the built book HTML. A page edited /
    rebuilt without regenerating the index is the finding. Same shape as `projections_model.freshness_findings`."""
    stored = load_artifact()
    if stored is None:
        return [f"{os.path.relpath(_ARTIFACT)} missing — run "
                f"`python3 book-models/metaphor_slogan_index_model.py regenerate`"]
    # Build-order guard: the fresh scan re-derives from the emitted book-web surface (the gitignored
    # `book/web/docs/*.md` bodies). In a pre-build checkout — CI runs `catalog.py validate` BEFORE
    # `catalog.py build` emits that tree — the surface is absent, so a re-derivation is impossible, not
    # stale: nothing has drifted; the input is missing. Defer to the post-build consumers, which see the
    # full surface (the suite's freshness check after CI's build step, and the pre-commit hook's
    # regen-after-build), rather than reporting a false DRIFT.
    if not _book_web_files():
        return []
    fresh = to_jsonable()
    if stored.get("index") != fresh["index"] or stored.get("_counts") != fresh["_counts"]:
        return [f"DRIFT: {os.path.relpath(_ARTIFACT)} disagrees with a fresh scan of the built book HTML — "
                f"regenerate with `python3 book-models/metaphor_slogan_index_model.py regenerate`"]
    return []


# ---- query surface ----------------------------------------------------------------------------------

def where(slug: str) -> int:
    entry = (load_artifact() or {}).get("index", {}).get(slug)
    if entry is None:
        print(f"{slug!r}: renders on no book page today (or the index is stale — regenerate)")
        return 0
    print(f"{slug} ({entry['kind']}, elaborates {_idea_key(entry['elaborates'])}) — {len(entry['sites'])} site(s):")
    for site in entry["sites"]:
        print(f"  {site['file']}#{site['anchor'] or '(top)'}  x{site['occ']}  [{site['variant']}]")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "regenerate"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        findings = freshness_findings()
        if findings:
            for f in findings:
                print(f)
            return 1
        print(f"metaphor-slogan-index.json is in sync ({(load_artifact() or {}).get('_counts', {})})")
        return 0
    if cmd == "where":
        if len(argv) < 3:
            print(f"usage: {argv[0]} where <slug>")
            return 2
        return where(argv[2])
    print(f"usage: {argv[0]} [regenerate|verify|where <slug>]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
