"""PROJECTOR `nav_map_model` — the book's cartographic navigation layer (round-7 Thrust B).

Projects the book-level transit-map SVGs from ONE declared model (`nav-model.json`) plus the book's
Part-sequence single source of truth (`build_book._PART_TITLES`):

  * `assets/nav-subway-p{1..6}.svg` — the BOOK-LEVEL "subway map": the six Parts as a line of stations
    (Mindset → Modeling → Alignment → Method → Evidence → Profession), one variant per Part with THAT Part's
    station highlighted. Answers "where am I in the book?"

(The former Part-local map family — `assets/nav-local-p{1..6}.svg` — was retired in the round-7 opener
anatomy change: the leaner opener embeds only the subway map, and the Part-opener verso now renders its own
native vocab block from `new_here_vocab` + `carrying_forward`. The projector no longer emits it.)

WHY A PROJECTOR, not hand-SVGs: the book-map drifted once already on a Part rename (its own header records
a forced manual rebuild after Modeling/Alignment swapped). A projector over `_PART_TITLES` cannot drift — a
renumber/rename re-projects. This is the book's own IR-projection thesis turned on its navigation art.

Every emitted SVG carries an AUTO-GEN provenance header (a hand-edit is meant to be caught + re-projected)
and a `<!-- semantic-families: neutral -->` budget marker (these are orientation art, not role-coloured
figures). Stdlib-only, clone-and-run, like `catalog.py`.

    python3 book-models/nav_map_model.py            # re-project all 6 subway SVGs into book/assets/
    python3 book-models/nav_map_model.py --check     # drift check: fail (exit 1) if any on-disk SVG differs
"""
from __future__ import annotations

import argparse
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
_ASSETS = os.path.join(_ROOT, "book", "assets")
_MODEL = os.path.join(_HERE, "nav-model.json")
_BOOK = os.path.join(_ROOT, "book")
if _BOOK not in sys.path:
    sys.path.insert(0, _BOOK)
import build_book as bbh  # noqa: E402 — the renderer owns _PART_TITLES, the Part-sequence SSOT

# House palette (design-tokens.json): ink text, muted-neutral stroke, hairline rule, paper fill. These are
# the neutral / supporting colours only — nav maps declare `semantic-families: neutral` and use no role hue.
_INK = "#1c1917"
_MUTED = "#57534e"
_RULE = "#cfcabf"
_PAPER = "#fdfcf9"

_W = 1000  # viewBox width = the design-system figure reference width, so font-sizes render 1:1.

_AUTOGEN = ("AUTO-GENERATED by book-models/nav_map_model.py — do NOT hand-edit; re-project with "
            "`python3 book-models/nav_map_model.py`. Source: book-models/nav-model.json + "
            "build_book._PART_TITLES.")


def _load_model() -> dict:
    with open(_MODEL, encoding="utf-8") as fh:
        return json.load(fh)["parts"]


def _part_nums() -> "list[int]":
    """The numbered Parts in order, from the book's Part-sequence SSOT (front matter and unnumbered
    matter — e.g. the Interlude between Parts 3 and 4 — excluded; only the numbered Parts are stations)."""
    return [n for n in sorted(bbh._PART_TITLES) if n != 0 and n <= 7 and n not in bbh._MATTER_PARTS]


def _esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _header(label: str, view_h: int) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- {_AUTOGEN} -->\n"
        f"<!-- Generated nav map (label: {label}). Orientation art, not a role-coloured figure. -->\n"
        "<!-- semantic-families: neutral -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {_W} {view_h}" '
        f'font-family="Georgia, \'Times New Roman\', serif" role="img" '
        f'aria-label="{_esc(label)}">\n'
        f'  <rect x="0" y="0" width="{_W}" height="{view_h}" fill="{_PAPER}"/>\n'
    )


def _station_xs(n: int, x0: int = 95, x1: int = 905) -> "list[float]":
    if n == 1:
        return [(x0 + x1) / 2]
    return [x0 + i * (x1 - x0) / (n - 1) for i in range(n)]


def _stations_svg(labels: "list[str]", y: float, active_idx: "int | None",
                  active_size: int = 24, base_size: int = 19) -> str:
    """A connected row of labeled stations — the shared transit-map primitive for both map families. The
    active station (if any) renders as a filled disc + bold ink label; the rest as hollow discs + muted
    labels. The connecting line runs behind the discs."""
    xs = _station_xs(len(labels))
    parts: "list[str]" = []
    parts.append(f'  <line x1="{xs[0]:.1f}" y1="{y}" x2="{xs[-1]:.1f}" y2="{y}" '
                 f'stroke="{_RULE}" stroke-width="3"/>')
    for i, (x, lab) in enumerate(zip(xs, labels)):
        is_active = (i == active_idx)
        r = 15 if is_active else 9
        fill = _INK if is_active else _PAPER
        stroke = _INK if is_active else _MUTED
        parts.append(f'  <circle cx="{x:.1f}" cy="{y}" r="{r}" fill="{fill}" '
                     f'stroke="{stroke}" stroke-width="3"/>')
        color = _INK if is_active else _MUTED
        weight = "bold" if is_active else "normal"
        size = active_size if is_active else base_size
        parts.append(f'  <text x="{x:.1f}" y="{y + r + size + 6:.1f}" text-anchor="middle" '
                     f'font-size="{size}" font-weight="{weight}" fill="{color}">{_esc(lab)}</text>')
    return "\n".join(parts) + "\n"


def render_subway(active_part: int, model: dict) -> str:
    """The book-level subway map with `active_part`'s station highlighted."""
    nums = _part_nums()
    labels = [model[str(n)]["subway_label"] for n in nums]
    active_idx = nums.index(active_part)
    title = bbh._PART_TITLES.get(active_part, f"Part {active_part}")
    view_h = 180
    out = _header(f"nav-subway-p{active_part}", view_h)
    out += (f'  <text x="95" y="42" font-size="17" fill="{_MUTED}">Where am I in the book?</text>\n')
    out += (f'  <text x="905" y="42" text-anchor="end" font-size="17" font-weight="bold" '
            f'fill="{_INK}">Part {active_part} · {_esc(title)}</text>\n')
    out += _stations_svg(labels, 100, active_idx)
    out += "</svg>\n"
    return out


def _targets(model: dict) -> "dict[str, str]":
    """{asset_path: svg_text} for all 6 subway nav maps — the projection surface `regenerate` + `--check`
    share."""
    out: "dict[str, str]" = {}
    for n in _part_nums():
        out[os.path.join(_ASSETS, f"nav-subway-p{n}.svg")] = render_subway(n, model)
    return out


def regenerate() -> int:
    model = _load_model()
    targets = _targets(model)
    for path, svg in sorted(targets.items()):
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(svg)
    print(f"re-projected {len(targets)} subway nav SVGs into {os.path.relpath(_ASSETS, _ROOT)}/")
    return 0


def check() -> int:
    model = _load_model()
    drift: "list[str]" = []
    for path, svg in sorted(_targets(model).items()):
        on_disk = ""
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                on_disk = fh.read()
        if on_disk != svg:
            drift.append(os.path.relpath(path, _ROOT))
    if drift:
        print(f"nav-map DRIFT — {len(drift)} SVG(s) differ from the projection; re-run "
              f"`python3 book-models/nav_map_model.py`:")
        for d in drift:
            print(f"    {d}")
        return 1
    print(f"nav-map: {len(_targets(model))} SVGs in sync with nav-model.json + _PART_TITLES")
    return 0


def main(argv: "list[str] | None" = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="drift-check instead of regenerating (exit 1 on drift)")
    args = ap.parse_args(argv)
    return check() if args.check else regenerate()


if __name__ == "__main__":
    raise SystemExit(main())
