"""The LEARNING-OUTCOMES view — a typed model of what a reader should be able to DO or KNOW after each
unit of the book, and which unit teaches which outcome. The book's 6th 4+1-style view (DESIGN §2.6).

Kruchten has no analogue: this is a book-specific PEDAGOGICAL view (the book is a textbook, so it is
modeled as one). Quality question: does every teaching unit — book, Part, chapter, and the sampled
sections — declare what a reader should be able to do after it, does that outcome map to a real unit, and
does the Part→chapter→section outcome tree decompose without gaps?

An OUTCOME is an ACTION VERB + OBJECT — "distinguish a constraint from a sensor," "size a transformation to
the model and the guarantee" — pinned to a Bloom cognitive level and to the outline unit that develops it.

THREE-WAY PROVENANCE — honest labeling is the load-bearing rule.  Every outcome carries a `provenance` tag
that says how honestly it reflects the prose AS WRITTEN:
  - `derived`         — grounded in what the unit ACTUALLY teaches, traceable to an anchor (a topic sentence
                        or heading). The "what the book teaches as written" set.
  - `declared`        — a real outcome the existing (sometimes thin) prose roughly supports, made explicit
                        by the author (e.g. a chapter outcome synthesized across its section titles).
  - `gap-recommended` — the outcome a MISSING or inadequately-delivered unit OUGHT to deliver; a
                        recommendation for content that does NOT yet exist. Never masqueraded as derived.
`derived` candidates are lifted mechanically by `_derive_section_candidates()` from verb-led topic sentences;
`declared` and `gap-recommended` outcomes are hand-authored in `outcomes_declared.json` with an `anchor`
(for declared, the grounding prose) or a gap note (for gap-recommended, why the unit falls short). The
declared + gap-recommended sets ARE the author's rearrange/fill worklist. The regen merges: a hand-authored
declaration wins on the units it names; a mechanically-derived candidate fills a section left silent.

NO NEW MARKDOWN SYMBOL.  Outcomes live in this model's `outcomes.json`, keyed by outline section ids — the
renderer stays uncoupled (DESIGN §2.6 "notation decision"). An inline `<!-- outcome: … -->` marker is
*proposed* in DESIGN §3.3 but deliberately NOT wired into the renderer's marker vocabulary here.

Run `python3 book-models/outcomes_model.py regenerate` to write the artifact; `... verify` to drift-check;
`... gaps` to list units with no outcome (the author's rearrange/fill worklist).
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import book_symbols as bs  # noqa: E402 — sibling helper; read-only symbol-extraction over book_ir
import outline_model as om  # noqa: E402 — the outline view is the unit tree outcomes map onto

_ARTIFACT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outcomes.json")
_DECLARED = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outcomes_declared.json")
_PROVENANCE = ("GENERATED by book-models/outcomes_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/outcomes_model.py regenerate`. Derived from the book (topic sentences) "
               "+ declared outcomes in book-models/outcomes_declared.json.")

# ---- the verb taxonomy ------------------------------------------------------------------------------
# A CLOSED set of teaching verbs, grouped by Bloom cognitive level (2001 revision). The set is tuned to
# THIS book's pedagogy — a governance / MBSE / AI-first-engineering textbook whose outcomes run from
# "recognize a mechanism" through "design a control." An outcome's verb MUST be in this set (checked as
# invariant U4), so the vocabulary stays uniform and the Bloom level is derivable from the verb alone.

BLOOM_VERBS: "dict[str, tuple[str, ...]]" = {
    # KNOW — recall / recognize a named thing exists.
    "know": ("recall", "recognize", "name", "list", "define", "identify"),
    # UNDERSTAND — explain it in your own words; tell two things apart.
    "understand": ("explain", "describe", "distinguish", "summarize", "interpret", "restate", "relate"),
    # APPLY — carry the move out on a new case.
    "apply": ("apply", "use", "compute", "write", "run", "route", "instantiate", "adopt"),
    # ANALYZE — take a situation apart; place it on an axis.
    "analyze": ("analyze", "classify", "map", "trace", "compare", "diagnose", "situate", "decompose"),
    # EVALUATE — judge; size a decision; choose among options.
    "evaluate": ("evaluate", "judge", "size", "critique", "justify", "choose", "weigh", "assess"),
    # CREATE — build a new artifact of the taught kind.
    "create": ("design", "construct", "author", "compose", "derive", "build", "model", "generate", "package"),
}
_VERB_TO_BLOOM: "dict[str, str]" = {v: b for b, vs in BLOOM_VERBS.items() for v in vs}
_ALL_VERBS: frozenset = frozenset(_VERB_TO_BLOOM)

#: The four unit granularities the outcome tree decomposes through (book → Part → chapter → section).
GRANULARITIES = ("book", "part", "chapter", "section")

#: The three honesty tags an outcome carries — how faithfully it reflects the prose as written.
#:   derived         → the book teaches it as written (mechanically lifted or anchored to real prose).
#:   declared        → thin prose roughly supports it; the author makes it explicit.
#:   gap-recommended → the outcome a MISSING / inadequate unit ought to deliver (content not yet written).
PROVENANCE_TAGS = ("derived", "declared", "gap-recommended")

#: The PEDAGOGICAL TIERS the outcome spine presents through — the flat outcomes read as a course
#: structure. Module = Part, Lesson = chapter: the SAME unit keys the outcomes already carry (no prose is
#: re-authored), relabeled into a hierarchy. The whole-book (book-level) outcomes sit ABOVE the modules as
#: the PROGRAM tier — they span every module, so they are not forced under any one of them; section
#: outcomes nest under their Lesson. A pure presentation relabel of `granularity`, so it cannot say
#: anything the outcomes do not already carry.
TIERS = ("program", "module", "lesson", "outcome")
_TIER_OF_GRANULARITY = {"book": "program", "part": "module", "chapter": "lesson", "section": "outcome"}

#: Module titles, keyed by Part number — the one fact the unit keys do not carry (they key on numeric part
#: / chapter slug). Canonical HERE so the reviewable digest and the models reading-view read ONE source
#: (the reading-view reads these titles back out of the emitted `hierarchy`, not a second hand-kept copy).
#: Part 0 is front matter (preface / acknowledgments) — not a teaching Module, so it is omitted from the
#: module tier (matching the coverage invariants, which already skip it).
#: These MUST agree, on every shared Part number, with `build_book._PART_TITLES` (the reader-facing
#: SSOT the running-heads/openers render from) — a rule-#33 parity lint holds the two in step
#: (check_part_title_parity, AUDIT-ONLY-first).
PART_TITLES = {
    0: "Front Matter",
    1: "The New Engineering Problem",
    2: "Modeling",
    3: "Alignment",
    4: "The MAGE Method",
    5: "The Evidence",
    6: "The Theory",
    7: "The Profession",
    8: "Conclusion",
}

#: Renumber-safe PART key surrogate. The outcomes DECLARED source keys each part record by a stable LABEL
#: (`part:<slug-of-title>`), NOT the part NUMBER — so a Part renumber cannot transpose two records, the bug
#: this determinizes away: `part-2` / `part-3` went stale after Modeling and Alignment swapped position, so
#: the Modeling capability sat under `part-3` and the Alignment one under `part-2`. The number is DERIVED
#: HERE from `PART_TITLES` (held in parity with `build_book._PART_TITLES` by check_part_title_parity)
#: at load time, so a rename/renumber re-binds a label to its current number automatically — one source of
#: truth for "which Part." `chapter_identity` is already label-keyed for the same reason; this brings the
#: part outcomes into line. Every downstream consumer (U-gates, the tiered view, the site projection) still
#: sees the resolved `part-<N>`, so only this one seam changes.
_PART_LABEL_TO_NUM: "dict[str, int]" = {bs.slugify(title): n for n, title in PART_TITLES.items() if n != 0}


def _resolve_part_key(unit_id: str) -> str:
    """Map a renumber-safe part LABEL key (`part:<slug>`) to the current `part-<N>` the rest of the model
    and every projection speak. A non-label key (chapter slug / section id / `book` / an already-numeric
    `part-N`) passes through unchanged. Fails loud on a `part:` label naming no current Part — the
    determinize's structural guarantee: a stale label can never silently resolve to the WRONG number; it
    resolves to the right one or errors."""
    if not unit_id.startswith("part:"):
        return unit_id
    slug = unit_id.removeprefix("part:")
    n = _PART_LABEL_TO_NUM.get(slug)
    if n is None:
        raise SystemExit(f"outcomes: part label {unit_id!r} names no current Part — "
                         f"known labels: {sorted(_PART_LABEL_TO_NUM)}")
    return f"part-{n}"


# ---- typed model ------------------------------------------------------------------------------------

@dataclass
class Outcome:
    """One learning outcome: an action verb + object, pinned to a PRIMARY unit (where it is chiefly taught)
    plus any ELABORATIVE units (that reinforce, extend, or apply it), and a Bloom level.

    An outcome maps ONE-primary-to-MANY-elaborative, not one-to-one. `primary_unit` and each of
    `secondary_units` is a JOIN KEY into the outline's unit space:
      - granularity "section" → an outline `section_id`.
      - granularity "chapter" → an outline chapter `slug`.
      - granularity "part"    → `part-<N>`.
      - granularity "book"    → `book`.

    COVERAGE SEMANTICS: primary drives coverage. A unit "covers" an outcome only when it is that outcome's
    PRIMARY. Appearing in `secondary_units` reinforces an outcome OWNED ELSEWHERE and does NOT by itself
    make the reinforcing unit covered — a unit that is only ever elaborative is still a coverage GAP.
    """
    outcome_id: str          # stable id: "<primary_unit>::<verb>-<slug-of-object>"
    granularity: str         # granularity of the PRIMARY unit: book | part | chapter | section
    primary_unit: str        # the outline unit that chiefly teaches this outcome (drives coverage)
    secondary_units: list[str]  # elaborative units that reinforce/extend/apply it (do NOT drive coverage)
    verb: str                # a teaching verb from BLOOM_VERBS
    obj: str                 # the object the verb acts on ("a constraint from a sensor")
    statement: str           # the full outcome sentence a reader reads
    bloom: str               # derived from the verb (know|understand|apply|analyze|evaluate|create)
    provenance: str          # derived | declared | gap-recommended (PROVENANCE_TAGS — honesty tag)
    anchor: "str | None" = None           # the grounding prose (topic sentence / heading) for a derived/declared outcome
    gap_note: "str | None" = None          # for gap-recommended: why the unit is missing/inadequate


@dataclass
class OutcomeModel:
    outcomes: list[Outcome]

    def by_primary(self) -> "dict[str, list[Outcome]]":
        """unit → outcomes it PRIMARILY teaches (the coverage-driving map)."""
        d: "dict[str, list[Outcome]]" = {}
        for o in self.outcomes:
            d.setdefault(o.primary_unit, []).append(o)
        return d

    def elaborated_by(self) -> "dict[str, list[Outcome]]":
        """unit → outcomes it ELABORATES (reinforces but does not own). Informational, not coverage."""
        d: "dict[str, list[Outcome]]" = {}
        for o in self.outcomes:
            for u in o.secondary_units:
                d.setdefault(u, []).append(o)
        return d


# ---- derivation: lift candidate outcomes from verb-led topic sentences ------------------------------

#: A topic sentence whose FIRST word is a teaching verb is a free candidate outcome: the section opens by
#: telling the reader to DO the taught thing. Kept HIGH-PRECISION on purpose (honesty over coverage): we
#: accept only an opener that is literally a taxonomy verb, plus a SHORT allow-list of trustworthy
#: inflections. We deliberately EXCLUDE navigational imperatives — "Start at the decision on the left",
#: "Start coarse and refine", "Read the stack as …" — because those instruct the READER's path through the
#: page, not a learning outcome. Lifting them would manufacture a garbled outcome masquerading as derived,
#: exactly the dishonesty the three-way provenance tags exist to prevent. When in doubt, do NOT derive —
#: leave the section a gap the author fills with a declaration.
_INFLECTION_LEMMA: "dict[str, str]" = {
    # opener form → taxonomy VERB (each RHS must be a member of some BLOOM_VERBS group).
    "measure": "compute",
}

#: Openers that LOOK like verbs but instruct navigation / reading, not a learning outcome — never derived.
_NAVIGATIONAL_OPENERS = frozenset({"start", "give", "read", "go", "look", "step", "slide", "turn"})


def _lemma_for_opener(word: str) -> "str | None":
    """Map a topic-sentence opening word to a taxonomy verb, or None if it is not a teaching verb (or is a
    navigational imperative we refuse to derive from)."""
    w = word.lower().strip(".,:;\"'*")
    if w in _NAVIGATIONAL_OPENERS:
        return None
    if w in _ALL_VERBS:
        return w
    return _INFLECTION_LEMMA.get(w)


def _derive_section_candidates() -> "list[Outcome]":
    """Lift a CANDIDATE section outcome from every section whose topic sentence opens on a teaching verb.
    A cheap, structural signal — the imperative opener IS a stated outcome ("Name both ends before you
    move." → apply: name both ends of a brownfield move). Declared outcomes override these per unit."""
    outline = om.derive_outline()
    out: "list[Outcome]" = []
    for _c, s in outline.sections():
        if not s.topic_sentence:
            continue
        first = s.topic_sentence.split()[0] if s.topic_sentence.split() else ""
        lemma = _lemma_for_opener(first)
        if lemma is None:
            continue
        obj = _trim_object(s.topic_sentence)
        out.append(_mk_outcome(
            granularity="section", primary_unit=s.section_id, secondary_units=[], verb=lemma, obj=obj,
            statement=f"After this section, the reader can {lemma} {obj}.",
            provenance="derived", anchor=f"ts: {s.topic_sentence[:90]}"))
    return out


def _trim_object(sentence: str) -> str:
    """A coarse object phrase for a derived outcome — the topic sentence minus its opening verb, clipped to
    a readable length. This is a candidate the author refines into a declaration; it need not be perfect."""
    words = sentence.split()
    tail = " ".join(words[1:]).rstrip(".")
    return (tail[:70].rsplit(" ", 1)[0] + " …") if len(tail) > 72 else tail


# ---- declared outcomes: authored, keyed by outline unit ids -----------------------------------------

def _slug_object(obj: str) -> str:
    return bs.slugify(obj)[:40].strip("-") or "outcome"


def _mk_outcome(*, granularity: str, primary_unit: str, secondary_units: "list[str]", verb: str, obj: str,
                statement: str, provenance: str, anchor: "str | None" = None,
                gap_note: "str | None" = None) -> Outcome:
    if verb not in _ALL_VERBS:
        raise ValueError(f"verb {verb!r} not in the outcome taxonomy (BLOOM_VERBS)")
    if provenance not in PROVENANCE_TAGS:
        raise ValueError(f"provenance {provenance!r} not in {PROVENANCE_TAGS}")
    if primary_unit in secondary_units:
        raise ValueError(f"primary_unit {primary_unit!r} also listed as a secondary/elaborative unit")
    return Outcome(
        outcome_id=f"{primary_unit}::{verb}-{_slug_object(obj)}",
        granularity=granularity, primary_unit=primary_unit, secondary_units=list(secondary_units),
        verb=verb, obj=obj, statement=statement, bloom=_VERB_TO_BLOOM[verb], provenance=provenance,
        anchor=anchor, gap_note=gap_note)


def _load_declared() -> "list[dict]":
    """The authored outcome declarations — a flat list of
    {granularity, primary_unit, secondary_units?, verb, obj, statement?, provenance, anchor?, gap_note?}."""
    with open(_DECLARED, encoding="utf-8") as fh:
        return json.load(fh)["declarations"]


def _declared_outcomes() -> "list[Outcome]":
    """The hand-authored outcomes — `declared` (thin prose supports) and `gap-recommended` (content the unit
    ought to deliver but does not yet). NOTE: a hand-authored outcome may also be tagged `derived` when it is
    tightly anchored to a real heading/topic sentence — the tag reflects honesty, not who typed it."""
    out: "list[Outcome]" = []
    for d in _load_declared():
        verb, obj = d["verb"], d["obj"]
        statement = d.get("statement") or f"After this unit, the reader can {verb} {obj}."
        # Resolve the renumber-safe part LABEL surrogate → the current `part-<N>` before constructing the
        # Outcome, so everything downstream (outcome_id, U-gates, tiered view, site projection) speaks the
        # numeric key unchanged. A non-part key passes through untouched.
        primary = _resolve_part_key(d["primary_unit"])
        secondary = [_resolve_part_key(u) for u in d.get("secondary_units", [])]
        out.append(_mk_outcome(granularity=d["granularity"], primary_unit=primary,
                               secondary_units=secondary, verb=verb, obj=obj,
                               statement=statement, provenance=d.get("provenance", "declared"),
                               anchor=d.get("anchor"), gap_note=d.get("gap_note")))
    return out


# ---- merge: a declared outcome wins on its primary unit; a derived candidate fills a silent section -----

def derive_model() -> OutcomeModel:
    """Build the full outcome model: declared outcomes, plus derived section candidates for every section
    that is not already some declaration's PRIMARY unit. The single derivation regen + drift check share."""
    declared = _declared_outcomes()
    declared_primaries = {o.primary_unit for o in declared}
    derived = [o for o in _derive_section_candidates() if o.primary_unit not in declared_primaries]
    # Stable order: by granularity tier, then primary_unit, then verb, then obj — deterministic artifact.
    tier = {g: i for i, g in enumerate(GRANULARITIES)}
    both = declared + derived
    both.sort(key=lambda o: (tier[o.granularity], o.primary_unit, o.verb, o.obj))
    return OutcomeModel(outcomes=both)


# ---- the Module → Lesson → outcome hierarchy (derived presentation of the flat spine) ----------------

def tiered_view(model: OutcomeModel) -> dict:
    """Present the flat outcome spine as a Module → Lesson → outcome COURSE STRUCTURE. Module = Part,
    Lesson = chapter — the unit keys the outcomes already carry, grouped by the outline's
    part → chapter → section containment. The whole-book outcomes form the PROGRAM tier above the modules;
    each Module carries its own part-level outcome(s) and its Lessons; each Lesson carries its own
    chapter-level outcome(s) plus the section outcomes nested beneath it.

    DERIVED, not authored: every id here is an `outcome_id` already in `model.outcomes`, placed by its
    `primary_unit`. No prose is written, so the hierarchy cannot drift from the outcomes it groups — it
    re-derives from the same source (invariant U8 asserts it partitions the outcomes exactly once). Part 0
    (front matter) is not a teaching Module and is omitted."""
    outline = om.derive_outline()
    by_primary = model.by_primary()
    chapters_in_part: "dict[int, list[str]]" = {}
    sections_in_chapter: "dict[str, list[str]]" = {}
    for c in outline.chapters:
        chapters_in_part.setdefault(c.part, []).append(c.slug)
        sections_in_chapter[c.slug] = [s.section_id for s in c.sections]

    def ids_for(unit: str) -> "list[str]":
        return [o.outcome_id for o in by_primary.get(unit, [])]

    modules: "list[dict]" = []
    for part in sorted(p for p in chapters_in_part if p != 0):
        lessons = [{
            "lesson": slug,
            "own_outcomes": ids_for(slug),
            "section_outcomes": [oid for sid in sections_in_chapter[slug] for oid in ids_for(sid)],
        } for slug in chapters_in_part[part]]
        modules.append({
            "module": f"part-{part}",
            "number": part,
            "title": PART_TITLES.get(part, f"Part {part}"),
            "own_outcomes": ids_for(f"part-{part}"),
            "lessons": lessons,
        })
    return {
        "tiers": list(TIERS),
        "program": {"unit": "book", "own_outcomes": ids_for("book")},
        "modules": modules,
    }


# ---- invariants (walked by the drift check in tests/book_models.py) ---------------------------------

def _unit_resolves(unit_id: str, section_ids: "set[str]", chapter_slugs: "set[str]",
                   parts: "set[int]") -> bool:
    """True when a unit id names a real outline unit at ANY granularity (section id / chapter slug /
    part-N / book). Used for both primary and secondary/elaborative units."""
    if unit_id == "book":
        return True
    if unit_id.startswith("part-"):
        n = unit_id.removeprefix("part-")
        return n.isdigit() and int(n) in parts
    return unit_id in chapter_slugs or unit_id in section_ids


def coverage_findings(model: OutcomeModel) -> "list[str]":
    """The coverage / drift invariants (U1–U7). Each finding is a GAP SIGNAL the author uses to rearrange
    content and fill pedagogy holes — this is the view's product, not just a lint.

    COVERAGE SEMANTICS — PRIMARY DRIVES COVERAGE. A unit covers an outcome only when it is that outcome's
    PRIMARY. A purely elaborative (secondary) reference reinforces an outcome owned elsewhere and does NOT
    make the reinforcing unit covered — so a unit that only ever appears as an elaborative is still a gap.

    U1 — every outcome's PRIMARY unit resolves to a real outline unit (section id / chapter slug / part-N / book).
    U2 — every verb is in the taxonomy (BLOOM_VERBS); bloom equals the verb's level.
    U3 — every chapter is the PRIMARY of ≥1 outcome (directly, or via a section it owns) — else a pedagogy gap.
    U4 — every Part is the PRIMARY of ≥1 part-level outcome — else a pedagogy gap.
    U5 — the book is the PRIMARY of ≥1 book-level outcome.
    U6 — every outcome's provenance is a valid tag; a `derived`/`declared` outcome cites an anchor and a
         `gap-recommended` one cites a gap note (honest-labeling discipline).
    U7 — every ELABORATIVE (secondary) unit resolves to a real outline unit, and is not the primary itself.
    U8 — the Module → Lesson hierarchy PARTITIONS the outcomes: every outcome is placed exactly once
         (program / a Module's own / a Lesson's own / a Lesson's section) — a drop or double-placement means
         the tiering silently disagrees with the flat spine.
    Section-level gaps are reported by `section_gap_findings` (informational, not a U-invariant, since not
    every section must primarily deliver its own outcome — the author decides which do)."""
    import chapter_identity_model as chapter_identity  # noqa: E402 — sibling book-model

    def _lab(slug: str) -> str:
        return chapter_identity.label_for_slug(slug) or slug

    outline = om.derive_outline()
    section_ids = {s.section_id for _c, s in outline.sections()}
    # Chapter units are referenced by number-free identity LABEL now; resolve against the union of outline
    # slugs and labels (permissive, half-migration-safe). The label-scoped backstop is the precision net.
    chapter_slugs = {c.slug for c in outline.chapters} | chapter_identity.labels()
    parts = {c.part for c in outline.chapters}

    findings: "list[str]" = []
    for o in model.outcomes:
        # U1 — the PRIMARY unit resolves, at the declared granularity.
        if o.granularity == "section" and o.primary_unit not in section_ids:
            findings.append(f"U1 outcome {o.outcome_id!r} primary maps to unknown section id {o.primary_unit!r}")
        elif o.granularity == "chapter" and o.primary_unit not in chapter_slugs:
            findings.append(f"U1 outcome {o.outcome_id!r} primary maps to unknown chapter slug {o.primary_unit!r}")
        elif o.granularity == "part":
            n = o.primary_unit.removeprefix("part-")
            if not (n.isdigit() and int(n) in parts):
                findings.append(f"U1 outcome {o.outcome_id!r} primary maps to unknown part {o.primary_unit!r}")
        elif o.granularity == "book" and o.primary_unit != "book":
            findings.append(f"U1 book outcome {o.outcome_id!r} has non-'book' primary {o.primary_unit!r}")
        # U2 — verb + bloom consistency.
        if o.verb not in _ALL_VERBS:
            findings.append(f"U2 outcome {o.outcome_id!r} uses non-taxonomy verb {o.verb!r}")
        elif o.bloom != _VERB_TO_BLOOM[o.verb]:
            findings.append(f"U2 outcome {o.outcome_id!r} bloom {o.bloom!r} ≠ verb level "
                            f"{_VERB_TO_BLOOM[o.verb]!r}")
        # U6 — provenance honesty: valid tag + the right grounding for its tag.
        if o.provenance not in PROVENANCE_TAGS:
            findings.append(f"U6 outcome {o.outcome_id!r} has invalid provenance {o.provenance!r}")
        elif o.provenance in ("derived", "declared") and not o.anchor:
            findings.append(f"U6 outcome {o.outcome_id!r} is {o.provenance} but cites no anchor "
                            f"(a derived/declared outcome must name its grounding prose)")
        elif o.provenance == "gap-recommended" and not o.gap_note:
            findings.append(f"U6 outcome {o.outcome_id!r} is gap-recommended but cites no gap_note "
                            f"(a recommended outcome must name why the unit falls short)")
        # U7 — every elaborative unit resolves and is distinct from the primary.
        for u in o.secondary_units:
            if u == o.primary_unit:
                findings.append(f"U7 outcome {o.outcome_id!r} lists its primary {u!r} as an elaborative unit")
            elif not _unit_resolves(u, section_ids, chapter_slugs, parts):
                findings.append(f"U7 outcome {o.outcome_id!r} elaborative unit {u!r} resolves to no outline unit")

    # PRIMARY drives coverage — only primary_unit counts a unit as covered.
    primary = model.by_primary()
    # covered_chapters is keyed by LABEL (a chapter primary is a label; a section primary maps to its
    # chapter's label), so U3 compares each chapter's label — not its numbered slug.
    section_to_chapter = {s.section_id: _lab(c.slug) for c in outline.chapters for s in c.sections}
    # U3 — every chapter is primary of ≥1 outcome (directly, or via a section it owns as that section's primary).
    covered_chapters = {u for u in primary if u in chapter_slugs}
    covered_chapters |= {section_to_chapter[u] for u in primary if u in section_to_chapter}
    for c in outline.chapters:
        if c.part == 0:
            continue  # front/back matter (preface, acknowledgments) — not a taught chapter
        if _lab(c.slug) not in covered_chapters:
            findings.append(f"U3 chapter {c.slug!r} (part {c.part}) is no outcome's PRIMARY — pedagogy gap")
    # U4 — every taught Part is primary of ≥1 part-level outcome.
    covered_parts = {int(u.removeprefix("part-")) for u in primary if u.startswith("part-")}
    for p in sorted(parts):
        if p == 0:
            continue
        if p not in covered_parts:
            findings.append(f"U4 part {p} is no outcome's PRIMARY — pedagogy gap")
    # U5 — the book is primary of ≥1 book-level outcome.
    if "book" not in primary:
        findings.append("U5 the book is no outcome's PRIMARY — pedagogy gap")

    # U8 — the Module/Lesson hierarchy partitions the outcomes exactly once.
    h = tiered_view(model)
    placed: "list[str]" = list(h["program"]["own_outcomes"])
    for m in h["modules"]:
        placed += m["own_outcomes"]
        for les in m["lessons"]:
            placed += les["own_outcomes"] + les["section_outcomes"]
    seen: "set[str]" = set()
    dups = sorted({i for i in placed if i in seen or seen.add(i)})  # add(i) returns None → falsy
    all_ids = {o.outcome_id for o in model.outcomes}
    missing = sorted(all_ids - set(placed))
    unknown = sorted(set(placed) - all_ids)
    if dups:
        findings.append(f"U8 hierarchy places {len(dups)} outcome(s) under more than one Module/Lesson: "
                        f"{dups[:3]}")
    if missing:
        findings.append(f"U8 hierarchy omits {len(missing)} outcome(s) from every Module/Lesson: "
                        f"{missing[:3]}")
    if unknown:
        findings.append(f"U8 hierarchy places {len(unknown)} id(s) that are no known outcome: {unknown[:3]}")
    return findings


def section_gap_findings(model: OutcomeModel) -> "list[str]":
    """INFORMATIONAL: sections that are no outcome's PRIMARY. The author's fill worklist — a section that
    teaches something but primarily delivers no outcome is a candidate for a declaration (or for merging
    away). A section that ONLY reinforces an outcome owned elsewhere (elaborative) still counts as a gap
    here — primary drives coverage — but we annotate it so the author can see it already earns its keep as
    an elaboration."""
    outline = om.derive_outline()
    primary_units = set(model.by_primary())
    elaborated = model.elaborated_by()
    gaps: "list[str]" = []
    for c in outline.chapters:
        if c.part == 0:
            continue
        for s in c.sections:
            if s.section_id not in primary_units:
                ts = (s.topic_sentence or "(no topic sentence)")[:60]
                elab = (f" | elaborates {len(elaborated[s.section_id])} outcome(s)"
                        if s.section_id in elaborated else "")
                gaps.append(f"[{c.slug}] section {s.section_id!r} (L{s.level}) — no PRIMARY outcome{elab} | ts: {ts}")
    return gaps


# ---- capability-quality: the part-binding transposition catcher (AUDIT-ONLY, rule #55) --------------
#: The 260810 finding: `outcomes_declared.json`'s part-2/part-3 records went stale after Modeling and
#: Alignment swapped position — the KEY (a part number) drifted from the CONTENT (the capability
#: statement). The DETERMINIZE (label keys + derive-number, above) makes the KEY impossible to transpose.
#: This lint is the FUZZY backstop the determinize cannot supply: it catches a right-key / WRONG-statement
#: drift — a `part:modeling` record whose statement is about governance, not models. Two rungs, both
#: reported AUDIT-ONLY (the whole U-gate family is audit-only; a follow-up may promote the structural rung).

_PB_STOPWORDS = frozenset(
    "the a an of to and or for in on at by with from into as is are be can each its it this that these "
    "those one not how which what why who does do reader after part their they them you your may must "
    "through over under about across between while when where then than so but also only more most".split())


def _pb_tokens(text: str) -> "set[str]":
    """Coarse content tokens for the fuzzy overlap check: lowercase alphabetic words ≥4 chars, minus a
    small stopword set. No stemming — the overlap test below matches on a shared 4-char prefix, which
    absorbs 'model' / 'models' / 'modeling' without a fragile stemmer."""
    import re  # local: a tiny self-contained tokenizer used only by this audit-only lint
    return {w for w in re.findall(r"[a-z]+", text.lower()) if len(w) >= 4 and w not in _PB_STOPWORDS}


def _pb_overlap(statement_tokens: "set[str]", expected_tokens: "set[str]") -> int:
    """Count expected tokens that share a ≥4-char prefix with some statement token (prefix match absorbs
    plural/gerund morphology: 'modeling' ~ 'model')."""
    hits = 0
    for e in expected_tokens:
        if any(s[:4] == e[:4] for s in statement_tokens):
            hits += 1
    return hits


def _expected_part_tokens(part_num: int, outline) -> "set[str]":
    """The vocabulary a Part-N outcome statement should touch: the Part TITLE words plus the words of the
    chapter slugs the outline places in Part N (stripping the numeric `N.M-` prefix). Derived from the
    live outline + PART_TITLES, so it tracks a renumber/rename with no hand-kept list."""
    toks = _pb_tokens(PART_TITLES.get(part_num, ""))
    for c in outline.chapters:
        if c.part != part_num:
            continue
        stem = c.slug.split("-", 1)[1] if "-" in c.slug and c.slug.split("-", 1)[0].replace(".", "").isdigit() else c.slug
        toks |= _pb_tokens(stem.replace("-", " "))
    return toks


def part_binding_findings() -> "list[str]":
    """AUDIT-ONLY capability-quality checks over the DECLARED part records — the transposition catcher the
    stale part-2/part-3 binding demanded (the audit's U9 sketch had count/uniqueness but MISSED this one).

      U9pb-struct (DETERMINISTIC) — every `part` record keys by a `part:<label>` surrogate resolving to
        exactly one current Part number. A bare numeric `part-<N>` key (the renumber-fragile form) or an
        unresolvable label is a finding.
      U9pb-parity (FUZZY) — the record's statement+object must OVERLAP the resolved Part's expected
        vocabulary (title + chapter-slug words). Zero overlap flags a right-key / wrong-statement drift
        (a Modeling statement mis-filed under Alignment, or vice versa).

    Reads the declared file directly, so it sees the label surrogate the load-time resolver erases."""
    outline = om.derive_outline()
    findings: "list[str]" = []
    for d in _load_declared():
        if d.get("granularity") != "part":
            continue
        key = d["primary_unit"]
        # U9pb-struct — the key must be a resolvable label surrogate, never a bare number.
        if not key.startswith("part:"):
            findings.append(f"U9pb-struct part record {key!r} uses a renumber-fragile numeric key — "
                            f"re-key to the `part:<label>` surrogate (the transposition determinize)")
            continue
        slug = key.removeprefix("part:")
        num = _PART_LABEL_TO_NUM.get(slug)
        if num is None:
            findings.append(f"U9pb-struct part label {key!r} names no current Part "
                            f"(known: {sorted(_PART_LABEL_TO_NUM)})")
            continue
        # U9pb-parity — the statement must talk about THIS Part's subject.
        stmt_tokens = _pb_tokens(f"{d.get('statement', '')} {d.get('obj', '')}")
        expected = _expected_part_tokens(num, outline)
        if _pb_overlap(stmt_tokens, expected) == 0:
            findings.append(f"U9pb-parity part {key!r} (→ part-{num} {PART_TITLES.get(num)!r}) statement "
                            f"shares NO vocabulary with the Part's title/chapters — possible mis-binding")
    return findings


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(model: OutcomeModel) -> dict:
    outline = om.derive_outline()
    n_sections = len(outline.sections())
    # PRIMARY drives coverage: a section counts as covered only when it is some outcome's primary.
    primary_sections = {o.primary_unit for o in model.outcomes if o.granularity == "section"}
    elaborated_units = set(model.elaborated_by())
    hierarchy = tiered_view(model)
    return {
        "_provenance": _PROVENANCE,
        "_counts": {
            "outcomes": len(model.outcomes),
            "by_provenance": {p: sum(1 for o in model.outcomes if o.provenance == p)
                              for p in PROVENANCE_TAGS},
            "by_granularity": {g: sum(1 for o in model.outcomes if o.granularity == g)
                               for g in GRANULARITIES},
            "by_tier": {t: sum(1 for o in model.outcomes
                               if _TIER_OF_GRANULARITY.get(o.granularity) == t) for t in TIERS},
            "by_bloom": {b: sum(1 for o in model.outcomes if o.bloom == b) for b in BLOOM_VERBS},
            "outcomes_with_elaborative_units": sum(1 for o in model.outcomes if o.secondary_units),
            "elaborative_links": sum(len(o.secondary_units) for o in model.outcomes),
            "units_serving_as_elaborative": len(elaborated_units),
            "sections_total": n_sections,
            "sections_primary_of_an_outcome": len(primary_sections),
            "modules": len(hierarchy["modules"]),
            "lessons": sum(len(m["lessons"]) for m in hierarchy["modules"]),
        },
        "taxonomy": {b: list(vs) for b, vs in BLOOM_VERBS.items()},
        # The Module → Lesson → outcome course structure — a derived presentation of the flat spine below
        # (Module = Part, Lesson = chapter). See `tiered_view`. Every id here also appears in `outcomes`.
        "hierarchy": hierarchy,
        "outcomes": [asdict(o) for o in model.outcomes],
    }


def regenerate() -> int:
    model = derive_model()
    payload = to_jsonable(model)
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['outcomes']} outcomes "
          f"(by provenance {c['by_provenance']}); "
          f"by tier {c['by_tier']} across {c['modules']} modules / {c['lessons']} lessons; "
          f"{c['outcomes_with_elaborative_units']} with elaborative units "
          f"({c['elaborative_links']} links); "
          f"{c['sections_primary_of_an_outcome']}/{c['sections_total']} sections are a primary")
    write_digest(model)
    cov = coverage_findings(model)
    if cov:
        print(f"  {len(cov)} coverage finding(s) (audit-only — see tests/book_models.py):")
        for f in cov:
            print(f"    {f}")
    pb = part_binding_findings()
    if pb:
        print(f"  {len(pb)} part-binding finding(s) (audit-only — capability-quality U9pb):")
        for f in pb:
            print(f"    {f}")
    return 0


_DIGEST = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outcomes-draft.md")


def _pretty_unit(unit_id: str) -> str:
    """A short, reader-facing unit label for the digest: 'part-2' → 'Module 2', a chapter slug → its
    number prefix ('2.3', the Lesson id), a section id → its slug. Chapter/section ids already read well;
    keep them terse."""
    if unit_id == "book":
        return "the program"
    if unit_id.startswith("part-"):
        return f"Module {unit_id.removeprefix('part-')}"
    # A chapter slug like '2.3-the-governed-environment' → '2.3'; a section id stays as-is.
    head = unit_id.split("-", 1)[0]
    return head if head.replace(".", "").isdigit() else unit_id


def write_digest(model: OutcomeModel) -> None:
    """Emit a human-readable, reviewable digest of the actual outcome STATEMENTS, organized by PRIMARY unit
    (book → Part → chapter → section), each tagged with its provenance (derived | declared | gap-recommended),
    its anchor, and — when it spans more than one unit — its primary + elaborative units shown distinctly
    ("primary: 2.3 · elaborated by: 4.5, 6.0"). This is the surface the author reviews."""
    outline = om.derive_outline()
    chapters_in_part: "dict[int, list[str]]" = {}
    for c in outline.chapters:
        chapters_in_part.setdefault(c.part, []).append(c.slug)
    by_primary = model.by_primary()
    elaborated = model.elaborated_by()

    tag = {"derived": "DERIVED", "declared": "DECLARED", "gap-recommended": "GAP-REC"}
    lines: "list[str]" = [
        "<!-- GENERATED by book-models/outcomes_model.py — reviewable digest of the outcomes view.",
        "     Do not hand-edit; edit book-models/outcomes_declared.json and regenerate. -->",
        "# Learning outcomes — reviewable draft\n",
        "The outcomes read as a **Module → Lesson → outcome** course structure: **Module = Part**, "
        "**Lesson = chapter** (the unit keys the outcomes already carry). The whole-book outcomes form the "
        "**Program** tier above the modules.\n",
        "Every outcome has a **PRIMARY** unit (where it is chiefly taught — this drives coverage) and may "
        "list **elaborative** units that reinforce, extend, or apply it. Primary drives coverage: a unit "
        "that only ever appears as an elaborative is still a gap.\n",
        "Each outcome is also tagged by how honestly it reflects the prose **as written**:",
        "- **DERIVED** — grounded in what the primary unit actually teaches (traceable to its anchor).",
        "- **DECLARED** — a real outcome the existing (thin) prose roughly supports, made explicit.",
        "- **GAP-REC** — the outcome a *missing / inadequate* unit ought to deliver (content not yet written).\n",
        "The DECLARED + GAP-REC sets are the rearrange/fill worklist. The DERIVED set is what the book "
        "teaches today.\n",
    ]

    def emit(o: "Outcome", indent: str) -> None:
        note = f" — _anchor: {o.anchor}_" if o.anchor else ""
        if o.gap_note:
            note = f" — _gap: {o.gap_note}_"
        span = ""
        if o.secondary_units:
            elab = ", ".join(_pretty_unit(u) for u in o.secondary_units)
            span = f" _(primary: {_pretty_unit(o.primary_unit)} · elaborated by: {elab})_"
        lines.append(f"{indent}- **[{tag[o.provenance]}]** ({o.bloom}) {o.statement}{span}{note}")

    def emit_elaborations(unit_id: str, indent: str) -> None:
        """Show, under a unit, the outcomes it ELABORATES but does not own (owned elsewhere)."""
        for o in elaborated.get(unit_id, []):
            lines.append(f"{indent}- _elaborates (owned by {_pretty_unit(o.primary_unit)}):_ "
                         f"({o.bloom}) {o.statement}")

    # Program level (the whole-book outcomes, above the modules).
    lines.append("## Program — across the whole book\n")
    for o in by_primary.get("book", []):
        emit(o, "")
    emit_elaborations("book", "")
    lines.append("")

    for part in sorted(p for p in chapters_in_part if p != 0):
        lines.append(f"## Module {part} — {PART_TITLES.get(part, f'Part {part}')}\n")
        for o in by_primary.get(f"part-{part}", []):
            emit(o, "")
        emit_elaborations(f"part-{part}", "")
        lines.append("")
        for slug in chapters_in_part[part]:
            lines.append(f"### Lesson {slug}\n")
            for o in by_primary.get(slug, []):
                emit(o, "")
            emit_elaborations(slug, "")
            # Section-level outcomes under this chapter, in section order.
            for u in [s.section_id for c in outline.chapters if c.slug == slug for s in c.sections]:
                for o in by_primary.get(u, []):
                    emit(o, "  ")
                emit_elaborations(u, "  ")
            lines.append("")

    with open(_DIGEST, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")
    print(f"wrote {os.path.relpath(_DIGEST)} — reviewable outcome digest")


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """Drift check as a CLI: assert the on-disk artifact equals a fresh derivation."""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable(derive_model())
    if (stored.get("outcomes") != fresh["outcomes"] or stored.get("_counts") != fresh["_counts"]
            or stored.get("hierarchy") != fresh["hierarchy"]):
        print("DRIFT: outcomes.json disagrees with a fresh derivation — regenerate")
        return 1
    print(f"outcomes.json is in sync ({fresh['_counts']['outcomes']} outcomes)")
    return 0


def gaps() -> int:
    """List the pedagogy gaps under the PRIMARY-drives-coverage rule — chapters/parts/book that are no
    outcome's primary (U3/U4/U5), and sections that are no outcome's primary (annotated when they at least
    serve as an elaboration). The author's rearrange/fill worklist."""
    model = derive_model()
    cov = coverage_findings(model)
    sec = section_gap_findings(model)
    print(f"UNIT gaps (U1–U7): {len(cov)}")
    for f in cov:
        print(f"  {f}")
    print(f"\nSECTION gaps — sections that primarily deliver no outcome (informational): {len(sec)}")
    for f in sec:
        print(f"  {f}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "regenerate"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "gaps":
        return gaps()
    print(f"usage: {argv[0]} [regenerate|verify|gaps]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
