"""The PROJECTION metamodel — book vs website as distinct rendered projections of the book models.

WHY IT EXISTS.  A cross-cutting concept edit (rename Churn, reframe Compounding) must land in every place
the concept renders — on the book AND the website, not just the chapters. No single model named those
sites: `definitions.json` carries one `site_home` slot (all `"N/A"`), `landing-big-ideas.json` knows only
the six landing cards, `metaphor-spans.json` is book-only, and `reverse_index.json` inverts book VIEWS
(outline/outcomes/claims), never the website HTML. The heaviest surfaces (a chapter with 50+ occurrences,
the figures gallery) were grep-only. This model closes that gap.

TWO FILES, mirroring the reverse-index discipline (authored config + derived inversion):
  - `projections.json` — AUTHORED. Names each projection, its kind (book|website), and the built-output
    glob it owns. The small hand truth of "what surfaces exist."
  - `projection-index.json` — DERIVED. For each tracked concept slug, the projections + sites its rendered
    form appears in, scanned from the BUILT HTML per projections.json. Re-derived each run, so it cannot
    drift — the same regenerate/verify freshness discipline `reverse_index.py` uses.

WHAT IS REUSED (A.10 — reuse, don't copy).  `reverse_index.py` inverts in-memory VIEW-models, not built
HTML, so it exposes no HTML-scan helper to call; nothing to duplicate there. This module instead:
  - reuses `catalog.site_prune_dirs()` — the SINGLE source of truth for "which built .html is a served
    surface" (the same prune `tests.common.html_files` / the orphan gate use), so the surface universe
    cannot drift from the site walk;
  - mirrors reverse_index's `to_jsonable` / `load_artifact` / `verify` freshness shape verbatim (the repo's
    canonical derived-model pattern) — the FRESHNESS gate reuses that pattern, not a new one;
  - reads the existing join-key SSOTs (`definitions.json._order`, `landing-big-ideas.json`,
    `metaphor-spans.json` slugs) for the tracked-slug universe — no new naming.

The scan is a whole-word / whole-phrase match of the concept term within each projection's glob, with CSS
custom-property tokens (`--diagram-<slug>` and every other `--var`) stripped first so a per-page palette
token never counts as prose. Hyphen-joined anchor forms (`bi-churn`, `--diagram-churn`) are excluded by the
word boundary. This is discoverability for cross-cutting edits, not a precise concept classifier: over-
reporting (the English word "churn" in a catalogue entry) is the safe direction for "where must I edit?".

Run `python3 book-models/projections_model.py regenerate` to write the index; `... verify` to freshness-
check; `... where <slug>` to answer "where does concept X render, book vs website?"; `... completeness`
and `... site-home` for the two sync gates.
"""
from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import catalog  # noqa: E402 — reuse site_prune_dirs(): the SINGLE source of truth for "the served surface"

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)  # the governance-catalog repo root (book-models/ is one level down)
_REGISTRY = os.path.join(_HERE, "projections.json")
_ARTIFACT = os.path.join(_HERE, "projection-index.json")

_PROVENANCE = ("GENERATED by book-models/projections_model.py — do not hand-edit; regenerate with "
               "`python3 book-models/projections_model.py regenerate`. A DERIVED inversion: for each "
               "tracked concept slug, the projections + built sites its rendered form appears in, scanned "
               "from the built HTML per projections.json. Re-derived each run, so it cannot itself drift.")

#: Every `--var` custom-property token (CSS var name / value ref) — stripped before the word scan so a
#: per-page palette token (`--diagram-churn`, `--diagram-churn-fill`) is never counted as prose.
_CSS_VAR = re.compile(r"--[a-z][a-z0-9-]*")


# ---- the authored registry --------------------------------------------------------------------------

def load_registry() -> "list[dict]":
    """The authored projection records from projections.json (each: id, kind, builder, globs)."""
    raw = json.load(open(_REGISTRY, encoding="utf-8"))
    return raw["projections"]


def _glob_to_re(pat: str) -> "re.Pattern[str]":
    """A shell-glob → regex over repo-relative paths. `**` spans directories; `*` stays within one
    segment; `?` is one char. Matched against the served-surface rel paths."""
    p = re.escape(pat).replace(r"\*\*", ".*").replace(r"\*", "[^/]*").replace(r"\?", ".")
    return re.compile(p + r"\Z")


# ---- the served-surface universe (reused from catalog, single source of truth) ----------------------

def served_html_surfaces() -> "list[str]":
    """Every built page that is part of the served site, as repo-relative paths: the catalogue's .html
    (reusing `catalog.site_prune_dirs()` so that half is identical to the orphan gate / axe walk) PLUS
    the book's emitted `book/web/docs/*.md` page bodies — the book's served surface since the C3
    publish swap (each body is the rendered HTML that ships at /book/mage-book/<stem>.html). This is
    the set the completeness gate holds to 'claimed by exactly one projection.'"""
    prune = catalog.site_prune_dirs()
    out: "list[str]" = []
    for dirpath, dirnames, filenames in os.walk(_ROOT):
        dirnames[:] = [d for d in dirnames if d not in prune]
        for fn in filenames:
            if fn.endswith(".html"):
                out.append(os.path.relpath(os.path.join(dirpath, fn), _ROOT))
    docs = os.path.join(_ROOT, "book", "web", "docs")
    if os.path.isdir(docs):
        out.extend(f"book/web/docs/{fn}" for fn in os.listdir(docs) if fn.endswith(".md"))
    return sorted(out)


def _resolve_projection(projection: dict, surfaces: "list[str]") -> "list[str]":
    """The served surfaces a projection's globs claim (html projections only). book-pdf is derived (its
    glob is a .pdf, absent from `surfaces`), so it returns []."""
    pats = [_glob_to_re(g) for g in projection["globs"]]
    return [s for s in surfaces if any(p.match(s) for p in pats)]


# ---- the tracked-slug universe (reused join keys) ---------------------------------------------------

def _order(d: dict) -> "list[str]":
    return [k for k in d.get("_order", []) if not k.startswith("_")]


def tracked_terms() -> "dict[str, str]":
    """`{slug: search-term}` for every tracked concept — the join keys the other book models already use:
    definitions (`_order`), landing big-ideas (`_order`), and metaphor spans (`slug`). The search term is
    the slug with hyphens as spaces (`governance-mechanism` -> `governance mechanism`), the form the term
    renders as in prose. Generic taxonomy words in concepts.json (constraint / sensor / gate) are NOT
    tracked — as bare words they appear on nearly every page and would swamp the index with noise; the
    named-vocabulary sources above are the discoverability-useful join keys."""
    slugs: "set[str]" = set()
    defs = json.load(open(os.path.join(_ROOT, "book", "data", "definitions.json"), encoding="utf-8"))
    slugs.update(_order(defs))
    ideas = json.load(open(os.path.join(_HERE, "landing-big-ideas.json"), encoding="utf-8"))
    slugs.update(_order(ideas))
    spans = json.load(open(os.path.join(_HERE, "metaphor-spans.json"), encoding="utf-8"))
    slugs.update(m["slug"] for m in spans.get("metaphors", []) if m.get("slug"))
    return {s: s.replace("-", " ") for s in sorted(slugs)}


def _count(text: str, term: str) -> int:
    """Whole-word / whole-phrase occurrences of `term` in `text`, CSS-var tokens stripped first. The
    boundary `(?<![\\w-])…(?![\\w-])` excludes hyphen-joined forms (a `bi-churn` anchor, a leftover
    `--diagram-churn`), so only substantive prose uses count."""
    stripped = _CSS_VAR.sub(" ", text)
    return len(re.findall(r"(?<![\w-])" + re.escape(term) + r"(?![\w-])", stripped, re.I))


# ---- the derived inversion --------------------------------------------------------------------------

def build_index() -> "dict[str, dict]":
    """Invert the built HTML into `{slug -> {kind -> {projection_id -> [{file, occ}]}}}`. Each website /
    book-web projection is scanned file-by-file for each tracked term; book-pdf is the DERIVED twin — the
    single PDF is one site whenever the concept appears in any book-web page (same chapter sources)."""
    surfaces = served_html_surfaces()
    terms = tracked_terms()
    projections = load_registry()
    # Pre-read each served file once (scanned against every term).
    text_of: "dict[str, str]" = {}
    for rel in surfaces:
        text_of[rel] = open(os.path.join(_ROOT, rel), encoding="utf-8").read()

    index: "dict[str, dict]" = {}
    pdf_projection = next((p for p in projections if p.get("derived_twin_of")), None)
    for slug, term in terms.items():
        by_kind: "dict[str, dict]" = {}
        for proj in projections:
            if proj.get("derived_twin_of"):
                continue  # book-pdf handled below (derived from its twin)
            sites: "list[dict]" = []
            for rel in _resolve_projection(proj, surfaces):
                n = _count(text_of[rel], term)
                if n:
                    sites.append({"file": rel, "occ": n})
            if sites:
                sites.sort(key=lambda s: s["file"])
                by_kind.setdefault(proj["kind"], {})[proj["id"]] = sites
        # DERIVED book-pdf twin: one site (the PDF) iff the concept appears in its twin projection.
        if pdf_projection is not None:
            twin_sites = by_kind.get(pdf_projection["kind"], {}).get(pdf_projection["derived_twin_of"], [])
            if twin_sites:
                pdf_file = pdf_projection["globs"][0]
                by_kind.setdefault(pdf_projection["kind"], {})[pdf_projection["id"]] = [
                    {"file": pdf_file, "occ": len(twin_sites)}]
        if by_kind:
            index[slug] = by_kind
    return index


def _site_totals(entry: dict) -> "dict[str, int]":
    """`{kind: number-of-sites}` for one slug's index entry (sites summed across the kind's projections)."""
    return {kind: sum(len(sites) for sites in projs.values()) for kind, projs in entry.items()}


def to_jsonable(index: "dict[str, dict] | None" = None) -> dict:
    if index is None:
        index = build_index()
    by_projection: "dict[str, int]" = {}
    total_sites = 0
    for entry in index.values():
        for projs in entry.values():
            for pid, sites in projs.items():
                by_projection[pid] = by_projection.get(pid, 0) + len(sites)
                total_sites += len(sites)
    return {
        "_provenance": _PROVENANCE,
        "_counts": {
            "tracked_slugs": len(tracked_terms()),
            "slugs_rendered": len(index),
            "total_sites": total_sites,
            "by_projection": dict(sorted(by_projection.items())),
        },
        # slug -> {kind -> {projection_id -> [{file, occ}]}}, keys sorted for a stable diff.
        "index": {k: index[k] for k in sorted(index)},
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['slugs_rendered']}/{c['tracked_slugs']} tracked slugs "
          f"render across {c['total_sites']} site(s); by projection {c['by_projection']}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


# ---- the sync gates ---------------------------------------------------------------------------------

def freshness_findings() -> "list[str]":
    """FRESHNESS — the on-disk index equals a fresh re-derivation from the built HTML. A page edited /
    rebuilt without regenerating the index is the finding. Same shape as reverse_index.verify()."""
    stored = load_artifact()
    if stored is None:
        return [f"{os.path.relpath(_ARTIFACT)} missing — run "
                f"`python3 book-models/projections_model.py regenerate`"]
    fresh = to_jsonable()
    if stored.get("index") != fresh["index"] or stored.get("_counts") != fresh["_counts"]:
        return [f"DRIFT: {os.path.relpath(_ARTIFACT)} disagrees with a fresh scan of the built HTML — "
                f"regenerate with `python3 book-models/projections_model.py regenerate`"]
    return []


def completeness_findings(surfaces: "list[str] | None" = None) -> "list[str]":
    """COMPLETENESS / JOIN — two directions:
      (a) every served HTML surface is claimed by EXACTLY ONE projections.json record (no orphan surface,
          no double-claim) — so a new page can't render outside the projection model;
      (b) every site in the projection index resolves to a real built file.
    book-pdf is derived + binary, so it is exempt from (a) and its PDF site is exempt from (b)."""
    if surfaces is None:
        surfaces = served_html_surfaces()
    projections = load_registry()
    html_projections = [p for p in projections if not p.get("derived_twin_of")]
    findings: "list[str]" = []

    # (a) exactly-one-claim over the served surface universe.
    claims: "dict[str, list[str]]" = {}
    for proj in html_projections:
        for rel in _resolve_projection(proj, surfaces):
            claims.setdefault(rel, []).append(proj["id"])
    for rel in surfaces:
        owners = claims.get(rel, [])
        if not owners:
            findings.append(f"completeness: served surface {rel!r} is claimed by NO projections.json "
                            f"record (an orphan surface — add a glob that claims it)")
        elif len(owners) > 1:
            findings.append(f"completeness: served surface {rel!r} is claimed by {len(owners)} records "
                            f"{owners} — a surface must belong to exactly one projection")

    # (b) every index site is a real file (skip the derived PDF twin — gitignored + binary).
    pdf_ids = {p["id"] for p in projections if p.get("derived_twin_of")}
    for slug, entry in (load_artifact() or {}).get("index", {}).items():
        for kind, projs in entry.items():
            for pid, sites in projs.items():
                if pid in pdf_ids:
                    continue
                for site in sites:
                    if not os.path.isfile(os.path.join(_ROOT, site["file"])):
                        findings.append(f"completeness: index site {site['file']!r} (slug {slug!r}, "
                                        f"projection {pid}) is not a real built file")
    return findings


def site_home_findings() -> "list[str]":
    """SITE-HOME RECONCILE — the stale `definitions.json.site_home` catch the design flagged. Every core
    definition currently declares `site_home: "N/A"` (no site projection), yet the projection index shows
    some of those concepts DO render on a website projection (Churn: a landing Big-Idea card + a dedicated
    concept page). A record whose concept the index places on the website but whose `site_home` is `"N/A"`
    is a contradiction: the definition is modeled book-only while the concept plainly projects to the site.

    Reports the contradiction; it does NOT flip the raw `site_home` value, because that slot doubles as the
    landing def-strip anchor id (the renderer skips `"N/A"` records) — flipping it would re-introduce the
    on-landing definitions strip a prior commit deliberately removed and break the def-strip drift check.
    The reconciliation the design ratified is this parity lint (its option b), landed audit-only-first.

    The website signal is the UNAMBIGUOUS one the design used for Churn: a dedicated concept ENTRY page
    (`concept-<slug>.html`). A bare foundational word (`model`, `agent`) occurs on nearly every page, so
    incidental prose hits are NOT a projection of the definition — only a slug's own concept page is."""
    defs = json.load(open(os.path.join(_ROOT, "book", "data", "definitions.json"), encoding="utf-8"))
    index = (load_artifact() or {}).get("index", {})
    findings: "list[str]" = []
    for slug in _order(defs):
        rec = defs.get(slug, {})
        site_home = rec.get("site_home")
        if site_home != "N/A":
            continue
        concept_sites = index.get(slug, {}).get("website", {}).get("website-concepts", [])
        entry_page = f"concept-{slug}.html"
        if any(s["file"] == entry_page for s in concept_sites):
            findings.append(f"site-home: {slug!r} has a dedicated website concept page {entry_page!r} but "
                            f"definitions.json site_home is \"N/A\" — the definition is modeled book-only "
                            f"while the concept projects to the site (reconcile per the projection index)")
    return findings


# ---- query surface ----------------------------------------------------------------------------------

def where(slug: str) -> int:
    """Answer "where does concept X render, book vs website?" — the per-projection site list for `slug`,
    read from the derived index (regenerate first if stale)."""
    entry = (load_artifact() or {}).get("index", {}).get(slug)
    if entry is None:
        terms = tracked_terms()
        if slug in terms:
            print(f"{slug!r}: tracked, but renders on no projection today (or the index is stale — "
                  f"`python3 book-models/projections_model.py regenerate`)")
        else:
            print(f"{slug!r}: not a tracked concept slug. Tracked: {', '.join(sorted(terms))}")
        return 0
    totals = _site_totals(entry)
    parts = []
    for kind in ("book", "website"):
        if kind in totals:
            per = " + ".join(f"{pid} x{len(sites)}" for pid, sites in sorted(entry[kind].items()))
            parts.append(f"{kind.upper()}: {totals[kind]} sites ({per})")
    print(f"{slug} — " + " · ".join(parts))
    for kind in ("website", "book"):
        for pid, sites in sorted(entry.get(kind, {}).items()):
            files = ", ".join(f"{s['file']} ({s['occ']})" for s in sites)
            print(f"  {kind.upper():8} {pid:20} {files}")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "regenerate"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        findings = freshness_findings()
        if findings:
            for f in findings:
                print(f)
            return 1
        print(f"projection-index.json is in sync ({(load_artifact() or {}).get('_counts', {})})")
        return 0
    if cmd == "completeness":
        findings = completeness_findings()
        for f in findings:
            print(f)
        print(f"{len(findings)} completeness finding(s)")
        return 1 if findings else 0
    if cmd == "site-home":
        findings = site_home_findings()
        for f in findings:
            print(f)
        print(f"{len(findings)} site-home reconciliation finding(s) (audit-only)")
        return 0
    if cmd == "where":
        if len(argv) < 3:
            print(f"usage: {argv[0]} where <concept-slug>")
            return 2
        return where(argv[2])
    print(f"usage: {argv[0]} [regenerate|verify|completeness|site-home|where <slug>]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
