#!/usr/bin/env python3
"""render_models_view.py — the book models, rendered as a browsable HTML reading view.

The book is modeled as typed views in `book-models/` (an outline of the heading tree with a topic
sentence per section, and a learning-outcomes view keyed to book/Part/chapter/section units). Those
models drive the published site as projections. This renderer turns two of them — `outline.json` and
`outcomes.json` — into a single self-contained page, `book-models/models-view.html`: an alternative,
model-derived way to read the book's spine.

    The heading tree     — Part → chapter → section, indented, each section its own anchor.
    The topic sentences  — the opening sentence the outline records for each section, shown inline.
    The learning outcomes — every outcome attached to the unit it belongs to (book at the top; a
                            Part under its opener; a chapter under its heading; a section inline).

WHY read the JSON artifacts, not import the model modules: this stays a thin, decoupled PROJECTION.
The renderer never re-derives the models — it reads the materialized `.json` a sibling regenerates,
exactly as the site's landing projection reads `outcomes.json`. That keeps the freshness contract in
ONE place (the views-audit re-derivation check), and keeps this renderer robust while the model
modules are mid-edit. Stdlib-only, no dependencies (clone-and-run, like `catalog.py`).

Regen discipline: run `python3 book-models/render_models_view.py` (or `regenerate`) to re-emit the
HTML. The repo's `pre-commit` hook runs it on every commit and stages the output, so the committed
page can never drift from the models. The page is TRACKED (not gitignored) — it mirrors how the repo
treats the site HTML: GitHub Pages serves committed HTML, the hook keeps it fresh, CI is the source
of truth on push. A drift check (`check_models_view_*` in tests/html.py, surfaced by
`catalog.py views-audit`) reddens if the committed page falls out of sync with the models.
"""
from __future__ import annotations

import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTLINE_JSON = os.path.join(ROOT, "book-models", "outline.json")
OUTCOMES_JSON = os.path.join(ROOT, "book-models", "outcomes.json")
OUT_HTML = os.path.join(ROOT, "book-models", "models-view.html")

PROVENANCE = ("GENERATED by book-models/render_models_view.py — do not hand-edit; regenerate with "
              "`python3 book-models/render_models_view.py`. Derived from book-models/outline.json + "
              "outcomes.json. The pre-commit hook re-renders + stages this on every commit.")

# Module titles come from the outcomes model's `hierarchy` block (Module = Part; the outcomes model owns
# the canonical Part→title map and emits it into outcomes.json — read it back here, not a second copy).
# Only Part 0 (front matter) is not a Module and has no hierarchy entry, so keep that one label local.
_NON_MODULE_TITLES = {0: "Front Matter", 3.5: "Interlude — One Problem, Many Models"}

_BLOOM_ORDER = ["know", "understand", "apply", "analyze", "evaluate", "create"]


def _esc(s: str) -> str:
    return html.escape(str(s), quote=True)


def _load(path: str) -> dict:
    if not os.path.isfile(path):
        raise SystemExit(f"render_models_view: missing model artifact {path} — regenerate the models first")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def _outcomes_by_unit(outcomes: list[dict]) -> dict[str, list[dict]]:
    """Group outcomes by their `primary_unit` key. book -> 'book'; a Part -> 'part-N'; a chapter ->
    the chapter slug; a section -> the section_id. That is exactly the key each granularity attaches
    to a node in the outline, so the renderer can look up 'what can the reader do here?' per node."""
    by_unit: dict[str, list[dict]] = {}
    for o in outcomes:
        unit = o.get("primary_unit", "")
        if unit:
            by_unit.setdefault(unit, []).append(o)
    # Stable within a unit: order by Bloom level, then by statement.
    for lst in by_unit.values():
        lst.sort(key=lambda o: (_bloom_rank(o.get("bloom", "")), o.get("statement", "")))
    return by_unit


def _bloom_rank(bloom: str) -> int:
    return _BLOOM_ORDER.index(bloom) if bloom in _BLOOM_ORDER else len(_BLOOM_ORDER)


def _outcome_li(o: dict) -> str:
    """One outcome rendered as a list item: a Bloom-verb tag + the statement STRAIGHT FROM the model,
    a provenance tag (declared / derived / gap-recommended), and — for a gap outcome — its author note."""
    bloom = _esc(o.get("bloom", ""))
    stmt = _esc(o.get("statement", ""))
    prov = o.get("provenance", "")
    prov_cls = "prov-gap" if prov == "gap-recommended" else "prov"
    prov_tag = f'<span class="{prov_cls}">{_esc(prov)}</span>' if prov else ""
    gap = o.get("gap_note", "")
    gap_html = f'<span class="gap-note">{_esc(gap)}</span>' if gap else ""
    trail = f" {prov_tag}" if prov_tag else ""
    return (f'<li class="oc"><span class="bloom bloom-{bloom}">{bloom or "—"}</span>'
            f'<span class="oc-text">{stmt}{trail}{gap_html}</span></li>')


def _outcome_block(outcomes: list[dict], scope_label: str) -> str:
    if not outcomes:
        return ""
    items = "".join(_outcome_li(o) for o in outcomes)
    return (f'<div class="outcomes"><div class="oc-h">{_esc(scope_label)} — the reader can</div>'
            f'<ul class="oc-list">{items}</ul></div>')


def _id_safe(s: str) -> str:
    """Sanitize a value into an HTML id (letters, digits, dash, underscore only). Chapter slugs carry
    dots (`6.0-implications-…`); a raw dot is an invalid id char, so map every non-word run to a dash."""
    return re.sub(r"[^A-Za-z0-9_-]+", "-", s).strip("-")


def _section_id_anchor(chapter_slug: str, section_id: str) -> str:
    return _id_safe(f"sec-{chapter_slug}--{section_id}")


def render_html() -> str:
    outline = _load(OUTLINE_JSON)
    outcomes_model = _load(OUTCOMES_JSON)
    outcomes = outcomes_model.get("outcomes", [])
    by_unit = _outcomes_by_unit(outcomes)

    chapters = outline.get("chapters", [])
    ocounts = outline.get("_counts", {})
    ncounts = outcomes_model.get("_counts", {})
    # Module titles from the outcomes model's Module → Lesson hierarchy (Module = Part). One source: the
    # renderer reads them back out of outcomes.json rather than keeping a second copy of the Part→title map.
    module_titles = {m.get("number"): m.get("title", "") for m in
                     outcomes_model.get("hierarchy", {}).get("modules", [])}

    # Group chapters by part, preserving order.
    parts: list[tuple[int, list[dict]]] = []
    seen_order: list[int] = []
    part_map: dict[int, list[dict]] = {}
    for ch in chapters:
        p = ch.get("part", 0)
        if p not in part_map:
            part_map[p] = []
            seen_order.append(p)
        part_map[p].append(ch)
    parts = [(p, part_map[p]) for p in seen_order]

    out: list[str] = []
    out.append("<!DOCTYPE html>")
    out.append('<html lang="en">')
    out.append("<head>")
    out.append('<meta charset="utf-8">')
    out.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    out.append(f"<!-- {_esc(PROVENANCE)} -->")
    out.append("<title>The book models — reading view</title>")
    out.append(f"<style>{_CSS}</style>")
    out.append("</head>")
    out.append('<body class="models-view">')
    out.append("<main>")

    # Header + navigation back to the site.
    out.append('<nav class="crumb" aria-label="Breadcrumb"><a href="../index.html">← Catalogue landing</a> · '
               '<a href="../book/index.html">The book</a></nav>')
    out.append("<h1>The book models — a reading view</h1>")
    out.append('<p class="subtitle">The book\'s outline and learning-outcome models, rendered as an '
               'alternative way to read the spine. Every heading, topic sentence, and outcome below is '
               'projected straight from <code>book-models/outline.json</code> and '
               '<code>outcomes.json</code> — regenerated on every commit, so it never goes stale.</p>')
    out.append(
        '<p class="counts">'
        f'<b>{len(chapters)}</b> chapters · <b>{ocounts.get("sections", 0)}</b> sections · '
        f'<b>{len(outcomes)}</b> learning outcomes '
        f'({ncounts.get("declared", "?")} declared · {ncounts.get("derived", "?")} derived · '
        f'{ncounts.get("gap-recommended", "?")} gap-recommended)</p>')

    # The book reads as a Module → Lesson → outcome course: Module = Part, Lesson = chapter. The
    # whole-book outcomes are the PROGRAM tier, above the modules.
    def _part_title(p: int) -> str:
        # Matter parts (front matter, the Interlude) are not course Modules — their title is authoritative
        # in _NON_MODULE_TITLES, ahead of any placeholder the outcomes hierarchy minted for them.
        if p in _NON_MODULE_TITLES:
            return _NON_MODULE_TITLES[p]
        return module_titles.get(p) or f"Part {p}"

    def _is_module(p) -> bool:
        # A numbered course Module — excludes matter (front matter, the Interlude) even though the outcomes
        # hierarchy lists them, so they render with a bare title rather than a "Module N" kicker.
        return p in module_titles and p not in _NON_MODULE_TITLES

    def _part_anchor(p) -> str:
        # A valid HTML id / fragment. The float part number for the Interlude (3.5) would yield
        # id="part-3.5", whose "." is illegal in an id (html-validate `valid-id`); normalize dot → dash.
        return "part-" + str(p).replace(".", "-")

    # Program-level outcomes at the top — the whole-book "you'll be able to…".
    book_ocs = by_unit.get("book", [])
    if book_ocs:
        out.append('<section class="book-outcomes">')
        out.append("<h2>The program — what you'll be able to do after the whole book</h2>")
        out.append(_outcome_block(book_ocs, "After the program"))
        out.append("</section>")

    # Table of contents — a jump list of Modules.
    toc = []
    for p, _chs in parts:
        label = f"Module {p}" if _is_module(p) else _part_title(p)
        toc.append(f'<a href="#{_part_anchor(p)}">{_esc(label)}</a>')
    out.append('<nav class="toc" aria-label="Modules"><b>Modules:</b> ' + " · ".join(toc) + "</nav>")

    # Per-module rendering.
    for p, chs in parts:
        is_module = _is_module(p)
        title = _part_title(p)
        heading = f"Module {p} — {title}" if is_module else title
        out.append(f'<section class="part" id="{_part_anchor(p)}">')
        out.append(f"<h2>{_esc(heading)}</h2>")
        part_ocs = by_unit.get(f"part-{p}", [])
        if part_ocs:
            scope = f"Module {p}" if is_module else ("the front matter" if p == 0 else title)
            out.append(_outcome_block(part_ocs, f"After {scope}"))
        for ch in chs:
            out.append(_render_chapter(ch, by_unit, is_lesson=is_module))
        out.append("</section>")

    out.append('<footer class="mv-foot">Projected from the book models · '
               '<a href="../index.html">catalogue</a> · '
               '<a href="../book/index.html">book</a>. Regenerated on every commit.</footer>')
    out.append("</main>")
    out.append("</body></html>")
    return "\n".join(out) + "\n"


def _render_chapter(ch: dict, by_unit: dict[str, list[dict]], is_lesson: bool = True) -> str:
    slug = ch.get("slug", "")
    sections = ch.get("sections", [])
    # A chapter's display heading: prefer an L1 section heading, else the slug. A chapter inside a Module
    # is a Lesson — tag it as one; front-matter chapters (preface / acknowledgments) are not Lessons.
    l1 = next((s for s in sections if s.get("level") == 1), None)
    ch_title = l1.get("heading_text") if l1 else slug
    parts: list[str] = []
    parts.append('<div class="chapter">')
    book_href = f"../book/{slug}.html"
    kick = '<span class="tier-kick">Lesson</span>' if is_lesson else ""
    parts.append(f'<h3 id="{_id_safe("ch-" + slug)}">{kick}<a href="{_esc(book_href)}" class="ch-link">'
                 f'{_esc(ch_title)}</a> <span class="ch-slug">{_esc(slug)}</span></h3>')
    ch_ocs = by_unit.get(slug, [])
    if ch_ocs:
        parts.append(_outcome_block(ch_ocs, "After this lesson" if is_lesson else "After this chapter"))
    # Sections — indent by heading level (L2 flush, L3 nested, L4 deeper).
    for s in sections:
        if l1 is not None and s is l1:
            continue  # the L1 heading became the chapter title; don't repeat it
        level = s.get("level", 2)
        sid = s.get("section_id", "")
        heading = s.get("heading_text", "")
        topic = s.get("topic_sentence", "")
        anchor = _section_id_anchor(slug, sid)
        indent = {2: "s2", 3: "s3", 4: "s4"}.get(level, "s4")
        # Link to the chapter PAGE, not a per-section fragment: the book HTML does not emit heading ids
        # matching the outline's derived section_id, so a `#section_id` fragment would dangle. The
        # per-section id lives HERE (this page is the deep-linkable surface for the model's sections).
        parts.append(f'<div class="section {indent}" id="{_esc(anchor)}">')
        parts.append(f'<div class="sec-h"><a href="{_esc(book_href)}">{_esc(heading)}</a></div>')
        if topic:
            parts.append(f'<p class="topic">{_esc(topic)}</p>')
        else:
            parts.append('<p class="topic no-topic">(no topic sentence — opens on a non-paragraph block)</p>')
        sec_ocs = by_unit.get(sid, [])
        if sec_ocs:
            parts.append(_outcome_block(sec_ocs, "After this section"))
        parts.append("</div>")
    parts.append("</div>")
    return "\n".join(parts)


_CSS = """
  :root { --ink:#1a1a1a; --muted:#555; --accent:#b45309; --line:#e2e8f0; --link:#0b5cad; --tint:#f8fafc; }
  * { box-sizing:border-box; }
  body { margin:0; font-family:"Source Sans 3",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
         color:var(--ink); background:#fff; line-height:1.6; font-size:17px; }
  main { max-width:960px; margin:0 auto; padding:28px 24px 80px; }
  h1 { font-family:"Source Serif 4",Georgia,serif; font-size:32px; margin:6px 0 4px; letter-spacing:-.02em; }
  h2 { font-family:"Source Serif 4",Georgia,serif; font-size:23px; margin:34px 0 8px; padding-top:8px;
       border-top:2px solid var(--accent); }
  h3 { font-family:"Source Serif 4",Georgia,serif; font-size:19px; margin:22px 0 4px; }
  .subtitle { color:#444; font-style:italic; margin:4px 0 8px; font-size:15px; }
  .counts { color:var(--muted); font-size:14px; margin:0 0 10px; }
  .counts b { color:var(--ink); }
  nav.crumb { font-size:13px; color:var(--muted); margin:0 0 14px; }
  nav.crumb a { color:var(--link); text-decoration:underline; text-underline-offset:2px; }
  nav.toc { font-size:14px; background:var(--tint); border:1px solid var(--line); border-radius:8px;
            padding:10px 14px; margin:6px 0 8px; line-height:1.9; }
  nav.toc a { color:var(--link); text-decoration:none; }
  nav.toc a:hover { text-decoration:underline; }
  a { color:var(--link); }
  .ch-link { text-decoration:underline; text-underline-offset:3px; text-decoration-thickness:1px; }
  .ch-link:hover { text-decoration-thickness:2px; }
  .ch-slug { font-size:12px; color:#6b7280; font-weight:400; font-family:"SF Mono",Menlo,monospace; margin-left:6px; }
  .tier-kick { font-family:"Source Sans 3",sans-serif; font-size:10.5px; text-transform:uppercase; letter-spacing:.07em;
               font-weight:800; color:var(--accent); margin-right:7px; vertical-align:2px; }
  .chapter { margin:6px 0 14px; }
  .section { margin:8px 0; padding-left:14px; border-left:2px solid var(--line); }
  .section.s3 { margin-left:18px; }
  .section.s4 { margin-left:36px; }
  .sec-h { font-weight:700; font-size:16px; }
  .sec-h a { color:var(--ink); text-decoration:none; }
  .sec-h a:hover { color:var(--link); text-decoration:underline; }
  .topic { margin:2px 0 4px; color:#333; font-size:15px; }
  .topic.no-topic { color:#b45309; font-style:italic; font-size:13.5px; }
  .outcomes { margin:6px 0 4px; background:var(--tint); border:1px solid var(--line);
              border-radius:7px; padding:8px 12px; }
  .oc-h { font-size:12px; text-transform:uppercase; letter-spacing:.05em; font-weight:800;
          color:var(--accent); margin:0 0 4px; }
  .oc-list { margin:0; padding:0; list-style:none; }
  .oc { display:flex; gap:8px; align-items:baseline; margin:4px 0; font-size:14.5px; }
  /* Badge bg colors use -700/-800 shades so white text clears WCAG AA 4.5:1 at this 10.5px size. */
  .bloom { flex:0 0 auto; font-size:10.5px; text-transform:uppercase; letter-spacing:.04em; font-weight:800;
           color:#fff; background:#475569; border-radius:4px; padding:1px 6px; min-width:64px; text-align:center; }
  .bloom-know{background:#475569;} .bloom-understand{background:#155e75;} .bloom-apply{background:#065f46;}
  .bloom-analyze{background:#6d28d9;} .bloom-evaluate{background:#92400e;} .bloom-create{background:#9f1239;}
  .oc-text { flex:1 1 auto; }
  .prov { font-size:11px; color:#576373; margin-left:4px; }
  .prov-gap { font-size:11px; color:#be123c; font-weight:700; margin-left:4px; }
  .gap-note { display:block; font-size:12.5px; color:#9a3412; font-style:italic; margin-top:2px; }
  .book-outcomes { margin:8px 0 4px; }
  .mv-foot { margin-top:40px; padding-top:14px; border-top:1px solid var(--line); font-size:12.5px;
             color:#666; text-align:center; }
  .mv-foot a { color:var(--link); }
  @media (max-width:640px){ .section.s3,.section.s4 { margin-left:8px; } .bloom { min-width:52px; } }
"""


def regenerate() -> int:
    """Render the page and write it to book-models/models-view.html. Returns 0 on success."""
    html_text = render_html()
    with open(OUT_HTML, "w", encoding="utf-8") as fh:
        fh.write(html_text)
    print(f"render_models_view: wrote {os.path.relpath(OUT_HTML, ROOT)} "
          f"({len(html_text):,} bytes)")
    return 0


def verify() -> int:
    """Exit 1 if the committed HTML differs from a fresh render — the freshness contract, callable as a
    standalone gate. The views-audit surfaces the same signal (audit-only-first)."""
    if not os.path.isfile(OUT_HTML):
        print("render_models_view: models-view.html missing — run `regenerate`")
        return 1
    fresh = render_html()
    with open(OUT_HTML, encoding="utf-8") as fh:
        stored = fh.read()
    if fresh != stored:
        print("render_models_view: models-view.html is STALE — run "
              "`python3 book-models/render_models_view.py regenerate`")
        return 1
    print("render_models_view: models-view.html is fresh")
    return 0


def main(argv: list[str]) -> int:
    cmd = argv[0] if argv else "regenerate"
    if cmd in ("regenerate", "render", ""):
        return regenerate()
    if cmd == "verify":
        return verify()
    print(f"usage: {os.path.basename(__file__)} [regenerate|verify]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
