"""The REVERSE INDEX — a DERIVED projection that inverts every built view's forward references into
`{md symbol → [view elements that depend on it]}`. The drift layer's substrate (DESIGN §4).

WHY IT EXISTS.  The view-models (`outline`, `outcomes`) point FORWARD at md symbols: an outline section
rides a heading anchor / section id; an outcome names the units it teaches (a section id / chapter slug /
part-N / book) and cites a concept-or-heading anchor. Held that way, the question "if I edit section X,
which view elements break?" needs an O(views·elements) re-scan every time. The reverse index inverts the
forward edges ONCE, so the answer is one dict lookup — and the same inverted map is what turns the
structural drift audit into a single walk (does every symbol a view points at still exist in the source?).

DERIVED, NEVER HAND-AUTHORED.  `build_index()` re-inverts the views from the current source on every call.
There is no hand-authored source of truth, so the index itself cannot drift — a stale `reverse_index.json`
is caught by `verify()` (the on-disk artifact must equal a fresh inversion). The artifact carries a
provenance header and is TRACKED (diffable in PRs), mirroring `outline.json` / `outcomes.json`.

TWO SYMBOL ROLES.  A symbol appears in two ways, kept distinct so drift is precise:
  - DEFINED in the source  — the symbol universe: every section id / heading anchor / concept slug / float
    label / ref key / chapter slug / part that the book actually contains. Enumerated from `book_ir` +
    the outline view. A view reference to a symbol NOT in this set is a STRUCTURAL-DRIFT finding (dangling).
  - DEPENDED-ON by a view   — the inverted edge: which view elements point at this symbol. This is the
    reverse index proper; `deps <symbol>` reads it.

Run `python3 book-models/reverse_index.py regenerate` to write the artifact; `... verify` to drift-check;
`... deps <symbol>` to answer "edit this symbol → which view elements break?".
"""
from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import asdict, dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import book_symbols as bs  # noqa: E402 — read-only symbol-extraction over book_ir
import claims_model as clm  # noqa: E402 — the claims view (built) — a source of claim-assertion edges
import outcomes_model as ocm  # noqa: E402 — the outcomes view (built) — a source of forward references
import outline_model as om  # noqa: E402 — the outline view (built) — a source of forward references

_ARTIFACT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reverse_index.json")
_PROVENANCE = ("GENERATED by book-models/reverse_index.py — do not hand-edit; regenerate with "
               "`python3 book-models/reverse_index.py regenerate`. A DERIVED inversion of every built "
               "view's forward references into {md symbol -> [dependent view elements]}; re-derived from "
               "the book (via book_ir + the view-models) each run, so it cannot itself drift.")

#: The `index-def: slug` / `index-example: slug` grammar — a concept anchor's slug lives in the directive's
#: raw comment. Parsed here (the anchor slug is not yet a first-class book_ir field — DESIGN §6.2).
_CONCEPT_DIRECTIVE = re.compile(r"^<!--\s*(index-def|index-example)\s*:\s*([a-z0-9-]+)\s*-->$", re.I)

#: The md symbol kinds the reverse index tracks. Each names a DIFFERENT source construct an edit can touch;
#: keeping them typed (not one flat string set) lets a `deps` answer say WHAT kind of symbol you edited and
#: lets the universe-membership drift check reason per-kind. `point` is the drain-phase symbol: each
#: `<!-- point: <slug> | <claim> [| terms: …] -->` decorator's slug is an authored reference the outline
#: rides. `term` is the two-tier tagging symbol: a slug a point's `terms:` segment (tier-2) or a
#: `<!-- section-terms: … -->` marker (tier-1) names — it inverts into term→point and term→section edges,
#: so "which sections develop term X ∪ which paragraphs use term X" is one lookup.
#: `claim` is the CLAIMS-view symbol: each claim id is an authored symbol (the join key + the deferred inline
#: `<!-- claim: <id> -->` marker's target). The claims view rides the outline at each `asserted_at` site, so
#: its edges are keyed by those SITE symbols (section-id / chapter / part / book) with role `claim-assertion`
#: / `claim-home` — that is how `deps <section>` answers "edit section X → which claims are asserted here?".
SYMBOL_KINDS = ("section-id", "concept", "label", "ref", "chapter", "part", "book", "point", "term", "claim")


# ---- the symbol universe: what the source actually DEFINES -------------------------------------------

@dataclass
class SymbolUniverse:
    """Every md symbol the book currently defines, grouped by kind. The resolve-target set the structural
    drift audit checks a view reference against. Derived fresh from `book_ir` + the outline view."""
    section_ids: "set[str]" = field(default_factory=set)   # outline section ids (explicit {#slug} or derived)
    concepts: "set[str]" = field(default_factory=set)      # <!-- index-def / index-example: slug -->
    labels: "set[str]" = field(default_factory=set)        # <!-- label: key --> float labels
    refs: "set[str]" = field(default_factory=set)          # [ref:key] keys that appear in prose
    chapters: "set[str]" = field(default_factory=set)      # chapter slugs
    parts: "set[int]" = field(default_factory=set)         # part numbers
    points: "set[str]" = field(default_factory=set)        # <!-- point: slug | text --> decorator slugs
    terms: "set[str]" = field(default_factory=set)         # registered term slugs (index-terms.md two-tier registry)
    claims: "set[str]" = field(default_factory=set)        # claim ids (book-models/claims.json) — the claims view's symbols

    def resolves(self, symbol: str, kind: str) -> bool:
        """True when `symbol` is a real DEFINED symbol of the given `kind`. `book` and `part-<N>` are the
        two synthetic unit kinds the outcomes view uses; the rest name concrete source constructs. A `term`
        resolves against the REGISTERED term set (the two-tier registry), NOT the source prose — a tagged
        term that is not registered is the `term-tags-registered` finding."""
        if kind == "book":
            return symbol == "book"
        if kind == "part":
            n = symbol.removeprefix("part-")
            return n.isdigit() and int(n) in self.parts
        return symbol in {
            "section-id": self.section_ids, "concept": self.concepts, "label": self.labels,
            "ref": self.refs, "chapter": self.chapters, "point": self.points, "term": self.terms,
            "claim": self.claims,
        }.get(kind, set())

    def unit_kind(self, unit_id: str) -> str:
        """Classify an OUTCOME unit id (book | part-N | chapter slug | section id) to its symbol kind — the
        kind an outcome's primary/secondary reference resolves against. Matches the outcomes view's own
        `_unit_resolves` granularity order (book, part, chapter, then section)."""
        if unit_id == "book":
            return "book"
        if unit_id.startswith("part-") and unit_id.removeprefix("part-").isdigit():
            return "part"
        if unit_id in self.chapters:
            return "chapter"
        return "section-id"


def point_occurrences() -> "list[tuple[str, str, int]]":
    """Every `<!-- point: <slug> | <text> -->` decorator in the book as (slug, chapter_slug, block_index).
    A list (not a set) so a DUPLICATE slug — two paragraphs induced to the same canonical point, the
    machine version of a redundancy — is visible to the drift audit, not silently deduped."""
    doc = bs.book_ir.parse_book()
    occ: "list[tuple[str, str, int]]" = []
    for c in doc.chapters:
        for b in c.blocks:
            if b.directive == "point" and b.point_slug:
                occ.append((b.point_slug, c.slug, b.index))
    return occ


def term_occurrences() -> "list[tuple[str, str, str, str, int]]":
    """Every tagged-term occurrence in the book as (term_slug, tier, chapter_slug, element_role, block_index).
    Two producers:
      - a `point`'s `terms:` segment → tier-2, role `paragraph-term` (the point's block is the element);
      - a `<!-- section-terms: … -->` marker → tier-1, role `section-term` (the marker's block is the element).
    A list (not a set) so the SAME term tagged at many sites is fully enumerated — the reverse index inverts
    every occurrence into a term→element edge. `tier` here is the tagging tier (point=tier-2, section=tier-1),
    NOT the term's registered tier; the registered tier is looked up separately by the lint."""
    doc = bs.book_ir.parse_book()
    occ: "list[tuple[str, str, str, str, int]]" = []
    for c in doc.chapters:
        for b in c.blocks:
            if b.directive == "point" and b.point_slug:
                for t in b.point_terms:
                    occ.append((t, "tier-2", c.slug, "paragraph-term", b.index))
            elif b.directive == "section-terms":
                for t in b.section_terms:
                    occ.append((t, "tier-1", c.slug, "section-term", b.index))
    return occ


def _registered_terms() -> "dict[str, str]":
    """The two-tier term registry {slug: registered-tier} from `index-terms.md` — the SSOT the term-tag
    resolution joins against. Read via the renderer's `_load_term_tiers` (one loader, no parallel parse)."""
    return bs.bb._load_term_tiers()


def derive_universe() -> SymbolUniverse:
    """Enumerate every symbol the book DEFINES today. Section ids + chapters + parts come from the outline
    view (one structural source, no parallel parse); concepts / labels / refs / points come from `book_ir`;
    terms come from the two-tier registry in `index-terms.md`."""
    import chapter_identity_model as chapter_identity  # noqa: E402 — sibling book-model
    doc = bs.book_ir.parse_book()
    u = SymbolUniverse()
    outline = om.derive_outline()
    for c in outline.chapters:
        u.chapters.add(c.slug)
        u.parts.add(c.part)
        for s in c.sections:
            u.section_ids.add(s.section_id)
    # A chapter is referenced by its number-free identity LABEL (chapter_identity model), so the chapter
    # symbol set includes the labels alongside the outline slugs — a migrated claim/outcome/… chapter ref
    # resolves as a `chapter`, not a dangling section-id. Both are kept so a half-migrated tree resolves.
    u.chapters.update(chapter_identity.labels())
    for c in doc.chapters:
        for b in c.blocks:
            m = _CONCEPT_DIRECTIVE.match(b.raw.strip()) if b.kind is bs.book_ir.BlockKind.DIRECTIVE else None
            if m:
                u.concepts.add(m.group(2))
    u.labels.update(doc.labels())
    u.refs.update(r.key for r in doc.refs())
    u.points.update(slug for slug, _c, _i in point_occurrences())
    u.terms.update(_registered_terms())
    u.claims.update(c.id for c in clm.derive_model().claims)
    return u


# ---- the inverted edges: which view elements DEPEND on each symbol -----------------------------------

@dataclass
class Dependent:
    """One view element that points at a symbol — the reverse edge. `view` names which view (`outline` /
    `outcomes`); `element` is that view's stable element id (a section id, an outcome id); `role` says HOW
    the element uses the symbol (a section that IS this id; an outcome's `primary` / `secondary` unit; an
    outcome's cited `anchor`), so a `deps` answer explains the nature of each break, not just the count."""
    view: str
    element: str
    role: str


def _add(index: "dict[str, dict]", symbol: str, kind: str, dep: Dependent) -> None:
    # The index key is NAMESPACED by kind — `<kind>:<slug>` (DESIGN §10.4). A term slug can equal a
    # section-id slug (e.g. `semantic-gap` the concept vs a `semantic-gap` heading anchor); a bare-slug
    # key would MERGE the two into one slot that then mislabels its `kind` and interleaves term edges with
    # outcome-unit edges. Namespacing keeps each construct a distinct entry, so `kind` is always right and
    # `deps` labels every collided sense correctly. Slugs are kebab / kinds are single lowercase words, so
    # neither carries a `:` — `key.split(":", 1)` recovers `(kind, slug)` unambiguously.
    key = f"{kind}:{symbol}"
    index.setdefault(key, {"kind": kind, "dependents": []})["dependents"].append(asdict(dep))


def build_index() -> "dict[str, dict]":
    """Invert every built view's forward references into `{symbol -> {kind, dependents:[Dependent]}}`.

    Forward edges inverted, per built view:
      - OUTLINE — every section RIDES a `section-id` (its heading anchor or derived id). Editing that
        heading's anchor moves the section's id, so the section depends on the symbol `section-id`.
      - OUTCOMES — every outcome names a `primary_unit` and any `secondary_units` (each a section id /
        chapter slug / part-N / book), and cites an `anchor` string. The unit references are the joins the
        coverage check walks; the anchor is the grounding prose an edit can invalidate. When an anchor
        string contains a concept/heading token we record the tokenized dependency too (best-effort: an
        `anchor` is prose, so we only invert the machine-checkable unit references as hard edges and record
        the anchor text as a soft `anchor` dependency keyed by the primary unit's symbol).
    """
    index: "dict[str, dict]" = {}
    universe = derive_universe()

    # OUTLINE: section rides its own section id.
    outline = om.derive_outline()
    for c in outline.chapters:
        for s in c.sections:
            _add(index, s.section_id, "section-id",
                 Dependent(view="outline", element=f"{c.slug}::{s.section_id}", role="section-anchor"))

    # OUTLINE POINTS: each `<!-- point: slug | text -->` decorator's slug is an authored symbol the outline
    # rides at paragraph granularity. Invert it so "edit/remove this decorator → which paragraph point
    # breaks?" is one lookup, on the same footing as a section id. The element is the chapter::block site.
    for slug, chap, idx in point_occurrences():
        _add(index, slug, "point",
             Dependent(view="outline", element=f"{chap}::block-{idx}", role="paragraph-point"))

    # TERM TAGS: each tagged term is a `term` symbol depended on by the paragraph (tier-2, from a point's
    # `terms:`) or the section (tier-1, from a `<!-- section-terms: … -->`). Inverting both produces the
    # "which sections develop term X ∪ which paragraphs use term X" answer as one `deps <term>` lookup. The
    # role carries the tagging tier so a `deps` answer distinguishes a section-develops from a paragraph-uses.
    for term, tier, chap, role, idx in term_occurrences():
        _add(index, term, "term",
             Dependent(view="outline", element=f"{chap}::block-{idx}", role=f"{role}[{tier}]"))

    # OUTCOMES: primary + secondary units are hard join edges; the anchor is a soft grounding edge.
    model = ocm.derive_model()
    for o in model.outcomes:
        _add(index, o.primary_unit, universe.unit_kind(o.primary_unit),
             Dependent(view="outcomes", element=o.outcome_id, role="primary-unit"))
        for u in o.secondary_units:
            _add(index, u, universe.unit_kind(u),
                 Dependent(view="outcomes", element=o.outcome_id, role="secondary-unit"))

    # CLAIMS: each claim rides the outline at its `home` (chiefly argued) and every `asserted_at` site. Invert
    # both so `deps <section>` answers "edit this unit → which claims are asserted / homed here?" — the claims
    # analogue of the outcomes coverage join (DESIGN §4.1 RI). Keyed by the SITE symbol, like an outcome unit.
    for cl in clm.derive_model().claims:
        # `home` and `asserted_at` share one unit grammar (section-id | chapter | part | book | point:<slug>),
        # so both must strip the `point:` prefix and key kind="point" — otherwise a claim homed on a point
        # is misread as a bogus section-id `point:<slug>` and reported as a false-positive DANGLING.
        home_kind = "point" if cl.home.startswith("point:") else universe.unit_kind(cl.home)
        home_symbol = cl.home.removeprefix("point:") if cl.home.startswith("point:") else cl.home
        _add(index, home_symbol, home_kind,
             Dependent(view="claims", element=cl.id, role="claim-home"))
        for site in cl.asserted_at:
            if site == cl.home:
                continue  # home already recorded above; keep one edge per (claim, site)
            kind = "point" if site.startswith("point:") else universe.unit_kind(site)
            symbol = site.removeprefix("point:") if site.startswith("point:") else site
            _add(index, symbol, kind,
                 Dependent(view="claims", element=cl.id, role="claim-assertion"))

    # Stable order: sort dependents within each symbol for a deterministic artifact.
    for slot in index.values():
        slot["dependents"].sort(key=lambda d: (d["view"], d["role"], d["element"]))
    return index


# ---- structural drift: a view reference to a symbol the source no longer DEFINES --------------------

def point_findings() -> "list[str]":
    """The `point`-decorator drift findings — a DUPLICATE slug (two paragraphs induced to the SAME canonical
    point, the machine version of a redundancy — the terseness audit) and a MALFORMED decorator (a
    `<!-- point: … -->` with no `|` separator, so its slug/text never parsed). Structural + deterministic,
    so it lives on the same footing as the dangling-reference walk. Text-content honesty (does the paragraph
    still make the point?) stays a SEMANTIC review-gate audit, not this lint."""
    findings: "list[str]" = []
    # DUPLICATE slug — a redundancy signal. Two decorators sharing a slug are the exact-match redundancy the
    # canonical-point model is meant to surface.
    seen: "dict[str, tuple[str, int]]" = {}
    for slug, chap, idx in point_occurrences():
        if slug in seen:
            fc, fi = seen[slug]
            findings.append(f"DUPLICATE point slug {slug!r} — {chap}::block-{idx} and {fc}::block-{fi} induce "
                            f"the same canonical point (a redundancy — collapse or re-point one)")
        else:
            seen[slug] = (chap, idx)
    # MALFORMED — a `point` directive whose argument had no `|`, so slug/text are None.
    doc = bs.book_ir.parse_book()
    for c in doc.chapters:
        for b in c.blocks:
            if b.directive == "point" and not b.point_slug:
                findings.append(f"MALFORMED point decorator in {c.slug}::block-{b.index} — {b.raw.strip()!r} "
                                f"has no `<slug> | <text>` split")
    return findings


def term_findings() -> "list[str]":
    """The `term-tags-registered` findings — every tagged-term slug (a point's `terms:` entry, tier-2; a
    `<!-- section-terms: … -->` entry, tier-1) must resolve to a REGISTERED term in the two-tier registry
    (`index-terms.md` §"Term tiers") carrying a tier. An unregistered slug is a finding — it names a concept
    no term registry knows, so the two-tier model has no tier for it. Structural + deterministic (a set
    membership test against the registry), so it lives on the same footing as the dangling-reference walk."""
    registry = _registered_terms()
    findings: "list[str]" = []
    for term, tier, chap, role, idx in term_occurrences():
        if term not in registry:
            findings.append(f"UNREGISTERED term {term!r} — tagged as {role} ({tier}) at {chap}::block-{idx} "
                            f"but not in the two-tier registry (add `- term: {term} | section|local` to "
                            f"index-terms.md, or register it as a `- concept:`)")
    return findings


def role_tier_findings() -> "list[str]":
    """The role↔tier consistency findings — a `<!-- section-terms: … -->` slug plays the **tier-1 role**
    (it names a major concept the section develops), so it must resolve to a term REGISTERED at tier
    `section`. A slug registered `local` (a fine-grained tier-2 paragraph term) used in a section-terms
    marker is a tier-role mismatch: either the term earns promotion to `section`, or the marker should
    name the section's true tier-1 concept instead. Paragraph `terms:` (tier-2 role) slugs are
    unconstrained — a `section` concept may be reused at paragraph granularity, and a `local` is expected
    there. Structural + deterministic (one registry-tier lookup per section-term occurrence), so it lives
    on the same footing as the registration walk. An UNREGISTERED slug (no tier at all) is left to
    `term_findings()`; this check speaks only to registered slugs carrying the wrong tier for the role."""
    registry = _registered_terms()
    findings: "list[str]" = []
    for term, _tier, chap, role, idx in term_occurrences():
        if role == "section-term" and registry.get(term) == "local":
            findings.append(f"TIER-ROLE MISMATCH {term!r} — used in a `section-terms` marker (tier-1 role) "
                            f"at {chap}::block-{idx} but registered `local` (tier-2); promote it with "
                            f"`- term: {term} | section` in index-terms.md, or re-tag the marker with the "
                            f"section's true tier-1 concept")
    return findings


def structural_findings() -> "list[str]":
    """Every view->md reference re-resolved against the CURRENT source. A dangling reference — a section id
    / chapter / part / concept / label / point a view points at that the book no longer defines — is a
    finding. The reverse index makes this a single walk over the inverted edges, plus the point-decorator
    drift walk (duplicate + malformed slugs). (STRUCTURAL half of the two-kind drift split — a lint.)"""
    universe = derive_universe()
    index = build_index()
    findings: "list[str]" = []
    for key, slot in sorted(index.items()):
        kind = slot["kind"]
        symbol = key.split(":", 1)[1]  # strip the kind namespace back to the bare slug (DESIGN §10.4)
        if not universe.resolves(symbol, kind):
            dep_summary = ", ".join(f"{d['view']}:{d['element']}({d['role']})" for d in slot["dependents"])
            findings.append(f"DANGLING {kind} {symbol!r} — referenced by {len(slot['dependents'])} view "
                            f"element(s) but the book no longer defines it: {dep_summary}")
    findings.extend(point_findings())
    return findings


# ---- materialization --------------------------------------------------------------------------------

def to_jsonable(index: "dict[str, dict] | None" = None) -> dict:
    if index is None:
        index = build_index()
    universe = derive_universe()
    by_kind: "dict[str, int]" = {}
    for slot in index.values():
        by_kind[slot["kind"]] = by_kind.get(slot["kind"], 0) + 1
    total_edges = sum(len(slot["dependents"]) for slot in index.values())
    return {
        "_provenance": _PROVENANCE,
        "_counts": {
            "symbols_depended_on": len(index),
            "reverse_edges": total_edges,
            "by_symbol_kind": dict(sorted(by_kind.items())),
            "universe": {
                "section_ids": len(universe.section_ids), "concepts": len(universe.concepts),
                "labels": len(universe.labels), "refs": len(universe.refs),
                "chapters": len(universe.chapters), "parts": len(universe.parts),
                "points": len(universe.points), "terms": len(universe.terms),
                "claims": len(universe.claims),
            },
        },
        # "<kind>:<slug>" -> {kind, dependents:[{view, element, role}]} — keys NAMESPACED by kind
        # (DESIGN §10.4) so a term slug that equals a section-id slug stays two distinct entries; keys
        # sorted for a stable diff.
        "index": {k: index[k] for k in sorted(index)},
    }


def regenerate() -> int:
    payload = to_jsonable()
    with open(_ARTIFACT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    c = payload["_counts"]
    print(f"wrote {os.path.relpath(_ARTIFACT)} — {c['symbols_depended_on']} symbols depended on by "
          f"{c['reverse_edges']} reverse edge(s); by kind {c['by_symbol_kind']}")
    findings = structural_findings()
    if findings:
        print(f"  {len(findings)} structural-drift finding(s) (audit-only — see tests/book_models.py):")
        for f in findings:
            print(f"    {f}")
    return 0


def load_artifact() -> "dict | None":
    if not os.path.isfile(_ARTIFACT):
        return None
    return json.load(open(_ARTIFACT, encoding="utf-8"))


def verify() -> int:
    """FRESHNESS drift check as a CLI: assert the on-disk artifact equals a fresh inversion. A stale
    artifact (a view edited, the index not regenerated) is the finding. (FRESHNESS half of the split.)"""
    stored = load_artifact()
    if stored is None:
        print(f"no {os.path.relpath(_ARTIFACT)} — run `regenerate` first")
        return 1
    fresh = to_jsonable()
    if stored.get("index") != fresh["index"] or stored.get("_counts") != fresh["_counts"]:
        print("DRIFT: reverse_index.json disagrees with a fresh inversion — regenerate")
        return 1
    print(f"reverse_index.json is in sync ({fresh['_counts']['symbols_depended_on']} symbols)")
    return 0


def deps(symbol: str) -> int:
    """Answer "edit this symbol -> which view elements break?" — the inverted lookup. Prints every view
    element that depends on `symbol`, with its role, and whether the symbol currently resolves in the
    source (a non-resolving symbol is itself a dangling / structural-drift signal)."""
    index = build_index()
    universe = derive_universe()
    # The index is keyed `<kind>:<slug>` (DESIGN §10.4), but a caller passes a bare slug. A slug can carry
    # more than one KIND — a `semantic-gap` concept AND a `semantic-gap` section id are two entries — so
    # gather every namespaced match and print each with its own (correct) kind label. That union IS the
    # answer the caller wants; namespacing just stops the two senses from merging and mislabeling.
    matches = [(k, index[f"{k}:{symbol}"]) for k in SYMBOL_KINDS if f"{k}:{symbol}" in index]
    if not matches:
        # Not depended on by any view. Say whether it even exists in the source, so the caller can tell
        # "typo / wrong symbol" from "real symbol, but no view rides it (safe to edit)".
        defined = any(universe.resolves(symbol, k) for k in SYMBOL_KINDS)
        where = "IS defined in the source but no built view depends on it (safe to edit)" if defined \
            else "is NOT a defined symbol in the source (typo, or a symbol no view tracks)"
        print(f"{symbol!r}: no dependents — {where}")
        return 0
    for kind, slot in matches:
        resolves = universe.resolves(symbol, kind)
        flag = "" if resolves else "  ⚠ DANGLING — the source no longer defines this symbol"
        print(f"{symbol!r} ({kind}){flag}")
        print(f"  {len(slot['dependents'])} view element(s) depend on it:")
        for d in slot["dependents"]:
            print(f"    - {d['view']}: {d['element']}  [{d['role']}]")
    return 0


def main(argv: "list[str]") -> int:
    cmd = argv[1] if len(argv) > 1 else "regenerate"
    if cmd == "regenerate":
        return regenerate()
    if cmd == "verify":
        return verify()
    if cmd == "deps":
        if len(argv) < 3:
            print(f"usage: {argv[0]} deps <symbol>")
            return 2
        return deps(argv[2])
    print(f"usage: {argv[0]} [regenerate|verify|deps <symbol>]")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
