#!/usr/bin/env python3
"""Codemod (rule #28): 4b — rename the ENFORCEMENT-sense authority-bearing INTERNAL identifiers.

Successor to the 4a conceptual migration (which renamed the enforcement sense of "authority" in all
VISIBLE text and kept every internal id). 4b renames the identifiers that carry the enforcement sense —
point-IDs, section anchors, term-keys, and figure-asset basenames/labels — with each new id mirroring the
point's already-migrated (post-4a) text. GENUINE professional/decision authority (Parts 6-7) and
AUTHORITATIVE-SOURCE ("the authoritative model") ids are KEPT (not in the table below).

Deterministic token rename across tracked, non-derived source files. Two safety properties (both hold):
  * No OUTPUT contains the substring "authorit" — so no output contains any input; the map cannot cascade.
  * Applied LONGEST-KEY-FIRST, which resolves the nested-substring families
    (`provenance-carried-authority-is-...` ⊃ `provenance-carried-authority`;
     `...-where-authority-can-act` [point-id] vs `3.1-where-authority-can-act` [slug, C3 only]).

SLICES (--slice):
  a  (default) — Commit A: 41 point-IDs + 3 anchors/term-keys + `provenance-carried-authority`
                 (anchor+asset, one token) + 4 other asset basenames. Zero published-chapter-URL impact.
  c3          — the 3.1 chapter slug ONLY (`3.1-where-authority-can-act`). Breaks the published chapter
                 URL; run separately after the coordinator surfaces the URL decision to the user.

File renames the codemod does NOT do (run alongside, same commit): `git mv` for the 5 §3 SVGs (slice a)
and the §1 md file (slice c3); `git rm book/3.1-where-authority-can-act.html` (slice c3).

SKIPPED (regenerate / out of scope): *.html (regenerated from .md), book/_design/** (design scratch),
*_typst* (gitignored print projection), book/d2-pilot/** (unshipped pilot legacy), and any JSON carrying
a GENERATED provenance header (derived; regenerated by its model .py).

Usage: python3 tools/dev/rename_authority_ids.py [--slice a|c3] [--apply]   (default: slice a, dry-run).
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

# --- Slice A: point-IDs (41) + term-key/anchors (guidance-vs, guidance-or, inset-*) + the shared
# provenance-carried-authority token (anchor + asset) + 4 other asset basenames. ---
_A = [
    # point-IDs (§2a)
    ("a-governed-obligation-carries-an-authoritative-consequence-appropriate-to-its-risk",
     "a-governed-obligation-carries-a-binding-consequence-appropriate-to-its-risk"),
    ("a-validator-should-not-get-more-authority-than-its-evidence-surface-warrants",
     "a-validator-should-not-get-more-gating-power-than-its-evidence-surface-warrants"),
    ("agentic-work-provides-identifiable-interfaces-where-authority-can-act",
     "agentic-work-provides-identifiable-interfaces-where-enforcement-can-act"),
    ("align-places-authority-at-the-earliest-boundary-with-the-semantics-to-decide-it",
     "align-places-enforcement-at-the-earliest-boundary-with-the-semantics-to-decide-it"),
    ("authority-can-act-at-several-boundaries-choose-where-the-obligation-is-visible",
     "enforcement-can-act-at-several-boundaries-choose-where-the-obligation-is-visible"),
    ("authority-is-not-determinism", "enforcement-is-not-determinism"),
    ("authority-must-reside-outside-the-agent", "enforcement-must-reside-outside-the-agent"),
    ("authority-needs-an-independent-obligation-and-a-legible-boundary",
     "enforcement-needs-an-independent-obligation-and-a-legible-boundary"),
    ("authority-remains-separate", "enforcement-remains-separate"),
    ("begin-with-two-inventories-representation-and-authority",
     "begin-with-two-inventories-representation-and-enforcement"),
    ("discovery-is-not-authority-a-representation-must-earn-trust",
     "discovery-does-not-confer-trust-a-representation-must-earn-it"),
    ("do-not-make-authority-the-automatic-destination-of-every-guidance",
     "do-not-make-enforcement-the-automatic-destination-of-every-guidance"),
    ("execution-consumes-the-computation-model-so-it-has-authority-over-composition",
     "execution-consumes-the-computation-model-so-it-governs-composition"),
    ("give-important-properties-independent-authority",
     "give-important-properties-independent-enforcement"),
    ("guidance-aims-authority-binds", "guidance-aims-enforcement-binds"),
    ("guidance-influences-behavior-authority-constrains-consequences",
     "guidance-influences-behavior-enforcement-constrains-consequences"),
    ("mage-improves-recurring-work-two-ways-support-the-reasoner-or-give-obligations-authority",
     "mage-improves-recurring-work-two-ways-support-the-reasoner-or-enforce-obligations"),
    ("measurement-boundary-modeling-and-authority-are-separate",
     "measurement-boundary-modeling-and-enforcement-are-separate"),
    ("measurement-earns-authority-when-the-number-is-deterministic",
     "measurement-earns-a-gate-when-the-number-is-deterministic"),
    ("modeling-changes-economics-alignment-changes-authority",
     "modeling-changes-economics-alignment-changes-enforcement"),
    ("modeling-changes-representation-alignment-gives-authority",
     "modeling-changes-representation-alignment-enforces-obligations"),
    ("most-systems-mix-surfaces-which-deserve-authority",
     "most-systems-mix-surfaces-which-deserve-enforcement"),
    ("not-all-operating-structure-is-authoritative", "not-all-operating-structure-is-binding"),
    ("packaging-confers-no-authority-but-a-skill-can-carry-or-invoke-the-machinery",
     "packaging-enforces-nothing-but-a-skill-can-carry-or-invoke-the-machinery"),
    ("part-2-ends-where-part-3-begins-the-models-already-pay-authority-is-a-separate-question",
     "part-2-ends-where-part-3-begins-the-models-already-pay-enforcement-is-a-separate-question"),
    ("part-three-placed-authority-at-the-earliest-legible-boundary",
     "part-three-placed-enforcement-at-the-earliest-legible-boundary"),
    ("place-authority-at-the-earliest-boundary-where-the-obligation-is-legible-and-enforceable",
     "place-enforcement-at-the-earliest-boundary-where-the-obligation-is-legible-and-decidable"),
    ("provenance-carried-authority-is-the-derivation-path-case-of-conformance",
     "provenance-carried-admission-is-the-derivation-path-case-of-conformance"),
    ("provenance-makes-a-derivation-path-authoritative",
     "provenance-makes-a-derivation-path-sanctioned"),
    ("represented-intent-becomes-authoritative-through-one-of-four-roles",
     "represented-intent-becomes-enforceable-through-one-of-four-roles"),
    ("richer-representations-enlarge-the-surface-next-chapter-asks-what-deserves-authority",
     "richer-representations-enlarge-the-surface-next-chapter-asks-what-deserves-enforcement"),
    ("substantial-authority-can-exist-without-rich-models",
     "substantial-enforcement-can-exist-without-rich-models"),
    ("the-boundary-is-not-fixed-judgment-can-acquire-authority-over-time",
     "the-boundary-is-not-fixed-judgment-can-acquire-enforcement-over-time"),
    ("the-grade-is-a-model-read-metric-not-an-authority", "the-grade-is-a-model-read-metric-not-a-gate"),
    ("the-mechanism-that-discovers-need-not-carry-the-authority",
     "the-mechanism-that-discovers-need-not-carry-the-enforcement"),
    ("the-move-toward-authority-is-an-opportunity-not-a-required-progression",
     "the-move-toward-enforcement-is-an-opportunity-not-a-required-progression"),
    ("the-skill-makes-operating-procedure-repeatable-not-authoritative",
     "the-skill-makes-operating-procedure-repeatable-not-binding"),
    ("the-two-problems-representation-and-authority", "the-two-problems-representation-and-enforcement"),
    ("the-two-representations-carry-different-authority-even-with-strong-correspondence",
     "the-two-representations-play-different-governing-roles-even-with-strong-correspondence"),
    ("traceability-connects-intent-realization-evidence-without-conferring-authority",
     "traceability-connects-intent-realization-evidence-without-enforcement"),
    ("whichever-validator-supplies-the-judgment-authority-depends-on-the-environment",
     "whichever-validator-supplies-the-judgment-the-consequence-depends-on-the-environment"),
    # term-key + section anchors (§4) — bare provenance-carried-authority covers anchor + asset (§3)
    ("guidance-vs-authority", "guidance-vs-enforcement"),
    ("guidance-or-authority", "guidance-or-enforcement"),
    ("inset-authority-conditional", "inset-enforcement-conditional"),
    ("provenance-carried-authority", "provenance-carried-admission"),
    # other asset basenames (§3)
    ("cost-authority-gradient", "cost-enforcement-gradient"),
    ("modeling-perp-authority", "modeling-perp-enforcement"),
    ("question-to-authority-progression", "question-to-consequence-progression"),
    ("representation-authority", "representation-enforcement"),
]

# --- Slice C3: the chapter slug only (published-URL break). ---
_C3 = [
    ("3.1-where-authority-can-act", "3.1-where-obligations-can-be-enforced"),
]


def _tracked_files() -> list[Path]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return [ROOT / line for line in out.splitlines() if line]


def _skip(rel: str) -> bool:
    if rel.endswith(".html"):
        return True
    if rel.startswith("book/_design/"):
        return True
    if rel.startswith("book/d2-pilot/"):
        return True
    if "_typst" in rel:
        return True
    return False


def _is_generated(path: Path) -> bool:
    if path.suffix != ".json":
        return False
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:600]
    except OSError:
        return False
    return '"_provenance": "GENERATED' in head


def main() -> int:
    apply = "--apply" in sys.argv
    slice_name = "a"
    if "--slice" in sys.argv:
        slice_name = sys.argv[sys.argv.index("--slice") + 1]
    table = {"a": _A, "c3": _C3}[slice_name]

    # Cascade guard: no output may contain any input token (all inputs contain "authorit"; no output does).
    inputs = {frm for frm, _ in table}
    for _frm, to in table:
        for other in inputs:
            if other in to:
                raise SystemExit(f"CASCADE GUARD FAILED: output {to!r} contains input {other!r}")

    # Longest-key-first resolves nested-substring families deterministically.
    replacements = sorted(table, key=lambda kv: len(kv[0]), reverse=True)

    per_token: dict[str, int] = {frm: 0 for frm, _ in replacements}
    changed: list[tuple[str, int]] = []
    for path in _tracked_files():
        rel = path.relative_to(ROOT).as_posix()
        if _skip(rel) or _is_generated(path) or path == Path(__file__):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        new = text
        file_hits = 0
        for frm, to in replacements:
            n = new.count(frm)
            if n:
                per_token[frm] += n
                file_hits += n
                new = new.replace(frm, to)
        if file_hits:
            changed.append((rel, file_hits))
            if apply:
                path.write_text(new, encoding="utf-8")

    mode = "APPLIED" if apply else "DRY-RUN"
    print(f"[{mode}] 4b authority-id rename — slice {slice_name!r} ({len(table)} token(s))")
    for frm, to in replacements:
        if per_token[frm]:
            print(f"  {per_token[frm]:>4}  {frm}\n        -> {to}")
    zero = [frm for frm, _ in replacements if not per_token[frm]]
    if zero:
        print(f"  ZERO-HIT tokens ({len(zero)}) — expected only if a source has no such id yet:")
        for frm in zero:
            print(f"        {frm}")
    print(f"  total files touched: {len(changed)}")
    for rel, n in sorted(changed):
        print(f"    {n:>4}  {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
