#!/usr/bin/env python3
"""Codemod (rule #28): retire the Modeling/Alignment *Thesis* concept slug tokens to *Principle*.

Deterministic token rename across tracked, non-derived source files. Four base tokens cover every
compound by substring: `card-thesis-modeling`->`card-modeling-principle`, `bi-modeling-thesis`->
`bi-modeling-principle`, the descriptive content slugs (`the-modeling-thesis-in-its-weakest-form` etc.),
and the `concept-*-thesis.(md|html)` filename refs all contain one of the four base tokens, so the four
rules transform them correctly. No rule's OUTPUT contains any rule's INPUT, so the replacements do not
cascade and order is irrelevant (a fixed order is used for reproducibility).

Case-SENSITIVE by design: it must NOT touch capitalized prose ("Modeling Thesis", "Modeling-Thesis axis")
or the bare word "thesis"/"synthesis"/"hypothesis" — only the lowercase hyphenated concept-id slugs.

SKIPPED (regenerate / out of scope): *.html (regenerated from .md), book/_design/** (design scratch),
*_typst* (print projector — untouched this pass), and any JSON carrying a GENERATED provenance header
(derived; regenerated by its model .py). CSS design tokens (box-thesis-*, class thesis-box) are a separate
styling SSOT and are intentionally NOT renamed here.

Usage: python3 tools/dev/rename_thesis_slugs.py [--apply]   (default: dry-run report).
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

# Fixed order; non-cascading (see module docstring).
REPLACEMENTS = [
    ("thesis-modeling", "modeling-principle"),
    ("thesis-alignment", "alignment-principle"),
    ("modeling-thesis", "modeling-principle"),
    ("alignment-thesis", "alignment-principle"),
]


def _tracked_files() -> list[Path]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return [ROOT / line for line in out.splitlines() if line]


def _skip(rel: str) -> bool:
    if rel.endswith(".html"):
        return True
    if rel.startswith("book/_design/"):
        return True
    if "_typst" in rel:
        return True
    return False


def _is_generated(path: Path) -> bool:
    if path.suffix != ".json":
        return False
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:600]
    except OSError:
        return False
    return '"_provenance": "GENERATED' in head


def main() -> int:
    apply = "--apply" in sys.argv
    per_token: dict[str, int] = {frm: 0 for frm, _ in REPLACEMENTS}
    changed: list[tuple[str, int]] = []
    for path in _tracked_files():
        rel = path.relative_to(ROOT).as_posix()
        if _skip(rel) or _is_generated(path):
            continue
        if path == Path(__file__):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        new = text
        file_hits = 0
        for frm, to in REPLACEMENTS:
            n = new.count(frm)
            if n:
                per_token[frm] += n
                file_hits += n
                new = new.replace(frm, to)
        if file_hits:
            changed.append((rel, file_hits))
            if apply:
                path.write_text(new, encoding="utf-8")

    mode = "APPLIED" if apply else "DRY-RUN"
    print(f"[{mode}] thesis-slug -> principle-slug rename")
    for frm, to in REPLACEMENTS:
        print(f"  {frm:>18} -> {to:<20}  {per_token[frm]:>4} occurrence(s)")
    print(f"  total files touched: {len(changed)}")
    for rel, n in sorted(changed):
        print(f"    {n:>4}  {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
