#!/usr/bin/env python3
"""Generate the Extended Figure Gallery — every SVG figure in the repo, LIVE ones (referenced by a
chapter) above a big divider, the ones we are NOT using below it (finished-but-unreferenced in
book/assets/, then draft-only in book/_design/), with section intros and a jump-to-unused button.

A DEV/REVIEW artifact, not a shipped page: it inlines every SVG (incl. unused + WIP figures), so it is
gitignored and EXCLUDED from the orphan-reachability gate. It is regenerated as a step of
`catalog.py build` (and can be run standalone). Output: book/_design/extended-figures.html.

Stdlib-only (catalog.py is stdlib-only). Run:  python3 book/build_extended_figures.py
"""
from __future__ import annotations
import glob
import html
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # repo root (parent of book/)
OUT = os.path.join(ROOT, "book/_design/extended-figures.html")
_PROVENANCE = ("<!-- GENERATED by book/build_extended_figures.py (a step of `catalog.py build`) — DO NOT "
               "EDIT; gitignored + orphan-gate-excluded dev artifact. Regen: python3 book/build_extended_figures.py -->")

_FIG_RE = re.compile(r'<!--\s*figure:\s*([^|>]+\.svg)\s*(?:\|\s*(.*?))?-->', re.S)


def _book_md_files() -> list[str]:
    out = []
    for root, _, files in os.walk(os.path.join(ROOT, "book")):
        if "_design" in root or "node_modules" in root:
            continue
        out += [os.path.join(root, f) for f in files if f.endswith(".md")]
    return out


def _live_map() -> dict[str, tuple[str, str]]:
    """basename -> (caption, chapter-slug) for every figure referenced in a live chapter."""
    m: dict[str, tuple[str, str]] = {}
    for md in _book_md_files():
        slug = os.path.splitext(os.path.basename(md))[0]
        text = open(md, encoding="utf-8").read()
        for mt in _FIG_RE.finditer(text):
            base = os.path.basename(mt.group(1).strip())
            cap = re.sub(r"\s+", " ", (mt.group(2) or "").strip())
            cap = re.sub(r"\[(?:cite|note|ref|data):[^\]]*\]", "", cap)  # drop markers
            cap = re.sub(r"[*_`]", "", cap)
            if base not in m:
                m[base] = (cap, slug)
    return m


def _referenced_basenames(root: str) -> set[str]:
    """SVG basenames mentioned ANYWHERE in the repo's tracked text (build code, typst templates, JSON models,
    navigation) — 'used' even when the reference is not a chapter `<!-- figure: -->` directive. This is what
    keeps cover art, nav-subway panels, and build-referenced glyphs out of the 'unused' bucket."""
    refs: set[str] = set()
    globs = ("book/**/*.py", "book/**/*.typ", "book/**/*.json", "book/**/*.md", "book/**/*.js",
             "book-models/**/*.py", "book-models/**/*.json", "*.py")
    for g in globs:
        for f in glob.glob(os.path.join(root, g), recursive=True):
            if "_design" in f or "node_modules" in f or f.endswith("extended-figures.html"):
                continue
            try:
                txt = open(f, encoding="utf-8", errors="ignore").read()
            except OSError:
                continue
            for m in re.finditer(r'[\w./+-]+\.svg', txt):
                refs.add(os.path.basename(m.group(0)))
    return refs


def _inline_svg(path: str) -> str:
    try:
        s = open(path, encoding="utf-8").read()
    except Exception:  # noqa: BLE001 — a review tool skips an unreadable figure rather than aborting the build
        return '<div class="err">— could not read —</div>'
    s = re.sub(r"<\?xml[^>]*\?>", "", s)
    s = re.sub(r"<!DOCTYPE[^>]*>", "", s)
    s = re.sub(r'(<svg\b[^>]*?)\swidth="[^"]*"', r"\1", s, count=1)   # let CSS scale it (viewBox stays)
    s = re.sub(r'(<svg\b[^>]*?)\sheight="[^"]*"', r"\1", s, count=1)
    return s.strip()


def _card(base: str, path: str, sub: str) -> str:
    return (f'<figure class="card" id="fig-{html.escape(base)}">'
            f'<div class="svgbox">{_inline_svg(path)}</div>'
            f'<figcaption><span class="fname">{html.escape(base)}</span>'
            f'{sub}</figcaption></figure>')


def build_extended_figures(root: str = ROOT, out: str = OUT) -> tuple[int, int, int]:
    """Emit the gallery to `out`; returns (live, unused, draft) counts."""
    live = _live_map()
    assets = {os.path.basename(p): p for p in glob.glob(os.path.join(root, "book/assets/*.svg"))}
    referenced = _referenced_basenames(root)
    live_bases = sorted(b for b in assets if b in live)
    used_bases = sorted(b for b in assets if b not in live and b in referenced)   # cover, nav, build-referenced
    unused_bases = sorted(b for b in assets if b not in live and b not in referenced)  # referenced nowhere
    draft_only: dict[str, str] = {}
    for p in glob.glob(os.path.join(root, "book/_design/**/*.svg"), recursive=True):
        b = os.path.basename(p)
        if b not in assets and "mermaid" not in p:
            draft_only.setdefault(b, p)

    live_cards = []
    for b in live_bases:
        cap, slug = live[b]
        cap_h = html.escape(cap[:200] + ("…" if len(cap) > 200 else "")) if cap else "<em>no caption</em>"
        live_cards.append(_card(b, assets[b], f'<span class="used">§ {html.escape(slug)}</span>'
                                              f'<span class="cap">{cap_h}</span>'))
    used_cards = [_card(b, assets[b], '<span class="tag usedel">used outside chapters</span>')
                  for b in used_bases]
    unused_cards = [_card(b, assets[b], '<span class="tag unused">referenced nowhere</span>')
                    for b in unused_bases]
    draft_cards = [_card(b, p, f'<span class="tag draft">draft only</span>'
                              f'<span class="cap">{html.escape(os.path.relpath(p, root))}</span>')
                   for b, p in sorted(draft_only.items())]

    doc = f"""{_PROVENANCE}
<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Extended Figure Gallery — MAGE</title>
<style>
:root{{--ink:#1c1917;--muted:#57534e;--rule:#e4e0d8;--page:#fdfcf9;--card:#fff;
--green:#155c38;--rust:#9a3f12;--amber:#faf1e6;}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--page);color:var(--ink);
font-family:"Source Sans 3",-apple-system,"Segoe UI",sans-serif;line-height:1.5}}
header{{position:sticky;top:0;z-index:10;background:rgba(253,252,249,.94);
backdrop-filter:blur(6px);border-bottom:1px solid var(--rule);padding:18px 28px}}
h1{{font-family:"Source Serif 4",Georgia,serif;font-size:24px;margin:0 0 4px}}
.counts{{color:var(--muted);font-size:14px}} .counts b{{color:var(--ink)}}
.jump{{margin-top:10px;display:flex;gap:10px;flex-wrap:wrap}}
.jump a{{text-decoration:none;font-size:13px;font-weight:600;padding:7px 13px;border-radius:8px;
border:1px solid var(--rule);color:var(--ink);background:#fff}}
.jump a.hot{{background:var(--rust);color:#fff;border-color:var(--rust)}}
main{{padding:12px 28px 80px}} section{{margin-top:26px}}
.intro{{max-width:70ch;color:var(--muted);font-size:15px;margin:6px 0 18px}} .intro b{{color:var(--ink)}}
h2{{font-family:"Source Serif 4",Georgia,serif;font-size:20px;margin:0}}
.divider{{margin:52px 0 12px;border:0;border-top:3px double var(--rust);position:relative;height:0}}
.divider span{{position:absolute;top:-13px;left:50%;transform:translateX(-50%);
background:var(--page);padding:0 16px;color:var(--rust);font-weight:700;font-size:13px;
letter-spacing:.06em;text-transform:uppercase}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:18px}}
.card{{margin:0;background:var(--card);border:1px solid var(--rule);border-radius:12px;
overflow:hidden;display:flex;flex-direction:column}}
.svgbox{{padding:14px;display:flex;align-items:center;justify-content:center;
min-height:150px;overflow:auto;background:#fff}}
.svgbox svg{{max-width:100%;height:auto;max-height:340px}}
figcaption{{border-top:1px solid var(--rule);padding:10px 12px;font-size:12.5px;
display:flex;flex-direction:column;gap:4px;background:#fbfaf7}}
.fname{{font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:12px;color:var(--ink);word-break:break-all}}
.used{{color:var(--green);font-weight:600}} .cap{{color:var(--muted)}}
.tag{{font-weight:700;font-size:11px;letter-spacing:.04em;text-transform:uppercase;width:max-content;
padding:2px 8px;border-radius:6px}}
.tag.usedel{{background:#eef3f8;color:#345}} .tag.unused{{background:var(--amber);color:var(--rust)}} .tag.draft{{background:#eef2ef;color:var(--green)}}
.err{{color:#b91c1c;font-size:12px}}
</style></head><body>
<header>
<h1>Extended Figure Gallery <span style="font-weight:400;color:var(--muted);font-size:16px">— every SVG in the book repo</span></h1>
<div class="counts"><b>{len(live_cards)}</b> live · <b>{len(used_cards)}</b> used outside chapters (cover/nav/build) · <b>{len(unused_cards)}</b> unused (referenced nowhere) · <b>{len(draft_cards)}</b> draft-only</div>
<nav class="jump"><a href="#live">Live</a><a class="hot" href="#unused">↓ Jump to unused figures</a><a href="#drafts">Draft-only</a></nav>
</header>
<main>
<section id="live">
<h2>Live — in the current book</h2>
<p class="intro">These <b>{len(live_cards)}</b> figures are referenced by a chapter and appear in the
published book and in <b>figures.html</b>. Each card notes the section that uses it and its caption.</p>
<div class="grid">{''.join(live_cards)}</div>
</section>
<section id="used">
<h2>Used outside chapters — cover, navigation, and build assets</h2>
<p class="intro">These <b>{len(used_cards)}</b> SVGs are in <b>book/assets/</b> and <b>are used</b> — the cover
art, the navigation panels, glyphs, and other assets the build, typst templates, or nav code reference
directly rather than through a chapter <code>&lt;!-- figure: … --&gt;</code> directive. They do not appear
in <b>figures.html</b> (which lists chapter figures only), but they are not unused.</p>
<div class="grid">{''.join(used_cards)}</div>
</section>
<div class="divider"><span>not currently used ↓</span></div>
<section id="unused">
<h2>Unused — finished figures nobody links to</h2>
<p class="intro">These <b>{len(unused_cards)}</b> SVGs live in <b>book/assets/</b> — committed, finished
renderings — but no chapter references them, so they never reach <b>figures.html</b> or the book. Candidates
to <b>wire in</b> (add a <code>&lt;!-- figure: … --&gt;</code>) or <b>retire</b>.</p>
<div class="grid">{''.join(unused_cards)}</div>
</section>
<section id="drafts">
<h2>Draft-only — never promoted to assets/</h2>
<p class="intro">These <b>{len(draft_cards)}</b> SVGs exist only under <b>book/_design/</b> (the working area,
not committed to the shipped tree) — earlier explorations and unfinished figures. Raw material, not finished art.</p>
<div class="grid">{''.join(draft_cards)}</div>
</section>
</main></body></html>"""
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8").write(doc)
    return len(live_cards), len(used_cards), len(unused_cards), len(draft_cards)


def main() -> int:
    lv, us, un, dr = build_extended_figures()
    print(f"extended-figures: wrote {os.path.relpath(OUT, ROOT)} — live={lv} used-elsewhere={us} "
          f"unused={un} draft={dr} ({os.path.getsize(OUT)//1024} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
