#!/usr/bin/env python3
"""build_writing_style.py — emit the MAGE communication-style exports.

Assembles the standing self-communicate legs into self-contained single-file Markdown exports, one per
leg, from the sources DECLARED in the skill's `manifest.json` (`legs.<leg>.distribution`):

  - book/mage-writing-style.md    — the writing stack (prose)
  - book/mage-presenting-style.md — the presenting stack (talks + decks)
  - book/mage-drawing-style.md    — the drawing stack (diagrams / charts / tables / figures)

The manifest says WHAT feeds each export (its `distribution.inputs` + `generator`); this module owns HOW
those sources are synthesized (concatenated verbatim, each preceded by a full-width rule, a
`# [CATEGORY — name]` label, and a `# source:` line). No file list lives here — it is read from the
manifest, so the export cannot drift from the skill's structural model. These are GENERATED distribution
artifacts, not sources of truth: gitignored build artifacts (like book/mage-book.pdf), created never
committed, regenerated on every book/PDF build. Stdlib-only, so it runs on a fresh clone.
"""

from __future__ import annotations

import datetime
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SKILL_ROOT = ROOT / "plugin" / "mage" / "skills" / "self-communicate"
MANIFEST = SKILL_ROOT / "manifest.json"

RULE = "=" * 100  # the full-width section boundary


def _load_manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def _category(leg_key: str, leg: dict, src: str) -> str:
    """The `# [CATEGORY …]` bucket for one input: the skill entry, or the leg it belongs to."""
    return "SELF-COMMUNICATE" if src == leg["_entrypoint"] else leg["title"].upper()


def _provenance_lines() -> list[str]:
    return [
        "<!--",
        "AUTO-GENERATED by book/build_writing_style.py from the self-communicate manifest.json — regenerated",
        "by the book build (build_book.py); do not hand-edit. A gitignored build artifact, like",
        "book/mage-book.pdf: created, never committed. Edit the source files (or the manifest), then rebuild.",
        "-->",
    ]


def _intro_lines(leg: dict) -> list[str]:
    today = datetime.date.today().isoformat()
    return [
        f"# MAGE — {leg['title'].lower()} stack",
        "",
        f"**Generated {today}** from `talks-and-notes/governance-catalog/`. {leg['description']}",
        "",
        "This is the complete standing stack for this communication leg, assembled from the sources the",
        "skill's `manifest.json` declares for it, so the export cannot drift from the skill. Each section",
        "below reproduces one source file verbatim, preceded by a full-width rule, a `# [CATEGORY — name]`",
        "header, and a `# source:` line naming the file it was drawn from.",
    ]


def render(leg_key: str, leg: dict) -> str:
    """Assemble one leg's export from its manifest-declared distribution inputs. Skips an absent optional
    overlay input (`*.local.md`) silently; fails loud on any other missing input."""
    entry = leg["_entrypoint"]
    optional = {o["local"] for o in leg.get("overlays", []) if o.get("optional", False)}
    lines: list[str] = []
    lines += _provenance_lines()
    lines += [""]
    lines += _intro_lines(leg)
    lines += ["", "---"]

    for src in leg["distribution"]["inputs"]:
        path = SKILL_ROOT / src
        if not path.is_file():
            if src in optional:
                continue
            raise FileNotFoundError(f"{leg_key}-stack distribution input missing: {path}")
        content = path.read_text(encoding="utf-8").rstrip("\n")
        category = "SELF-COMMUNICATE" if src == entry else leg["title"].upper()
        lines += ["", "", ""]
        lines += [RULE, f"# [{category} — {pathlib.Path(src).name}]", f"# source: `{src}`", RULE, ""]
        lines += content.split("\n")
    return "\n".join(lines) + "\n"


def build_all(root: pathlib.Path = ROOT) -> list[pathlib.Path]:
    """Emit every leg's export to book/. Returns the paths written, in manifest order."""
    m = _load_manifest()
    entry = m["skill"]["entrypoint"]
    written = []
    for leg_key, leg in m["legs"].items():
        leg = {**leg, "_entrypoint": entry}
        out_path = HERE / leg["distribution"]["path"]
        out_path.write_text(render(leg_key, leg), encoding="utf-8")
        written.append(out_path)
    return written


def build_writing_style(root: pathlib.Path = ROOT, out_path: pathlib.Path | None = None) -> pathlib.Path:
    """Back-compat entry: emit just the writing-leg export."""
    m = _load_manifest()
    leg = {**m["legs"]["writing"], "_entrypoint": m["skill"]["entrypoint"]}
    dest = out_path if out_path is not None else (HERE / leg["distribution"]["path"])
    dest.write_text(render("writing", leg), encoding="utf-8")
    return dest


def main() -> int:
    for path in build_all():
        print(f"style export: {path.name} ({path.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
