#!/usr/bin/env python3
"""Generate the Visual Aids gallery — every FIGURE and TABLE in the book repo, with its actual book number
(Figure 6.5-2, Table 4.2-1) so it is ctrl-F-able, its full caption, and its in-book / not-in-book status.

Sections, top to bottom:
  • Figures in the book — numbered, full caption, rendered SVG, links to where it appears.
  • Tables in the book  — numbered, caption, link.
  • (divider: not in the book)
  • Used outside chapters — cover, navigation, build/glyph assets referenced by code, not a chapter figure.
  • Unused — SVGs in book/assets/ referenced nowhere.
  • Draft-only — SVGs that live only under book/_design/.

Numbers come from the build's own `list-of-figures.html` (the authoritative reading-order numbering); each
in-book figure joins to its SVG asset + full caption via the per-chapter source `<!-- figure: -->` directives
(source order == numbering order). A DEV/REVIEW artifact — inlines unused + WIP figures — so it is gitignored
and orphan-gate-excluded. Regenerated as a step of `catalog.py build`; also runnable standalone.

Stdlib-only. Run:  python3 book/build_visual_aids.py
"""
from __future__ import annotations
import glob
import html
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # repo root (parent of book/)
OUT = os.path.join(ROOT, "book/_design/visual-aids.html")
_LOF = os.path.join(ROOT, "book/list-of-figures.html")
_PROVENANCE = ("<!-- GENERATED by book/build_visual_aids.py (a step of `catalog.py build`) — DO NOT EDIT; "
               "gitignored + orphan-gate-excluded dev artifact. Regen: python3 book/build_visual_aids.py -->")

_FIG_RE = re.compile(r'<!--\s*figure:\s*([^|>]+\.svg)\s*\|\s*(.*?)\s*-->', re.S)
_LOF_FIG_RE = re.compile(r'<li><a href="([^"]+)#(fig-[^"]+)">(Figure [^<]+)</a>\s*—\s*([^<]*)</li>')
_LOF_TBL_RE = re.compile(r'<li><a href="([^"]+)#(tbl-[^"]+)">(Table [^<]+)</a>\s*—\s*([^<]*)</li>')


def _clean_caption(raw: str) -> str:
    """A figure directive's caption, made display-ready: drop the `[short: …]` list form and any
    `[cite|note|ref|data:…]` markers, unwrap markdown emphasis to plain text."""
    c = re.sub(r"\[short:[^\]]*\]", "", raw)
    c = re.sub(r"\[(?:cite|note|ref|data):[^\]]*\]", "", c)
    c = re.sub(r"[*_`]", "", c)
    return re.sub(r"\s+", " ", c).strip()


def _book_md_files() -> list[str]:
    out = []
    for root, _, files in os.walk(os.path.join(ROOT, "book")):
        if "_design" in root or "node_modules" in root:
            continue
        out += [os.path.join(root, f) for f in files if f.endswith(".md")]
    return out


def _source_figures_by_slug() -> dict[str, list[tuple[str, str]]]:
    """slug (chapter-file stem) -> ordered [(asset-basename, full-caption)] from `<!-- figure: -->` directives."""
    out: dict[str, list[tuple[str, str]]] = {}
    for md in _book_md_files():
        slug = os.path.splitext(os.path.basename(md))[0]
        rows: list[tuple[str, str]] = []
        for mt in _FIG_RE.finditer(open(md, encoding="utf-8").read()):
            rows.append((os.path.basename(mt.group(1).strip()), _clean_caption(mt.group(2))))
        if rows:
            out[slug] = rows
    return out


def _lof_floats() -> tuple[list[dict], list[dict]]:
    """Parse list-of-figures.html -> (figures, tables), each a list of {slug, anchor, num, short} in order."""
    if not os.path.isfile(_LOF):
        return [], []
    t = open(_LOF, encoding="utf-8").read()
    figs = [{"slug": h.split(".html")[0], "anchor": a, "num": n.strip(), "short": html.unescape(s).strip()}
            for h, a, n, s in _LOF_FIG_RE.findall(t)]
    tbls = [{"slug": h.split(".html")[0], "anchor": a, "num": n.strip(), "short": html.unescape(s).strip()}
            for h, a, n, s in _LOF_TBL_RE.findall(t)]
    return figs, tbls


def _referenced_basenames(root: str) -> set[str]:
    """SVG basenames mentioned anywhere in tracked text (build/typst/json/nav) — 'used' without a chapter
    directive. Keeps cover art, nav panels, and build-referenced glyphs out of the 'unused' bucket."""
    refs: set[str] = set()
    for g in ("book/**/*.py", "book/**/*.typ", "book/**/*.json", "book/**/*.md", "book/**/*.js",
              "book-models/**/*.py", "book-models/**/*.json", "*.py"):
        for f in glob.glob(os.path.join(root, g), recursive=True):
            if "_design" in f or "node_modules" in f or f.endswith(("visual-aids.html", "extended-figures.html")):
                continue
            try:
                txt = open(f, encoding="utf-8", errors="ignore").read()
            except OSError:
                continue
            for m in re.finditer(r'[\w./+-]+\.svg', txt):
                refs.add(os.path.basename(m.group(0)))
    return refs


def _inline_svg(path: str) -> str:
    try:
        s = open(path, encoding="utf-8").read()
    except Exception:  # noqa: BLE001 — a review tool skips an unreadable figure rather than aborting the build
        return '<div class="err">— could not read —</div>'
    s = re.sub(r"<\?xml[^>]*\?>", "", s)
    s = re.sub(r"<!DOCTYPE[^>]*>", "", s)
    s = re.sub(r'(<svg\b[^>]*?)\swidth="[^"]*"', r"\1", s, count=1)
    s = re.sub(r'(<svg\b[^>]*?)\sheight="[^"]*"', r"\1", s, count=1)
    return s.strip()


def _num_card(num: str, base: str, path: str, chapter: str, caption: str) -> str:
    return (f'<figure class="card" id="{html.escape(base)}">'
            f'<div class="svgbox">{_inline_svg(path)}</div>'
            f'<figcaption><span class="num">{html.escape(num)}</span>'
            f'<span class="cap full">{html.escape(caption) or "<em>no caption</em>"}</span>'
            f'<span class="meta">{html.escape(base)} · § {html.escape(chapter)}</span></figcaption></figure>')


def _plain_card(base: str, path: str, tag_html: str) -> str:
    return (f'<figure class="card" id="{html.escape(base)}">'
            f'<div class="svgbox">{_inline_svg(path)}</div>'
            f'<figcaption><span class="fname">{html.escape(base)}</span>{tag_html}</figcaption></figure>')


def build_visual_aids(root: str = ROOT, out: str = OUT) -> tuple[int, int, int, int, int]:
    """Emit the gallery; returns (figures, tables, used_elsewhere, unused, draft) counts."""
    lof_figs, lof_tbls = _lof_floats()
    src = _source_figures_by_slug()
    assets = {os.path.basename(p): p for p in glob.glob(os.path.join(root, "book/assets/*.svg"))}
    referenced = _referenced_basenames(root)

    # Join list-of-figures numbers to source figures per chapter (both in reading order).
    numbered: list[dict] = []      # {num, base, path, chapter, caption}
    in_book: set[str] = set()
    from collections import defaultdict
    by_slug: dict[str, list[dict]] = defaultdict(list)
    for f in lof_figs:
        by_slug[f["slug"]].append(f)
    for slug, figs in by_slug.items():
        srows = src.get(slug, [])
        for i, f in enumerate(figs):
            base, cap = (srows[i] if i < len(srows) else (None, f["short"]))
            if base and base in assets:
                in_book.add(base)
                numbered.append({"num": f["num"], "base": base, "path": assets[base],
                                 "chapter": slug, "caption": cap or f["short"]})
            else:  # inline/mermaid figure with no assets/*.svg — list it by number + short caption, no image
                numbered.append({"num": f["num"], "base": base or "(inline)", "path": None,
                                 "chapter": slug, "caption": cap or f["short"]})

    used_bases = sorted(b for b in assets if b not in in_book and b in referenced)
    unused_bases = sorted(b for b in assets if b not in in_book and b not in referenced)
    draft_only: dict[str, str] = {}
    for p in glob.glob(os.path.join(root, "book/_design/**/*.svg"), recursive=True):
        b = os.path.basename(p)
        if b not in assets and "mermaid" not in p:
            draft_only.setdefault(b, p)

    fig_cards = []
    for r in numbered:
        if r["path"]:
            fig_cards.append(_num_card(r["num"], r["base"], r["path"], r["chapter"], r["caption"]))
        else:
            fig_cards.append(f'<figure class="card noimg"><figcaption><span class="num">{html.escape(r["num"])}'
                             f'</span><span class="cap full">{html.escape(r["caption"])}</span>'
                             f'<span class="meta">rendered figure (no standalone SVG) · § {html.escape(r["chapter"])}'
                             f'</span></figcaption></figure>')
    tbl_cards = [f'<figure class="card noimg"><figcaption><span class="num tbl">{html.escape(t["num"])}</span>'
                 f'<span class="cap full">{html.escape(t["short"])}</span>'
                 f'<span class="meta">table · § {html.escape(t["slug"])}</span></figcaption></figure>'
                 for t in lof_tbls]
    used_cards = [_plain_card(b, assets[b], '<span class="tag usedel">used outside chapters</span>')
                  for b in used_bases]
    unused_cards = [_plain_card(b, assets[b], '<span class="tag unused">referenced nowhere</span>')
                    for b in unused_bases]
    draft_cards = [_plain_card(b, p, f'<span class="tag draft">draft only</span>'
                              f'<span class="cap">{html.escape(os.path.relpath(p, root))}</span>')
                   for b, p in sorted(draft_only.items())]

    doc = f"""{_PROVENANCE}
<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Visual Aids — MAGE (figures & tables)</title>
<style>
:root{{--ink:#1c1917;--muted:#57534e;--rule:#e4e0d8;--page:#fdfcf9;--card:#fff;
--green:#155c38;--rust:#9a3f12;--amber:#faf1e6;--blue:#2f5c8f;}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--page);color:var(--ink);font-family:"Source Sans 3",-apple-system,"Segoe UI",sans-serif;line-height:1.5}}
header{{position:sticky;top:0;z-index:10;background:rgba(253,252,249,.94);backdrop-filter:blur(6px);border-bottom:1px solid var(--rule);padding:18px 28px}}
h1{{font-family:"Source Serif 4",Georgia,serif;font-size:24px;margin:0 0 4px}}
.counts{{color:var(--muted);font-size:14px}} .counts b{{color:var(--ink)}}
.jump{{margin-top:10px;display:flex;gap:10px;flex-wrap:wrap}}
.jump a{{text-decoration:none;font-size:13px;font-weight:600;padding:7px 13px;border-radius:8px;border:1px solid var(--rule);color:var(--ink);background:#fff}}
.jump a.hot{{background:var(--rust);color:#fff;border-color:var(--rust)}}
main{{padding:12px 28px 80px}} section{{margin-top:26px}}
.intro{{max-width:72ch;color:var(--muted);font-size:15px;margin:6px 0 18px}} .intro b{{color:var(--ink)}}
h2{{font-family:"Source Serif 4",Georgia,serif;font-size:20px;margin:0}}
.divider{{margin:52px 0 12px;border:0;border-top:3px double var(--rust);position:relative;height:0}}
.divider span{{position:absolute;top:-13px;left:50%;transform:translateX(-50%);background:var(--page);padding:0 16px;color:var(--rust);font-weight:700;font-size:13px;letter-spacing:.06em;text-transform:uppercase}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:18px}}
.card{{margin:0;background:var(--card);border:1px solid var(--rule);border-radius:12px;overflow:hidden;display:flex;flex-direction:column}}
.card.noimg figcaption{{border-top:0}}
.svgbox{{padding:14px;display:flex;align-items:center;justify-content:center;min-height:150px;overflow:auto;background:#fff}}
.svgbox svg{{max-width:100%;height:auto;max-height:360px}}
figcaption{{border-top:1px solid var(--rule);padding:11px 13px;font-size:13px;display:flex;flex-direction:column;gap:5px;background:#fbfaf7}}
.num{{font-weight:700;color:var(--rust);font-size:14px}} .num.tbl{{color:var(--blue)}}
.cap.full{{color:var(--ink)}} .cap{{color:var(--muted)}}
.meta{{font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:11.5px;color:var(--muted);word-break:break-all}}
.fname{{font-family:"IBM Plex Mono",ui-monospace,monospace;font-size:12px;color:var(--ink);word-break:break-all}}
.tag{{font-weight:700;font-size:11px;letter-spacing:.04em;text-transform:uppercase;width:max-content;padding:2px 8px;border-radius:6px}}
.tag.usedel{{background:#eef3f8;color:var(--blue)}} .tag.unused{{background:var(--amber);color:var(--rust)}} .tag.draft{{background:#eef2ef;color:var(--green)}}
.err{{color:#b91c1c;font-size:12px}}
</style></head><body>
<header>
<h1>Visual Aids <span style="font-weight:400;color:var(--muted);font-size:16px">— every figure &amp; table in the book</span></h1>
<div class="counts"><b>{len(fig_cards)}</b> figures · <b>{len(tbl_cards)}</b> tables · <b>{len(used_cards)}</b> used outside chapters · <b>{len(unused_cards)}</b> unused · <b>{len(draft_cards)}</b> draft-only. Numbers (Figure 6.5-2, Table 4.2-1) are the book's own — ctrl-F them.</div>
<nav class="jump"><a href="#figures">Figures</a><a href="#tables">Tables</a><a class="hot" href="#notinbook">↓ Not in the book</a></nav>
</header>
<main>
<section id="figures">
<h2>Figures in the book</h2>
<p class="intro">All <b>{len(fig_cards)}</b> figures, in reading order, each labeled with its actual book number
(<b>Figure X.Y-Z</b>) and full caption. Ctrl-F a number to find a figure.</p>
<div class="grid">{''.join(fig_cards)}</div>
</section>
<section id="tables">
<h2>Tables in the book</h2>
<p class="intro">All <b>{len(tbl_cards)}</b> tables, by number (<b>Table X.Y-Z</b>) and caption. Tables render
as HTML in their chapters, so no thumbnail here — the number + caption make them findable.</p>
<div class="grid">{''.join(tbl_cards)}</div>
</section>
<div class="divider" id="notinbook"><span>not in the book ↓</span></div>
<section id="used">
<h2>Used outside chapters — cover, navigation, build assets</h2>
<p class="intro">These <b>{len(used_cards)}</b> SVGs are used — the cover art, navigation panels, glyphs, and
assets the build/typst/nav code reference directly rather than through a chapter figure. Not unused.</p>
<div class="grid">{''.join(used_cards)}</div>
</section>
<section id="unused">
<h2>Unused — referenced nowhere</h2>
<p class="intro">These <b>{len(unused_cards)}</b> SVGs sit in <b>book/assets/</b> but are referenced nowhere —
candidates to wire in or retire.</p>
<div class="grid">{''.join(unused_cards)}</div>
</section>
<section id="drafts">
<h2>Draft-only — never promoted to assets/</h2>
<p class="intro">These <b>{len(draft_cards)}</b> SVGs exist only under <b>book/_design/</b> — working-area
explorations, not shipped.</p>
<div class="grid">{''.join(draft_cards)}</div>
</section>
</main></body></html>"""
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8").write(doc)
    return len(fig_cards), len(tbl_cards), len(used_cards), len(unused_cards), len(draft_cards)


def main() -> int:
    fg, tb, us, un, dr = build_visual_aids()
    print(f"visual-aids: wrote {os.path.relpath(OUT, ROOT)} — figures={fg} tables={tb} "
          f"used-elsewhere={us} unused={un} draft={dr} ({os.path.getsize(OUT)//1024} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
