#!/usr/bin/env python3
"""build_writing_style.py — emit book/mage-writing-style.md, the MAGE "full writing stack" export.

Concatenates the standing writing-stack source files — the `self-communicate` skill entry, its
`writing/` resources, and the house style — into one file, each source preceded by a full-width rule,
a `# [CATEGORY — name]` label, and a `# source:` line. The SOURCES table below is the single source of
truth for the file list, labels, and order.

Stdlib-only (no dependencies), so it runs on a fresh clone. Called from `book/build_book.py` so the
export regenerates on every book/PDF build; the emitted file is a gitignored build artifact (like
`book/mage-book.pdf`) — created, never committed.
"""

from __future__ import annotations

import datetime
import pathlib
import sys

# The catalogue root (parent of book/) and the emitted artifact path.
HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
OUT_PATH = HERE / "mage-writing-style.md"

# Single source of truth: (category, label-note, path-relative-to-root), in export order.
# The category feeds the section header `# [CATEGORY — note]`; the path is reproduced verbatim on the
# `# source:` line and read for the section body.
SOURCES: list[tuple[str, str, str]] = [
    ("SELF-COMMUNICATE", "skill entry",
     "plugin/mage/skills/self-communicate/SKILL.md"),
    ("WRITING", "voice.md (THE voice guide)",
     "plugin/mage/skills/self-communicate/writing/voice.md"),
    ("WRITING", "rhetoric.md",
     "plugin/mage/skills/self-communicate/writing/rhetoric.md"),
    ("WRITING", "engineering.md",
     "plugin/mage/skills/self-communicate/writing/engineering.md"),
    ("WRITING", "lexicon.md (upstream-owned)",
     "plugin/mage/skills/self-communicate/writing/lexicon.md"),
    ("WRITING", "lexicon.local.md (adopter-owned)",
     "plugin/mage/skills/self-communicate/writing/lexicon.local.md"),
    ("WRITING", "document-types.md",
     "plugin/mage/skills/self-communicate/writing/document-types.md"),
    ("WRITING", "audit.md (self-review checklist)",
     "plugin/mage/skills/self-communicate/writing/audit.md"),
    ("HOUSE STYLE", "book/AGENTS.md (format + build + conventions)",
     "book/AGENTS.md"),
    ("HOUSE STYLE", "submodule CLAUDE.md (catalogue + book conventions)",
     "CLAUDE.md"),
]

RULE = "=" * 100  # the full-width section boundary


def _provenance_lines() -> list[str]:
    """The auto-generated banner, re-emitted on every run (a hand-edit is overwritten on the next build)."""
    return [
        "<!--",
        "AUTO-GENERATED by book/build_writing_style.py — regenerated by the book build (build_book.py);",
        "do not hand-edit. This file is a gitignored build artifact, like book/mage-book.pdf: created,",
        "never committed. Edit the source files listed in each `# source:` line, then rebuild.",
        "-->",
    ]


def _intro_lines() -> list[str]:
    """The title plus the connective meta-narrative that frames the three categories."""
    today = datetime.date.today().isoformat()
    return [
        "# MAGE book — full writing stack",
        "",
        f"**Generated {today}** from `talks-and-notes/governance-catalog/`. This is the complete standing",
        "writing stack a book-writer agent follows, concatenated from source into one file so the whole",
        "guidance can be read (or pondered) in one pass. It gathers three categories:",
        "",
        "- **SELF-COMMUNICATE** — the skill entry that governs how the fleet, and its operator, write prose.",
        "- **WRITING** — the `writing/` resources of that skill: voice, rhetoric, engineering, the",
        "  upstream and adopter-owned lexicons, document-types, and the audit checklist.",
        "- **HOUSE STYLE** — the book-and-catalogue conventions (`book/AGENTS.md` and the submodule",
        "  `CLAUDE.md`), distinct from the self-communicate skill.",
        "",
        "Each section below reproduces one source file verbatim, preceded by a full-width rule, a",
        "`# [CATEGORY — name]` header, and a `# source:` line naming the file it was drawn from.",
    ]


def render(root: pathlib.Path) -> str:
    """Assemble the full export text. Fails loud if any listed source file is missing."""
    lines: list[str] = []
    lines += _provenance_lines()
    lines += [""]
    lines += _intro_lines()
    lines += ["", "---"]

    for category, note, relpath in SOURCES:
        src = root / relpath
        if not src.is_file():
            raise FileNotFoundError(f"writing-stack source missing: {src}")
        content = src.read_text(encoding="utf-8").rstrip("\n")
        # 3 blank lines, then the 4-line boundary block, then 1 blank line, then the verbatim body.
        lines += ["", "", ""]
        lines += [RULE, f"# [{category} — {note}]", f"# source: `{relpath}`", RULE, ""]
        lines += content.split("\n")

    return "\n".join(lines) + "\n"


def build_writing_style(root: pathlib.Path = ROOT, out_path: pathlib.Path = OUT_PATH) -> pathlib.Path:
    """Render the export and write it to out_path. Returns the path written."""
    out_path.write_text(render(root), encoding="utf-8")
    return out_path


def main() -> int:
    out = build_writing_style()
    size = out.stat().st_size
    print(f"writing-stack export: {out} ({size:,} bytes, {len(SOURCES)} sources)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
